services:
 client:
  container_name: HierarchyGeneratorClient
  image: alexandraisaksson/hierarchy-generator-client:latest
  depends_on:
      - api
  ports:
      - "8080:80"
 api:
  container_name: HierarchyGeneratorApi
  image: alexandraisaksson/hierarchy-generator-api:latest
  depends_on:
      db:
        condition: service_healthy
  ports:
      - "1337:80"
 db:
  container_name: HierarchyGeneratorDatabase
  image: alexandraisaksson/hierarchy-generator-database:latest
  environment:
      - MYSQL_ROOT_PASSWORD=password
      - LANG=C.UTF-8
      - MYSQL_CHARSET=utf8mb4
  ports:
     - "3306:3306"
  volumes:
     - mysql_data:/var/lib/mysql
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    interval: 30s
    retries: 5
    start_period: 30s
    timeout: 10s
volumes:
    mysql_data: