services:
 client:
  container_name: HierarchyGeneratorClient
  build:
      context: HierarchyGeneratorClient
      dockerfile: Dockerfile
  depends_on:
      api:
        condition: service_healthy
  ports:
      - "8080:80"
 api:
  container_name: HierarchyGeneratorApi
  build:
      context: HierarchyGeneratorApi
      dockerfile: Dockerfile
  depends_on:
      db:
        condition: service_healthy
  ports:
      - "1337:80"
  healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 10s
 db:
  container_name: HierarchyGeneratorDatabase
  build:
      context: HierarchyGeneratorDatabase
      dockerfile: Dockerfile   
  environment:
      - MYSQL_ROOT_PASSWORD=password
      - LANG=C.UTF-8
      - MYSQL_CHARSET=utf8mb4
  ports:
     - "3306:3306"
  volumes:
     - mysql_data:/var/lib/mysql
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    interval: 30s
    retries: 5
    start_period: 30s
    timeout: 10s
volumes:
    mysql_data: