services:
 client:
  container_name: HierarchyGeneratorClient
  build:
      context: HierarchyGeneratorClient
      dockerfile: Dockerfile
  depends_on:
      - api
  ports:
      - "8080:80"
 api:
  container_name: HierarchyGeneratorApi
  build:
      context: HierarchyGeneratorApi
      dockerfile: Dockerfile
  depends_on:
      db:
        condition: service_healthy
  ports:
      - "1337:80"
 db:
  container_name: HierarchyGeneratorDatabase
  build:
      context: HierarchyGeneratorDatabase
      dockerfile: Dockerfile   
  environment:
      - MYSQL_ROOT_PASSWORD=password
  ports:
     - "3306:3306"
  healthcheck:
    test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    interval: 30s
    retries: 5
    start_period: 30s
    timeout: 10s
 llm:
  container_name: HierarchyGeneratorLLM
  build:
      context: HierarchyGeneratorLLM
      dockerfile: Dockerfile
  ports:
      - "11434:11434"