name: Build ASP.NET API and React App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore .NET Dependencies
        run: dotnet restore HierarchyGeneratorApi

      - name: Build .NET Application
        run: dotnet build HierarchyGeneratorApi --configuration Release --no-restore

  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install Node Dependencies
        run: npm install
        working-directory: HierarchyGeneratorClient

      - name: Build React App
        run: npm run build
        working-directory: HierarchyGeneratorClient
