use hierarchy_generator;

INSERT INTO `NameAdjectives` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('FANTASY', 'PLACE', 'L5', 'A path bound by fate itself'),
   ('FANTASY', 'PLACE', 'L5', 'A twisting dreamscape of time’s passage'),
   ('FANTASY', 'PLACE', 'L5', 'Abandoned Guardhouse'),
   ('FANTASY', 'PLACE', 'L5', 'Abandoned Tunnelways'),
   ('FANTASY', 'PLACE', 'L5', 'Abandoned farmhouse of eerie silence'),
   ('FANTASY', 'PLACE', 'L5', 'Abandoned farmstead of eldritch crops'),
   ('FANTASY', 'PLACE', 'L5', 'Abandoned fortress of last defense'),
   ('FANTASY', 'PLACE', 'L5', 'Abandoned mine shaft of cursed riches'),
   ('FANTASY', 'PLACE', 'L5', 'Alchemy of death’s elixir'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient Catacombs Entrance '),
   ('FANTASY', 'PLACE', 'L5', 'Ancient forces bound in dark stone'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient forge of dark secrets'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient gate of ritual sacrifice'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient keeps crafted from the stone'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient manuscripts of the old world'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient monastery carved into rock'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient paths hidden in the deep'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient ruins shrouded in sea mist'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient secrets buried in salty depths'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient stable beneath the oak’s shadow'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient statues draped in seaweed'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient stone heart of governance'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient stone keep of watchful guardians'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient stone structure of steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient watchtower above the winding road'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient wood of noble beasts'),
   ('FANTASY', 'PLACE', 'L5', 'Anvil of the thunder gods'),
   ('FANTASY', 'PLACE', 'L5', 'Arcane grimoire of forgotten arts'),
   ('FANTASY', 'PLACE', 'L5', 'Armored shields charged with thunder'),
   ('FANTASY', 'PLACE', 'L5', 'Armory crafted by the storm’s will'),
   ('FANTASY', 'PLACE', 'L5', 'Armory of divine soulblades'),
   ('FANTASY', 'PLACE', 'L5', 'Armory of thunder and steel'),
   ('FANTASY', 'PLACE', 'L5', 'Arsenal of divine lightning strikes'),
   ('FANTASY', 'PLACE', 'L5', 'Atlas of uncharted realms'),
   ('FANTASY', 'PLACE', 'L5', 'Banner blazing above morning cloud'),
   ('FANTASY', 'PLACE', 'L5', 'Banners fly for town gathering'),
   ('FANTASY', 'PLACE', 'L5', 'Battle-blessed shrine of radiant glory'),
   ('FANTASY', 'PLACE', 'L5', 'Battle-hardened fortress of ancient kings'),
   ('FANTASY', 'PLACE', 'L5', 'Bay-front refuge beneath bright skies'),
   ('FANTASY', 'PLACE', 'L5', 'Beachfront villa with salty air'),
   ('FANTASY', 'PLACE', 'L5', 'Beacon flaring with burning dawn'),
   ('FANTASY', 'PLACE', 'L5', 'Beacon for civic celebration feasts'),
   ('FANTASY', 'PLACE', 'L5', 'Bell-chimed home of civic duty'),
   ('FANTASY', 'PLACE', 'L5', 'Bell-topped spire for proclamations'),
   ('FANTASY', 'PLACE', 'L5', 'Beneath the ocean’s pulse of time'),
   ('FANTASY', 'PLACE', 'L5', 'Bile runs in sacred patterns'),
   ('FANTASY', 'PLACE', 'L5', 'Blade-forged in the heart of thunder'),
   ('FANTASY', 'PLACE', 'L5', 'Blade-honed steel beneath stormclouds'),
   ('FANTASY', 'PLACE', 'L5', 'Blade-sharp tower of iron might'),
   ('FANTASY', 'PLACE', 'L5', 'Blazing torch-lighted citadel at the edge'),
   ('FANTASY', 'PLACE', 'L5', 'Blight-borne guardians stalk the passage'),
   ('FANTASY', 'PLACE', 'L5', 'Blighted garden of dark fruits'),
   ('FANTASY', 'PLACE', 'L5', 'Blood candles flicker without flame'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-soaked arena of champions'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-wept altars hum with hate'),
   ('FANTASY', 'PLACE', 'L5', 'Bloodstained toll under broken moon'),
   ('FANTASY', 'PLACE', 'L5', 'Bolts of divine power stored here'),
   ('FANTASY', 'PLACE', 'L5', 'Bones and ash swirling in air'),
   ('FANTASY', 'PLACE', 'L5', 'Bones crunch under careless steps'),
   ('FANTASY', 'PLACE', 'L5', 'Bones piled near mossy arch'),
   ('FANTASY', 'PLACE', 'L5', 'Bones write scripture in blood'),
   ('FANTASY', 'PLACE', 'L5', 'Books of unspoken power'),
   ('FANTASY', 'PLACE', 'L5', 'Breaths of the void whispered'),
   ('FANTASY', 'PLACE', 'L5', 'Breezy cabin overlooking the tide'),
   ('FANTASY', 'PLACE', 'L5', 'Breezy lodge with ocean view'),
   ('FANTASY', 'PLACE', 'L5', 'Bridges carved from mountain rock'),
   ('FANTASY', 'PLACE', 'L5', 'Broken wheels litter the banks'),
   ('FANTASY', 'PLACE', 'L5', 'Broken-down Guard Barracks '),
   ('FANTASY', 'PLACE', 'L5', 'Bubbling cauldrons of unholy brew'),
   ('FANTASY', 'PLACE', 'L5', 'Burnt ruins of lost hopes'),
   ('FANTASY', 'PLACE', 'L5', 'Cages of twisted and broken souls'),
   ('FANTASY', 'PLACE', 'L5', 'Candlelit desk of midnight law'),
   ('FANTASY', 'PLACE', 'L5', 'Carrion-laced halls breathe corruption'),
   ('FANTASY', 'PLACE', 'L5', 'Carved cathedrals of stone and light'),
   ('FANTASY', 'PLACE', 'L5', 'Carved tunnels beneath the mountains'),
   ('FANTASY', 'PLACE', 'L5', 'Carved wood seat of counsel'),
   ('FANTASY', 'PLACE', 'L5', 'Cauldron room of heated discussion'),
   ('FANTASY', 'PLACE', 'L5', 'Cavernous depths of shifting reality'),
   ('FANTASY', 'PLACE', 'L5', 'Cavernous entrance to the underworld'),
   ('FANTASY', 'PLACE', 'L5', 'Celestial forge of skysteel blades'),
   ('FANTASY', 'PLACE', 'L5', 'Celestial forges of war’s wrath'),
   ('FANTASY', 'PLACE', 'L5', 'Center of scrolls and oaths'),
   ('FANTASY', 'PLACE', 'L5', 'Central archive of all law'),
   ('FANTASY', 'PLACE', 'L5', 'Chained souls and forgotten rituals'),
   ('FANTASY', 'PLACE', 'L5', 'Chained souls whisper forbidden psalms'),
   ('FANTASY', 'PLACE', 'L5', 'Chains rattle in murky gloom'),
   ('FANTASY', 'PLACE', 'L5', 'Chamber of riddles and puzzles'),
   ('FANTASY', 'PLACE', 'L5', 'Chapel of sun’s holy crown'),
   ('FANTASY', 'PLACE', 'L5', 'Charred bones mark the boundary'),
   ('FANTASY', 'PLACE', 'L5', 'Chiseled towers soaring above'),
   ('FANTASY', 'PLACE', 'L5', 'Chiseled windows into forgotten realms'),
   ('FANTASY', 'PLACE', 'L5', 'Chronicles of forgotten heroes'),
   ('FANTASY', 'PLACE', 'L5', 'Chronicles of the celestial realms'),
   ('FANTASY', 'PLACE', 'L5', 'Chronicles of the mighty empires'),
   ('FANTASY', 'PLACE', 'L5', 'Chronicles of the starbound wanderers'),
   ('FANTASY', 'PLACE', 'L5', 'Circle where fate is sealed'),
   ('FANTASY', 'PLACE', 'L5', 'Cliff-top retreat with ocean view'),
   ('FANTASY', 'PLACE', 'L5', 'Cliffside estate with endless horizon'),
   ('FANTASY', 'PLACE', 'L5', 'Cloud-kissed refuge for sky steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Coastal haven with swaying palms'),
   ('FANTASY', 'PLACE', 'L5', 'Coastal home with wind-chimed gardens'),
   ('FANTASY', 'PLACE', 'L5', 'Cobblestone heart of town rule'),
   ('FANTASY', 'PLACE', 'L5', 'Cobblestone structure for prized steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Codex of the elder seers'),
   ('FANTASY', 'PLACE', 'L5', 'Cold stone tower of rage'),
   ('FANTASY', 'PLACE', 'L5', 'Collapsed Ruin Outpost '),
   ('FANTASY', 'PLACE', 'L5', 'Collapsed Sewer Tunnel '),
   ('FANTASY', 'PLACE', 'L5', 'Collapsed Watchtower Ruins '),
   ('FANTASY', 'PLACE', 'L5', 'Collapsed ruins of forgotten kingdoms'),
   ('FANTASY', 'PLACE', 'L5', 'Collapsed watchtower of forgotten guardians'),
   ('FANTASY', 'PLACE', 'L5', 'Compendium of the elder races'),
   ('FANTASY', 'PLACE', 'L5', 'Coral-clad ruins of divine worship'),
   ('FANTASY', 'PLACE', 'L5', 'Coral-draped pillars of the forgotten'),
   ('FANTASY', 'PLACE', 'L5', 'Coral-encrusted gate to forgotten lands'),
   ('FANTASY', 'PLACE', 'L5', 'Coral-wrapped pavilion overlooking waves'),
   ('FANTASY', 'PLACE', 'L5', 'Corpse-fed fires light the tomb'),
   ('FANTASY', 'PLACE', 'L5', 'Corroded Miners’'),
   ('FANTASY', 'PLACE', 'L5', 'Corrupted blood sigils on stone'),
   ('FANTASY', 'PLACE', 'L5', 'Corrupted den of wicked power'),
   ('FANTASY', 'PLACE', 'L5', 'Corrupted flesh stitched with sinew'),
   ('FANTASY', 'PLACE', 'L5', 'Corrupted sciences that blur reality'),
   ('FANTASY', 'PLACE', 'L5', 'Council’s hearth in city’s heart'),
   ('FANTASY', 'PLACE', 'L5', 'Cozy shack beside the coastline'),
   ('FANTASY', 'PLACE', 'L5', 'Cracked Skeleton Shop '),
   ('FANTASY', 'PLACE', 'L5', 'Cracked mausoleum of restless souls'),
   ('FANTASY', 'PLACE', 'L5', 'Cracked pathway of ancient bones'),
   ('FANTASY', 'PLACE', 'L5', 'Cracked shrine of broken vows'),
   ('FANTASY', 'PLACE', 'L5', 'Cracked skulls and necrotic fluids'),
   ('FANTASY', 'PLACE', 'L5', 'Cracked stone halls where shadows reign'),
   ('FANTASY', 'PLACE', 'L5', 'Cracked well of stagnant waters'),
   ('FANTASY', 'PLACE', 'L5', 'Crafted pathways leading through stone'),
   ('FANTASY', 'PLACE', 'L5', 'Crafted vaults above the earth'),
   ('FANTASY', 'PLACE', 'L5', 'Craggy halls echoing with craft'),
   ('FANTASY', 'PLACE', 'L5', 'Crawling marrow feeds the shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Creaking Old Tavern '),
   ('FANTASY', 'PLACE', 'L5', 'Creaking forge of rusted tools'),
   ('FANTASY', 'PLACE', 'L5', 'Crimson rites beneath pale moon'),
   ('FANTASY', 'PLACE', 'L5', 'Crimson-walled fortress guarding the highlands'),
   ('FANTASY', 'PLACE', 'L5', 'Crimson-washed chapel of forgotten gods'),
   ('FANTASY', 'PLACE', 'L5', 'Crooked ladders lead to lookout'),
   ('FANTASY', 'PLACE', 'L5', 'Crossroads of fate beneath the cliffs'),
   ('FANTASY', 'PLACE', 'L5', 'Crowned haven of winged grace'),
   ('FANTASY', 'PLACE', 'L5', 'Crowned peak above sacred clouds'),
   ('FANTASY', 'PLACE', 'L5', 'Crows circle overhead and never landing'),
   ('FANTASY', 'PLACE', 'L5', 'Crude carvings whisper forgotten curses'),
   ('FANTASY', 'PLACE', 'L5', 'Crude symbols scrawled in blood'),
   ('FANTASY', 'PLACE', 'L5', 'Crumbled Bridge House '),
   ('FANTASY', 'PLACE', 'L5', 'Crumbled Smuggler’s Den '),
   ('FANTASY', 'PLACE', 'L5', 'Crumbled shrine of earth spirits'),
   ('FANTASY', 'PLACE', 'L5', 'Crumbled tavern of lost patrons'),
   ('FANTASY', 'PLACE', 'L5', 'Crumbling sanctum where tides never rest'),
   ('FANTASY', 'PLACE', 'L5', 'Crumbling stairways into darkened waters'),
   ('FANTASY', 'PLACE', 'L5', 'Crumbling tower of dark whispers'),
   ('FANTASY', 'PLACE', 'L5', 'Crushed reliquary of broken faith'),
   ('FANTASY', 'PLACE', 'L5', 'Cryptic runes glowing on stone'),
   ('FANTASY', 'PLACE', 'L5', 'Cryptic texts of the shadowed moon'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal cavern beneath the old path'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal echoes beneath the deep blue'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal gate to the eternal snow'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal heart of radiant sky'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal-laden resting place for unicorns'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal-lit chamber of decisions made'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal-lit home of mystical ponies'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal-lit vault of submerged gods'),
   ('FANTASY', 'PLACE', 'L5', 'Cursed magic bubbling in cauldrons'),
   ('FANTASY', 'PLACE', 'L5', 'Curses laced within enchanted artifacts'),
   ('FANTASY', 'PLACE', 'L5', 'Damp barracks of forgotten soldiers'),
   ('FANTASY', 'PLACE', 'L5', 'Damp crypt of the forgotten dead'),
   ('FANTASY', 'PLACE', 'L5', 'Damp and Forgotten Blacksmith’s Forge '),
   ('FANTASY', 'PLACE', 'L5', 'Dark cave of stolen treasures'),
   ('FANTASY', 'PLACE', 'L5', 'Dark essence that drips like blood'),
   ('FANTASY', 'PLACE', 'L5', 'Dark sigils burning in midnight air'),
   ('FANTASY', 'PLACE', 'L5', 'Dark tendons stretch across thresholds'),
   ('FANTASY', 'PLACE', 'L5', 'Decayed barn of mythical beasts'),
   ('FANTASY', 'PLACE', 'L5', 'Decaying Dockmaster’s Office '),
   ('FANTASY', 'PLACE', 'L5', 'Defender’s hold beneath the cliffs'),
   ('FANTASY', 'PLACE', 'L5', 'Deserted Vault Entrance '),
   ('FANTASY', 'PLACE', 'L5', 'Desolate Guild HQ '),
   ('FANTASY', 'PLACE', 'L5', 'Desolate outpost of the undead'),
   ('FANTASY', 'PLACE', 'L5', 'Devouring void beneath stitched altars'),
   ('FANTASY', 'PLACE', 'L5', 'Dew-kissed barn by the river’s edge'),
   ('FANTASY', 'PLACE', 'L5', 'Dilapidated mansion of ancient ghosts'),
   ('FANTASY', 'PLACE', 'L5', 'Disheveled Priest’s Passage '),
   ('FANTASY', 'PLACE', 'L5', 'Dome of the folk’s will'),
   ('FANTASY', 'PLACE', 'L5', 'Doomed battlefield of endless sacrifice'),
   ('FANTASY', 'PLACE', 'L5', 'Driftwood cottage at water’s edge'),
   ('FANTASY', 'PLACE', 'L5', 'Driftwood porch beside the surf'),
   ('FANTASY', 'PLACE', 'L5', 'Driftwood-strewn home by quiet bay'),
   ('FANTASY', 'PLACE', 'L5', 'Drowned relics whisper beneath the waves'),
   ('FANTASY', 'PLACE', 'L5', 'Drum-marked place of tribal order'),
   ('FANTASY', 'PLACE', 'L5', 'Dust-Caked Druid’s Grove '),
   ('FANTASY', 'PLACE', 'L5', 'Dusty Library of Forgotten Lore '),
   ('FANTASY', 'PLACE', 'L5', 'Dusty library of cursed texts'),
   ('FANTASY', 'PLACE', 'L5', 'Dwarven hollow for sturdy ponies'),
   ('FANTASY', 'PLACE', 'L5', 'Echo of the storm’s fury'),
   ('FANTASY', 'PLACE', 'L5', 'Echoes of a drowned civilization'),
   ('FANTASY', 'PLACE', 'L5', 'Echoes of death’s whispers'),
   ('FANTASY', 'PLACE', 'L5', 'Echoes of shieldmaidens’ chants'),
   ('FANTASY', 'PLACE', 'L5', 'Echoes of the hungering dead'),
   ('FANTASY', 'PLACE', 'L5', 'Echoes of thunder’s ancient roar'),
   ('FANTASY', 'PLACE', 'L5', 'Echoing hall of local power'),
   ('FANTASY', 'PLACE', 'L5', 'Echoing hall where shadows linger'),
   ('FANTASY', 'PLACE', 'L5', 'Echoing halls of thunderous power'),
   ('FANTASY', 'PLACE', 'L5', 'Echoing scrolls of time’s passage'),
   ('FANTASY', 'PLACE', 'L5', 'Echoing temple of unholy vows'),
   ('FANTASY', 'PLACE', 'L5', 'Echoing vaults of hidden treasures'),
   ('FANTASY', 'PLACE', 'L5', 'Elderwood barn of sacred chargers'),
   ('FANTASY', 'PLACE', 'L5', 'Eldritch horrors conjured in twilight'),
   ('FANTASY', 'PLACE', 'L5', 'Electric crackle in battle’s heart'),
   ('FANTASY', 'PLACE', 'L5', 'Electrified defenses for warbound champions'),
   ('FANTASY', 'PLACE', 'L5', 'Embers of the cursed flame'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanted archway of forgotten lands'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanted folios of immortal knowledge'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanted tomes of the forgotten king'),
   ('FANTASY', 'PLACE', 'L5', 'Endless halls of twisting stone'),
   ('FANTASY', 'PLACE', 'L5', 'Endless turns that lead nowhere'),
   ('FANTASY', 'PLACE', 'L5', 'Enduring walls built with skill'),
   ('FANTASY', 'PLACE', 'L5', 'Eternal banquet of rotted kin'),
   ('FANTASY', 'PLACE', 'L5', 'Eternal flame of forgotten tomes'),
   ('FANTASY', 'PLACE', 'L5', 'Ever-open hall of hearing hearts'),
   ('FANTASY', 'PLACE', 'L5', 'Eyeless statues guard the entrance'),
   ('FANTASY', 'PLACE', 'L5', 'Eyeless watchers guard cursed halls'),
   ('FANTASY', 'PLACE', 'L5', 'Eyes peer through rotting walls'),
   ('FANTASY', 'PLACE', 'L5', 'Eyes watching from shadowed corners'),
   ('FANTASY', 'PLACE', 'L5', 'Fabled chambers of lost kings'),
   ('FANTASY', 'PLACE', 'L5', 'Faded frescoes beneath the waves'),
   ('FANTASY', 'PLACE', 'L5', 'Fading Merchant’s Shop '),
   ('FANTASY', 'PLACE', 'L5', 'Feather-etched scrolls of ancient charters'),
   ('FANTASY', 'PLACE', 'L5', 'Feathered blades drawn in peace'),
   ('FANTASY', 'PLACE', 'L5', 'Fetid banners drip cursed ichor'),
   ('FANTASY', 'PLACE', 'L5', 'Filth-bound spirits roam the crypt'),
   ('FANTASY', 'PLACE', 'L5', 'Firescarred citadel of final judgment'),
   ('FANTASY', 'PLACE', 'L5', 'Fisherman’s lodge at dawn’s light'),
   ('FANTASY', 'PLACE', 'L5', 'Fisherman’s retreat at the harbor'),
   ('FANTASY', 'PLACE', 'L5', 'Fisher’s haven beneath starlit skies'),
   ('FANTASY', 'PLACE', 'L5', 'Flame of judgment ever watchful'),
   ('FANTASY', 'PLACE', 'L5', 'Flame-brushed shed for fiery steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Flame-lit stall of war steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Flames that burn the spirit'),
   ('FANTASY', 'PLACE', 'L5', 'Flawless facades shaped by hand'),
   ('FANTASY', 'PLACE', 'L5', 'Flesh-bound scrolls of dark magic'),
   ('FANTASY', 'PLACE', 'L5', 'Flesh-laden wind howls forevermore'),
   ('FANTASY', 'PLACE', 'L5', 'Flickering Lantern Market '),
   ('FANTASY', 'PLACE', 'L5', 'Flooded house of forgotten memories'),
   ('FANTASY', 'PLACE', 'L5', 'Fog-Wrapped Apothecary’s Den '),
   ('FANTASY', 'PLACE', 'L5', 'Fog-drenched stable of phantom steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Forest-bough roof above citizen matters'),
   ('FANTASY', 'PLACE', 'L5', 'Forge fires shaping timeless stone'),
   ('FANTASY', 'PLACE', 'L5', 'Forge of heaven-tempered steel'),
   ('FANTASY', 'PLACE', 'L5', 'Forge where lightning meets steel'),
   ('FANTASY', 'PLACE', 'L5', 'Forgefire fueled by tempests’ rage'),
   ('FANTASY', 'PLACE', 'L5', 'Forges burning bright with stonecraft'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten gateway sealed by the tide'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten gods linger in the deep'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten gods sleep beneath the tide'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten halls beneath the waves'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten halls of silent whispers'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten lore beneath the ocean’s wrath'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten myths and legends'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten prayers whispered by the ocean'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten stone circle of old magic'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten temple guarded by creatures'),
   ('FANTASY', 'PLACE', 'L5', 'Forgotten tombs beneath shifting sands'),
   ('FANTASY', 'PLACE', 'L5', 'Forsaken caravan of rotting supplies'),
   ('FANTASY', 'PLACE', 'L5', 'Forsaken shrine of binding spells'),
   ('FANTASY', 'PLACE', 'L5', 'Forsaken tomb of ancient kings'),
   ('FANTASY', 'PLACE', 'L5', 'Fortress high on thunder’s wing'),
   ('FANTASY', 'PLACE', 'L5', 'Fortresses of lasting strength'),
   ('FANTASY', 'PLACE', 'L5', 'Foul breath hangs in air'),
   ('FANTASY', 'PLACE', 'L5', 'Foul cavern of hidden beasts'),
   ('FANTASY', 'PLACE', 'L5', 'Frost-Glazed Cavern Entrance '),
   ('FANTASY', 'PLACE', 'L5', 'Frost-etched door to village voice'),
   ('FANTASY', 'PLACE', 'L5', 'Frost-kissed sanctuary for northern ponies'),
   ('FANTASY', 'PLACE', 'L5', 'Frostbitten encampment along the ridge'),
   ('FANTASY', 'PLACE', 'L5', 'Frostbitten gate of cruel offerings'),
   ('FANTASY', 'PLACE', 'L5', 'Frostbound records of the lost city'),
   ('FANTASY', 'PLACE', 'L5', 'Frozen shelter for winter beasts'),
   ('FANTASY', 'PLACE', 'L5', 'Frozen temple of forgotten blessings'),
   ('FANTASY', 'PLACE', 'L5', 'Funeral bells ring backward hymns'),
   ('FANTASY', 'PLACE', 'L5', 'Fungal Pathway Beneath '),
   ('FANTASY', 'PLACE', 'L5', 'Fungi bloom on cursed stones'),
   ('FANTASY', 'PLACE', 'L5', 'Funky and crooked barn of twisted crops'),
   ('FANTASY', 'PLACE', 'L5', 'Fury-bound weapons of sky’s rage'),
   ('FANTASY', 'PLACE', 'L5', 'Gasping relics twitch with memory'),
   ('FANTASY', 'PLACE', 'L5', 'Gate of heaven’s passing song'),
   ('FANTASY', 'PLACE', 'L5', 'Gates that lead to madness'),
   ('FANTASY', 'PLACE', 'L5', 'Gathering fire for winter debates'),
   ('FANTASY', 'PLACE', 'L5', 'Ghastly phantoms imprisoned in jars'),
   ('FANTASY', 'PLACE', 'L5', 'Gleaming crystal tower of knowledge'),
   ('FANTASY', 'PLACE', 'L5', 'Glimmering Underdark Mine '),
   ('FANTASY', 'PLACE', 'L5', 'Glimmering haven for starlit steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Glittering chamber of ancient might'),
   ('FANTASY', 'PLACE', 'L5', 'Gloom-filled chamber of shadow’s embrace'),
   ('FANTASY', 'PLACE', 'L5', 'Gloomy tower of dark pacts'),
   ('FANTASY', 'PLACE', 'L5', 'Glowing cauldron of life’s price'),
   ('FANTASY', 'PLACE', 'L5', 'Glowing gate of aurora sky'),
   ('FANTASY', 'PLACE', 'L5', 'Glowing relics rest beneath the deep'),
   ('FANTASY', 'PLACE', 'L5', 'Gnarled bones cradle sleeping wretches'),
   ('FANTASY', 'PLACE', 'L5', 'Gnarled tree roots grip tightly'),
   ('FANTASY', 'PLACE', 'L5', 'Golden-roofed haven for swift flyers'),
   ('FANTASY', 'PLACE', 'L5', 'Grand stone arch of passage'),
   ('FANTASY', 'PLACE', 'L5', 'Granite roads that never falter'),
   ('FANTASY', 'PLACE', 'L5', 'Granite walls carved with precision'),
   ('FANTASY', 'PLACE', 'L5', 'Grave-slick stone leads below'),
   ('FANTASY', 'PLACE', 'L5', 'Grave-touched relics of the damned'),
   ('FANTASY', 'PLACE', 'L5', 'Graveborn lords dwell in silence'),
   ('FANTASY', 'PLACE', 'L5', 'Gravel Path Shrine '),
   ('FANTASY', 'PLACE', 'L5', 'Great monuments carved with precision'),
   ('FANTASY', 'PLACE', 'L5', 'Grime-covered guards grunt for toll'),
   ('FANTASY', 'PLACE', 'L5', 'Grimoire of ancient bloodlines'),
   ('FANTASY', 'PLACE', 'L5', 'Grimoire of lost spells'),
   ('FANTASY', 'PLACE', 'L5', 'Grimy Thief’s Passage '),
   ('FANTASY', 'PLACE', 'L5', 'Grimy sanctuary of forgotten cults'),
   ('FANTASY', 'PLACE', 'L5', 'Gristle-wrapped altar of blasphemy'),
   ('FANTASY', 'PLACE', 'L5', 'Groaning statues of kneeling flesh'),
   ('FANTASY', 'PLACE', 'L5', 'Guardian statue watching the mountain trail'),
   ('FANTASY', 'PLACE', 'L5', 'Guardians of the thunderous sky'),
   ('FANTASY', 'PLACE', 'L5', 'Guardian’s hall carved from ice'),
   ('FANTASY', 'PLACE', 'L5', 'Guardian’s rest under sky’s wrath'),
   ('FANTASY', 'PLACE', 'L5', 'Guttural songs echo through trees'),
   ('FANTASY', 'PLACE', 'L5', 'Half-sunken chapel of unholy rites'),
   ('FANTASY', 'PLACE', 'L5', 'Hall of mirrors that deceive the mind'),
   ('FANTASY', 'PLACE', 'L5', 'Hall of open-handed judgment'),
   ('FANTASY', 'PLACE', 'L5', 'Hall of the world’s secrets'),
   ('FANTASY', 'PLACE', 'L5', 'Hallowed chamber of ancient rites'),
   ('FANTASY', 'PLACE', 'L5', 'Hallowed hall of chosen souls'),
   ('FANTASY', 'PLACE', 'L5', 'Hallowed walls that scream at night'),
   ('FANTASY', 'PLACE', 'L5', 'Halls lost beneath eternal waves'),
   ('FANTASY', 'PLACE', 'L5', 'Halls of the eternal stonecutters'),
   ('FANTASY', 'PLACE', 'L5', 'Halls of the wise seer'),
   ('FANTASY', 'PLACE', 'L5', 'Hammer-struck steel beneath storm’s breath'),
   ('FANTASY', 'PLACE', 'L5', 'Hammer-wrought weapons of storm’s fury'),
   ('FANTASY', 'PLACE', 'L5', 'Hammered steel beneath stormy skies'),
   ('FANTASY', 'PLACE', 'L5', 'Hammered stone of ancient halls'),
   ('FANTASY', 'PLACE', 'L5', 'Harbor-side home with sunlit porch'),
   ('FANTASY', 'PLACE', 'L5', 'Harmonies sung by divine blades'),
   ('FANTASY', 'PLACE', 'L5', 'Haunted relics that curse the living'),
   ('FANTASY', 'PLACE', 'L5', 'Haunting mausoleum of the unseen'),
   ('FANTASY', 'PLACE', 'L5', 'Heartbeat of the common folk'),
   ('FANTASY', 'PLACE', 'L5', 'Heartbeats of the long-dead'),
   ('FANTASY', 'PLACE', 'L5', 'Hearth-warmed gathering place for decisions'),
   ('FANTASY', 'PLACE', 'L5', 'Hearth-warmed stall for swift chargers'),
   ('FANTASY', 'PLACE', 'L5', 'Heaven-kissed edge of valor'),
   ('FANTASY', 'PLACE', 'L5', 'Heavy boots stomp through dusk'),
   ('FANTASY', 'PLACE', 'L5', 'Helm echoing tales of sacrifice'),
   ('FANTASY', 'PLACE', 'L5', 'Hidden cave of dark power'),
   ('FANTASY', 'PLACE', 'L5', 'Hidden crypt of cursed souls'),
   ('FANTASY', 'PLACE', 'L5', 'Hidden treasures buried in ocean ruins'),
   ('FANTASY', 'PLACE', 'L5', 'Hidden vault of untold riches'),
   ('FANTASY', 'PLACE', 'L5', 'High tower where seagulls soar'),
   ('FANTASY', 'PLACE', 'L5', 'Highland retreat for noble steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Hollow Echo Inn '),
   ('FANTASY', 'PLACE', 'L5', 'Hollow choir sings through sinew'),
   ('FANTASY', 'PLACE', 'L5', 'Hollow log drums beat warning'),
   ('FANTASY', 'PLACE', 'L5', 'Hollow mound of forgotten treasures'),
   ('FANTASY', 'PLACE', 'L5', 'Howls answer the toll bell'),
   ('FANTASY', 'PLACE', 'L5', 'Hungered hands claw the gates'),
   ('FANTASY', 'PLACE', 'L5', 'Hungry eyes peek from under'),
   ('FANTASY', 'PLACE', 'L5', 'Inscriptions etched in the stones'),
   ('FANTASY', 'PLACE', 'L5', 'Intricate arches spanning the land'),
   ('FANTASY', 'PLACE', 'L5', 'Iron cage sways in wind'),
   ('FANTASY', 'PLACE', 'L5', 'Iron coffins groan in prayer'),
   ('FANTASY', 'PLACE', 'L5', 'Iron giants of stormborn might'),
   ('FANTASY', 'PLACE', 'L5', 'Iron-chiseled doorways through stone'),
   ('FANTASY', 'PLACE', 'L5', 'Iron-clad outpost at the frontier'),
   ('FANTASY', 'PLACE', 'L5', 'Iron-clad war machines in waiting'),
   ('FANTASY', 'PLACE', 'L5', 'Ivy-wrapped tower of civic order'),
   ('FANTASY', 'PLACE', 'L5', 'Jagged stone keep of shadows'),
   ('FANTASY', 'PLACE', 'L5', 'Journal of the lost cities'),
   ('FANTASY', 'PLACE', 'L5', 'Labyrinth of the immortal ones'),
   ('FANTASY', 'PLACE', 'L5', 'Labyrinthine paths to forbidden knowledge'),
   ('FANTASY', 'PLACE', 'L5', 'Lagoon-side refuge with a breeze'),
   ('FANTASY', 'PLACE', 'L5', 'Lantern-lit center of village life'),
   ('FANTASY', 'PLACE', 'L5', 'Laughter echoes through hollow hills'),
   ('FANTASY', 'PLACE', 'L5', 'Library of ancient dragonkind'),
   ('FANTASY', 'PLACE', 'L5', 'Library of celestial scrolls and maps'),
   ('FANTASY', 'PLACE', 'L5', 'Library of forbidden magical arts'),
   ('FANTASY', 'PLACE', 'L5', 'Library of mystical scrolls and artifacts'),
   ('FANTASY', 'PLACE', 'L5', 'Library of the dragon’s wisdom'),
   ('FANTASY', 'PLACE', 'L5', 'Library of the forgotten lands'),
   ('FANTASY', 'PLACE', 'L5', 'Lichfire burns with cold malice'),
   ('FANTASY', 'PLACE', 'L5', 'Lightning-bathed armaments of the gods'),
   ('FANTASY', 'PLACE', 'L5', 'Lightning-bolted shields of war'),
   ('FANTASY', 'PLACE', 'L5', 'Lightning-infused bladeworks of warriors'),
   ('FANTASY', 'PLACE', 'L5', 'Lonely tower of mourning winds'),
   ('FANTASY', 'PLACE', 'L5', 'Lorekeeper’s bench of dusty records'),
   ('FANTASY', 'PLACE', 'L5', 'Lost city veiled in mist'),
   ('FANTASY', 'PLACE', 'L5', 'Lost ruins held by coral growths'),
   ('FANTASY', 'PLACE', 'L5', 'Lost sanctuary in ocean depths'),
   ('FANTASY', 'PLACE', 'L5', 'Lurking pit of torment'),
   ('FANTASY', 'PLACE', 'L5', 'Lush meadow encircling the guarded pass'),
   ('FANTASY', 'PLACE', 'L5', 'Maggot-thick incense clouds the air'),
   ('FANTASY', 'PLACE', 'L5', 'Magic-sealed ledgers and binding pacts'),
   ('FANTASY', 'PLACE', 'L5', 'Majestic resting place for gallant stallions'),
   ('FANTASY', 'PLACE', 'L5', 'Marble pillars holding up the sky'),
   ('FANTASY', 'PLACE', 'L5', 'Marble seat of wise councilors'),
   ('FANTASY', 'PLACE', 'L5', 'Marketplace echo turned ruling chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Masonry of forgotten empires'),
   ('FANTASY', 'PLACE', 'L5', 'Mastered craft beneath the earth'),
   ('FANTASY', 'PLACE', 'L5', 'Masterwork gates hewn with skill'),
   ('FANTASY', 'PLACE', 'L5', 'Masterworks of stone and flame'),
   ('FANTASY', 'PLACE', 'L5', 'Maw of death breathes invitation'),
   ('FANTASY', 'PLACE', 'L5', 'Maze of eternal echoes and shadows'),
   ('FANTASY', 'PLACE', 'L5', 'Maze of forgotten gods and kings'),
   ('FANTASY', 'PLACE', 'L5', 'Maze of shifting stone and sky'),
   ('FANTASY', 'PLACE', 'L5', 'Maze that shifts with every step'),
   ('FANTASY', 'PLACE', 'L5', 'Meeting ground beneath ancient tree'),
   ('FANTASY', 'PLACE', 'L5', 'Melody rising through starry air'),
   ('FANTASY', 'PLACE', 'L5', 'Melted candles mark each step'),
   ('FANTASY', 'PLACE', 'L5', 'Milky eyes glisten in darkness'),
   ('FANTASY', 'PLACE', 'L5', 'Minds consumed by undead whispers'),
   ('FANTASY', 'PLACE', 'L5', 'Minotaur’s lair of endless stone'),
   ('FANTASY', 'PLACE', 'L5', 'Misty refuge for forest striders'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Mage’s Enclave '),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit cottage on silent shore'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit grove of twisted oaths'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit halls in the ocean’s heart'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit resting ground for desert mounts'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit room of civil discourse'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit ruins hidden beneath the waves'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit tower above the mountain pass'),
   ('FANTASY', 'PLACE', 'L5', 'Moss-Covered Abandoned Temple '),
   ('FANTASY', 'PLACE', 'L5', 'Moss-choked mill of abandoned grain'),
   ('FANTASY', 'PLACE', 'L5', 'Moss-covered gatehouse of old blood'),
   ('FANTASY', 'PLACE', 'L5', 'Moss-covered stones beneath twilight'),
   ('FANTASY', 'PLACE', 'L5', 'Moss-covered tower of forgotten lore'),
   ('FANTASY', 'PLACE', 'L5', 'Mossy sigil of old power'),
   ('FANTASY', 'PLACE', 'L5', 'Mountain-side structures born of stone'),
   ('FANTASY', 'PLACE', 'L5', 'Mud-streaked refuge of hardy ponies'),
   ('FANTASY', 'PLACE', 'L5', 'Muddy Canal Tunnel '),
   ('FANTASY', 'PLACE', 'L5', 'Muddy path of silent travelers'),
   ('FANTASY', 'PLACE', 'L5', 'Mysteries of the dead dissected'),
   ('FANTASY', 'PLACE', 'L5', 'Mysteries of the deep ocean'),
   ('FANTASY', 'PLACE', 'L5', 'Mysterious crypt of cursed relics'),
   ('FANTASY', 'PLACE', 'L5', 'Mysterious hut of fey mischief'),
   ('FANTASY', 'PLACE', 'L5', 'Mystic barn of legendary horses'),
   ('FANTASY', 'PLACE', 'L5', 'Mystic gate of swirling mist'),
   ('FANTASY', 'PLACE', 'L5', 'Mystical pages of the twilight realm'),
   ('FANTASY', 'PLACE', 'L5', 'Nautical haven for wandering souls'),
   ('FANTASY', 'PLACE', 'L5', 'Nightmare-infused flesh and bone'),
   ('FANTASY', 'PLACE', 'L5', 'Noble manor overlooking the gorge'),
   ('FANTASY', 'PLACE', 'L5', 'Oak-walled hall of noble debate'),
   ('FANTASY', 'PLACE', 'L5', 'Oaken-walled haven for loyal steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Obsidian fortress with piercing towers'),
   ('FANTASY', 'PLACE', 'L5', 'Obsidian keep of torment'),
   ('FANTASY', 'PLACE', 'L5', 'Ocean view refuge on the cliff'),
   ('FANTASY', 'PLACE', 'L5', 'Ocean-kissed retreat among the cliffs'),
   ('FANTASY', 'PLACE', 'L5', 'Oceanside villa with seabird songs'),
   ('FANTASY', 'PLACE', 'L5', 'Old Beggar’s Hut '),
   ('FANTASY', 'PLACE', 'L5', 'Oozing roots twist with corpses'),
   ('FANTASY', 'PLACE', 'L5', 'Open porch for public matters'),
   ('FANTASY', 'PLACE', 'L5', 'Outlaw’s lair carved into rock'),
   ('FANTASY', 'PLACE', 'L5', 'Overgrown Thieves’ Hideout '),
   ('FANTASY', 'PLACE', 'L5', 'Overgrown herb shop of dubious remedies'),
   ('FANTASY', 'PLACE', 'L5', 'Overgrown passageways hiding forgotten lore'),
   ('FANTASY', 'PLACE', 'L5', 'Overrun Underground Tavern '),
   ('FANTASY', 'PLACE', 'L5', 'Painted walls of civic pride'),
   ('FANTASY', 'PLACE', 'L5', 'Palm-fringed retreat on the sands'),
   ('FANTASY', 'PLACE', 'L5', 'Passageways that coil like serpents'),
   ('FANTASY', 'PLACE', 'L5', 'Passageways that pulse with dark energy'),
   ('FANTASY', 'PLACE', 'L5', 'Path to the heart of chaos'),
   ('FANTASY', 'PLACE', 'L5', 'Paths carved by the hands of gods'),
   ('FANTASY', 'PLACE', 'L5', 'Paths of flame and shadow intertwined'),
   ('FANTASY', 'PLACE', 'L5', 'Paths that twist with deadly purpose'),
   ('FANTASY', 'PLACE', 'L5', 'Perch where Valkyries gather high'),
   ('FANTASY', 'PLACE', 'L5', 'Pestilent bloom chokes the altar'),
   ('FANTASY', 'PLACE', 'L5', 'Pillared hall of chained souls'),
   ('FANTASY', 'PLACE', 'L5', 'Pillars holding up the heavens'),
   ('FANTASY', 'PLACE', 'L5', 'Place where stories shape policy'),
   ('FANTASY', 'PLACE', 'L5', 'Plague-born monks chant unholy dirges'),
   ('FANTASY', 'PLACE', 'L5', 'Portal to realms unknown and strange'),
   ('FANTASY', 'PLACE', 'L5', 'Pungent stew simmers nearby fire'),
   ('FANTASY', 'PLACE', 'L5', 'Putrid apothecary of questionable concoctions'),
   ('FANTASY', 'PLACE', 'L5', 'Putrid witch’s cottage of dark spells'),
   ('FANTASY', 'PLACE', 'L5', 'Quarry’s heart where stones are born'),
   ('FANTASY', 'PLACE', 'L5', 'Quarry’s edge where stone is shaped'),
   ('FANTASY', 'PLACE', 'L5', 'Quarry’s edge where stone meets soul'),
   ('FANTASY', 'PLACE', 'L5', 'Quiet shelter of green pastures'),
   ('FANTASY', 'PLACE', 'L5', 'Ragged Cartographer’s Study '),
   ('FANTASY', 'PLACE', 'L5', 'Ragged jailhouse of criminal misfits'),
   ('FANTASY', 'PLACE', 'L5', 'Raging fires tempered by the storm'),
   ('FANTASY', 'PLACE', 'L5', 'Rain-worn roof above old justice'),
   ('FANTASY', 'PLACE', 'L5', 'Rainbow bridge’s watchful threshold gate'),
   ('FANTASY', 'PLACE', 'L5', 'Ransacked armory of tarnished steel'),
   ('FANTASY', 'PLACE', 'L5', 'Rat-Crafted Stables '),
   ('FANTASY', 'PLACE', 'L5', 'Rat-Infested Old Warehouse '),
   ('FANTASY', 'PLACE', 'L5', 'Ravaged keep of old curses'),
   ('FANTASY', 'PLACE', 'L5', 'Ravine fortress lost in history'),
   ('FANTASY', 'PLACE', 'L5', 'Records of the moonlit prophecy'),
   ('FANTASY', 'PLACE', 'L5', 'Resting place for fallen champions'),
   ('FANTASY', 'PLACE', 'L5', 'Ritual circle of eternal night'),
   ('FANTASY', 'PLACE', 'L5', 'Ritual-bound forge of steel'),
   ('FANTASY', 'PLACE', 'L5', 'Rituals that tear at existence'),
   ('FANTASY', 'PLACE', 'L5', 'Rituals under the blood moon'),
   ('FANTASY', 'PLACE', 'L5', 'Rock-hewn passages of mastery'),
   ('FANTASY', 'PLACE', 'L5', 'Rock-hewn vaults of endless time'),
   ('FANTASY', 'PLACE', 'L5', 'Rocks turned to splendor'),
   ('FANTASY', 'PLACE', 'L5', 'Roost of the ever-vigilant'),
   ('FANTASY', 'PLACE', 'L5', 'Roost of twilight’s honored fallen'),
   ('FANTASY', 'PLACE', 'L5', 'Root-bound hall of growing governance'),
   ('FANTASY', 'PLACE', 'L5', 'Rot seeps through bone-wrought stone'),
   ('FANTASY', 'PLACE', 'L5', 'Rotten ruins of dead kings'),
   ('FANTASY', 'PLACE', 'L5', 'Rotting Plunderer’s Hut '),
   ('FANTASY', 'PLACE', 'L5', 'Rotting Prison Cells '),
   ('FANTASY', 'PLACE', 'L5', 'Rotting beams creak with warning'),
   ('FANTASY', 'PLACE', 'L5', 'Rotting cadavers on cold stone'),
   ('FANTASY', 'PLACE', 'L5', 'Rotting corpses under the microscope'),
   ('FANTASY', 'PLACE', 'L5', 'Rotting marketplace of cursed trinkets'),
   ('FANTASY', 'PLACE', 'L5', 'Rotting trading post of odd wares'),
   ('FANTASY', 'PLACE', 'L5', 'Royal resting place for winged mounts'),
   ('FANTASY', 'PLACE', 'L5', 'Ruins of a sunken paradise'),
   ('FANTASY', 'PLACE', 'L5', 'Run-down guildhall of shifty merchants'),
   ('FANTASY', 'PLACE', 'L5', 'Rundown alchemist’s lab of foul potions'),
   ('FANTASY', 'PLACE', 'L5', 'Rune-etched walls of lawkeeping lore'),
   ('FANTASY', 'PLACE', 'L5', 'Runes of the world’s birth'),
   ('FANTASY', 'PLACE', 'L5', 'Runestone-etched entrance through the valley'),
   ('FANTASY', 'PLACE', 'L5', 'Rusted blacksmith’s forge of broken tools'),
   ('FANTASY', 'PLACE', 'L5', 'Rusted spikes jut from ground'),
   ('FANTASY', 'PLACE', 'L5', 'Rustic haven for wandering travelers'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred chambers in aquatic shadows'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred codices of celestial truth'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred flame of sworn oaths'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred forges of tempest’s roar'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred hall of sky champions'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred journals of the divine'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred scrolls of endless wisdom'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred shrine at the crossroads'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred site swallowed by the sea'),
   ('FANTASY', 'PLACE', 'L5', 'Sacrificial altar at the mountain’s edge'),
   ('FANTASY', 'PLACE', 'L5', 'Sacrificial pit of unholy rites'),
   ('FANTASY', 'PLACE', 'L5', 'Salt-kissed refuge for sailors'),
   ('FANTASY', 'PLACE', 'L5', 'Salt-sprayed cottage at the inlet'),
   ('FANTASY', 'PLACE', 'L5', 'Salt-stained hideaway by the reef'),
   ('FANTASY', 'PLACE', 'L5', 'Sanctuary of noble sky maidens'),
   ('FANTASY', 'PLACE', 'L5', 'Sanctuary of the ascended brave'),
   ('FANTASY', 'PLACE', 'L5', 'Sanctum blessed by skyward wings'),
   ('FANTASY', 'PLACE', 'L5', 'Sandstone house near the coast'),
   ('FANTASY', 'PLACE', 'L5', 'Sapphire-lit stable of fabled steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Scattered Bones Tomb '),
   ('FANTASY', 'PLACE', 'L5', 'Screeching bats nest above gate'),
   ('FANTASY', 'PLACE', 'L5', 'Screeching bone-flutes echo despair'),
   ('FANTASY', 'PLACE', 'L5', 'Scroll-lit hall of ancestral rulings'),
   ('FANTASY', 'PLACE', 'L5', 'Scrolls of knowledge from distant lands'),
   ('FANTASY', 'PLACE', 'L5', 'Scrolls of the ancient gods'),
   ('FANTASY', 'PLACE', 'L5', 'Scrolls of the eternal flame'),
   ('FANTASY', 'PLACE', 'L5', 'Sculpted fortresses rising from the earth'),
   ('FANTASY', 'PLACE', 'L5', 'Sea-swept cabin beneath cliffs'),
   ('FANTASY', 'PLACE', 'L5', 'Seafarer’s cottage on rocky shore'),
   ('FANTASY', 'PLACE', 'L5', 'Searing magic from forsaken lands'),
   ('FANTASY', 'PLACE', 'L5', 'Seashell-adorned cottage with sea breeze'),
   ('FANTASY', 'PLACE', 'L5', 'Seashell-lined cottage by the dunes'),
   ('FANTASY', 'PLACE', 'L5', 'Seaside lodge nestled in cliffs'),
   ('FANTASY', 'PLACE', 'L5', 'Seaside manor beneath the stars'),
   ('FANTASY', 'PLACE', 'L5', 'Seaward lookout above the bay'),
   ('FANTASY', 'PLACE', 'L5', 'Seaweed-clad shrine of ancient rituals'),
   ('FANTASY', 'PLACE', 'L5', 'Secret corridors hidden beneath ancient stone'),
   ('FANTASY', 'PLACE', 'L5', 'Secret haven for enchanted horses'),
   ('FANTASY', 'PLACE', 'L5', 'Secretive cloister of hidden monks'),
   ('FANTASY', 'PLACE', 'L5', 'Secretive pathway through the mountain rock'),
   ('FANTASY', 'PLACE', 'L5', 'Secrets locked away in eternal halls'),
   ('FANTASY', 'PLACE', 'L5', 'Sentinel post of noble flight'),
   ('FANTASY', 'PLACE', 'L5', 'Severed voices beg for silence'),
   ('FANTASY', 'PLACE', 'L5', 'Shadowed refuge for battlehorses'),
   ('FANTASY', 'PLACE', 'L5', 'Shadows formed by restless spirits'),
   ('FANTASY', 'PLACE', 'L5', 'Shadows stir beneath dripping roots'),
   ('FANTASY', 'PLACE', 'L5', 'Shadowy retreat of roving creatures'),
   ('FANTASY', 'PLACE', 'L5', 'Shaped spires cutting through the sky'),
   ('FANTASY', 'PLACE', 'L5', 'Shattered bones and cursed tomes'),
   ('FANTASY', 'PLACE', 'L5', 'Shattered crypt of blood and bone'),
   ('FANTASY', 'PLACE', 'L5', 'Shattered shrine of fractured souls'),
   ('FANTASY', 'PLACE', 'L5', 'Shattered shrine of the old gods'),
   ('FANTASY', 'PLACE', 'L5', 'Shattered temple of forbidden magic'),
   ('FANTASY', 'PLACE', 'L5', 'Shielded enclave of shared voices'),
   ('FANTASY', 'PLACE', 'L5', 'Shielded stronghold of feathered valor'),
   ('FANTASY', 'PLACE', 'L5', 'Shimmering gateway to the inner realm'),
   ('FANTASY', 'PLACE', 'L5', 'Shimmering light of higher planes'),
   ('FANTASY', 'PLACE', 'L5', 'Shrine where golden honor sleeps'),
   ('FANTASY', 'PLACE', 'L5', 'Shrouded pain clings to stone'),
   ('FANTASY', 'PLACE', 'L5', 'Silent echoes from drowned halls'),
   ('FANTASY', 'PLACE', 'L5', 'Silent hall of forgotten rites'),
   ('FANTASY', 'PLACE', 'L5', 'Silent prayers on mountain wind'),
   ('FANTASY', 'PLACE', 'L5', 'Silent vault where the ancients sleep'),
   ('FANTASY', 'PLACE', 'L5', 'Silver spire above drifting clouds'),
   ('FANTASY', 'PLACE', 'L5', 'Silvered tower gleaming through the night'),
   ('FANTASY', 'PLACE', 'L5', 'Sinew-strung lanterns light the damned'),
   ('FANTASY', 'PLACE', 'L5', 'Sinking timbers sway with weight'),
   ('FANTASY', 'PLACE', 'L5', 'Skeletal priests guard shrines forgotten'),
   ('FANTASY', 'PLACE', 'L5', 'Skin-wrapped scrolls tell vile truths'),
   ('FANTASY', 'PLACE', 'L5', 'Sky-shattered weapons to break foes'),
   ('FANTASY', 'PLACE', 'L5', 'Sky-trained legion of sacred warriors'),
   ('FANTASY', 'PLACE', 'L5', 'Slime trails glisten on planks'),
   ('FANTASY', 'PLACE', 'L5', 'Slime-dripped prayers fuel necromancy'),
   ('FANTASY', 'PLACE', 'L5', 'Sludge flows from nearby cave'),
   ('FANTASY', 'PLACE', 'L5', 'Smashed barrels line the sides'),
   ('FANTASY', 'PLACE', 'L5', 'Smoldering forge of electric fury'),
   ('FANTASY', 'PLACE', 'L5', 'Snow-capped for winter steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Snow-covered bastion at the summit'),
   ('FANTASY', 'PLACE', 'L5', 'Snow-feathered nest of grace'),
   ('FANTASY', 'PLACE', 'L5', 'Soggy cellar of dark rituals'),
   ('FANTASY', 'PLACE', 'L5', 'Soggy dockside tavern of shady deals'),
   ('FANTASY', 'PLACE', 'L5', 'Soot-blackened stones under watchful gaze'),
   ('FANTASY', 'PLACE', 'L5', 'Soul-crushing whispers in the dark'),
   ('FANTASY', 'PLACE', 'L5', 'Souls trapped within crystal prisons'),
   ('FANTASY', 'PLACE', 'L5', 'Spiral passages that unravel time'),
   ('FANTASY', 'PLACE', 'L5', 'Squalid Beggars’ Nest '),
   ('FANTASY', 'PLACE', 'L5', 'Stained banners hang like skins'),
   ('FANTASY', 'PLACE', 'L5', 'Star-forged books of prophecy'),
   ('FANTASY', 'PLACE', 'L5', 'Starlit chamber of old agreements'),
   ('FANTASY', 'PLACE', 'L5', 'Steel-clad bastion of stormfire'),
   ('FANTASY', 'PLACE', 'L5', 'Steel-shaped by the storm’s might'),
   ('FANTASY', 'PLACE', 'L5', 'Stitched horrors bound in silence'),
   ('FANTASY', 'PLACE', 'L5', 'Stone circle of thoughtful order'),
   ('FANTASY', 'PLACE', 'L5', 'Stone columns lost beneath the sea'),
   ('FANTASY', 'PLACE', 'L5', 'Stone corridors leading to wonder'),
   ('FANTASY', 'PLACE', 'L5', 'Stone floors worn with age'),
   ('FANTASY', 'PLACE', 'L5', 'Stone teeth line the path'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-bound craftsmanship in every form'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-bound passages of old'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-bound path of madness and fear'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-carved home for ethereal horses'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-cut paths to the future'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-driven creations that last forever'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-hewn gateways to new realms'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-hewn haven of noble steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-laden rest for stonehoofed beasts'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-towered home for royal steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Stonemason’s workshop at the pass'),
   ('FANTASY', 'PLACE', 'L5', 'Storm-forged echo of flying lances'),
   ('FANTASY', 'PLACE', 'L5', 'Storm-forged shields beneath a dark sky'),
   ('FANTASY', 'PLACE', 'L5', 'Storm-forged walls of mighty strength'),
   ('FANTASY', 'PLACE', 'L5', 'Storm-worn bridge of lost souls'),
   ('FANTASY', 'PLACE', 'L5', 'Storm-wracked keep on the cliffside'),
   ('FANTASY', 'PLACE', 'L5', 'Storm-wrought tower of ancient power'),
   ('FANTASY', 'PLACE', 'L5', 'Stormblown church of sorrow'),
   ('FANTASY', 'PLACE', 'L5', 'Storm’s rage tempered into steel'),
   ('FANTASY', 'PLACE', 'L5', 'Strikes of fury from skybound hands'),
   ('FANTASY', 'PLACE', 'L5', 'Stumbling inn of lost travelers'),
   ('FANTASY', 'PLACE', 'L5', 'Submerged ruins of eldritch power'),
   ('FANTASY', 'PLACE', 'L5', 'Submerged stones worn by time'),
   ('FANTASY', 'PLACE', 'L5', 'Summit gleaming with endless dawn'),
   ('FANTASY', 'PLACE', 'L5', 'Summoning abyssal horrors into being'),
   ('FANTASY', 'PLACE', 'L5', 'Summoning circle of vile power'),
   ('FANTASY', 'PLACE', 'L5', 'Summoning of twisted wraiths'),
   ('FANTASY', 'PLACE', 'L5', 'Sun-drenched barn of swift coursers'),
   ('FANTASY', 'PLACE', 'L5', 'Sun-washed home by the beach'),
   ('FANTASY', 'PLACE', 'L5', 'Sunken Trade Dock '),
   ('FANTASY', 'PLACE', 'L5', 'Sunken altar under an endless sky'),
   ('FANTASY', 'PLACE', 'L5', 'Sunken boathouse of forgotten voyages'),
   ('FANTASY', 'PLACE', 'L5', 'Sunken city with broken spires'),
   ('FANTASY', 'PLACE', 'L5', 'Sunken ruins kissed by the abyss'),
   ('FANTASY', 'PLACE', 'L5', 'Sunken shrine beneath moonlit waters'),
   ('FANTASY', 'PLACE', 'L5', 'Sunlit shelter for gallant horses'),
   ('FANTASY', 'PLACE', 'L5', 'Sunset cottage on golden sands'),
   ('FANTASY', 'PLACE', 'L5', 'Sunset watchtower over endless waves'),
   ('FANTASY', 'PLACE', 'L5', 'Sunset-lit barn of rare mounts'),
   ('FANTASY', 'PLACE', 'L5', 'Surfer’s haven by the shores'),
   ('FANTASY', 'PLACE', 'L5', 'Surfer’s paradise by the shore'),
   ('FANTASY', 'PLACE', 'L5', 'Swamp gas flickers in night'),
   ('FANTASY', 'PLACE', 'L5', 'Swampland refuge for swamp-dwellers’ steeds'),
   ('FANTASY', 'PLACE', 'L5', 'Swarming Sewers '),
   ('FANTASY', 'PLACE', 'L5', 'Swarming flies fill the air'),
   ('FANTASY', 'PLACE', 'L5', 'Tales of ancient battles'),
   ('FANTASY', 'PLACE', 'L5', 'Tangled Smuggler’s Path '),
   ('FANTASY', 'PLACE', 'L5', 'Tangled greenhouse of wild plants'),
   ('FANTASY', 'PLACE', 'L5', 'Tangled refuge of untamed beasts'),
   ('FANTASY', 'PLACE', 'L5', 'Tapestry-hung hall of judgment'),
   ('FANTASY', 'PLACE', 'L5', 'Tattered mercenary camp of ancient coins'),
   ('FANTASY', 'PLACE', 'L5', 'Teeth marks on old wood'),
   ('FANTASY', 'PLACE', 'L5', 'Teeth-filled thrones line the corridor'),
   ('FANTASY', 'PLACE', 'L5', 'Tempest-chained blades of endless battle'),
   ('FANTASY', 'PLACE', 'L5', 'Tempest-tempered forge of war'),
   ('FANTASY', 'PLACE', 'L5', 'Temple submerged beneath endless tides'),
   ('FANTASY', 'PLACE', 'L5', 'The Everwinter hall of trials'),
   ('FANTASY', 'PLACE', 'L5', 'The cryptic den of shifting walls'),
   ('FANTASY', 'PLACE', 'L5', 'The cryptic twist of ancient power'),
   ('FANTASY', 'PLACE', 'L5', 'The cursed halls of endless confusion'),
   ('FANTASY', 'PLACE', 'L5', 'The drowned altar of forgotten rites'),
   ('FANTASY', 'PLACE', 'L5', 'The heart of stonework craftsmanship'),
   ('FANTASY', 'PLACE', 'L5', 'The hidden crypt in deep waters'),
   ('FANTASY', 'PLACE', 'L5', 'The keeper’s den of forgotten secrets'),
   ('FANTASY', 'PLACE', 'L5', 'The mage’s arcane journal'),
   ('FANTASY', 'PLACE', 'L5', 'The maze where time itself bends'),
   ('FANTASY', 'PLACE', 'L5', 'The people’s voice made stone'),
   ('FANTASY', 'PLACE', 'L5', 'The sacred archive of forbidden knowledge'),
   ('FANTASY', 'PLACE', 'L5', 'The sorcerer’s legendary lore'),
   ('FANTASY', 'PLACE', 'L5', 'The submerged heart of an empire'),
   ('FANTASY', 'PLACE', 'L5', 'The sunken crypts of eternal sleep'),
   ('FANTASY', 'PLACE', 'L5', 'The sunken maze beneath the ocean'),
   ('FANTASY', 'PLACE', 'L5', 'The vast winding catacombs of destiny'),
   ('FANTASY', 'PLACE', 'L5', 'The winding route to forbidden knowledge'),
   ('FANTASY', 'PLACE', 'L5', 'Theosophical collection of divine texts'),
   ('FANTASY', 'PLACE', 'L5', 'Thick mist hides hulking shapes'),
   ('FANTASY', 'PLACE', 'L5', 'Thunder-charged siege weapons on standby'),
   ('FANTASY', 'PLACE', 'L5', 'Thunder-forged vault of glory'),
   ('FANTASY', 'PLACE', 'L5', 'Thunder-struck weapons of eternal might'),
   ('FANTASY', 'PLACE', 'L5', 'Thunderous forge where heroes are made'),
   ('FANTASY', 'PLACE', 'L5', 'Tidal retreat with breezy garden'),
   ('FANTASY', 'PLACE', 'L5', 'Tidal silence holds ancient power'),
   ('FANTASY', 'PLACE', 'L5', 'Tidal stone sanctuary by cliffs'),
   ('FANTASY', 'PLACE', 'L5', 'Tiled floor walked by generations'),
   ('FANTASY', 'PLACE', 'L5', 'Timeless bridges built to endure'),
   ('FANTASY', 'PLACE', 'L5', 'Timeless stones shaped with care'),
   ('FANTASY', 'PLACE', 'L5', 'Tomb-bound hunger never sleeps still'),
   ('FANTASY', 'PLACE', 'L5', 'Tombstone-laden chamber of forbidden rites'),
   ('FANTASY', 'PLACE', 'L5', 'Tome of eternal memories'),
   ('FANTASY', 'PLACE', 'L5', 'Tomes of the eternal warriors'),
   ('FANTASY', 'PLACE', 'L5', 'Torn Cart Graveyard '),
   ('FANTASY', 'PLACE', 'L5', 'Tower rising beyond mortal reach'),
   ('FANTASY', 'PLACE', 'L5', 'Towered citadel with hidden treasure'),
   ('FANTASY', 'PLACE', 'L5', 'Towered stronghold above the valley'),
   ('FANTASY', 'PLACE', 'L5', 'Trails of forgotten souls lost forever'),
   ('FANTASY', 'PLACE', 'L5', 'Tranquil dwelling by moonlit shores'),
   ('FANTASY', 'PLACE', 'L5', 'Troll-hammer carved into archstone'),
   ('FANTASY', 'PLACE', 'L5', 'Troll-hold hidden among dark rocks'),
   ('FANTASY', 'PLACE', 'L5', 'Tumbledown cottage by the swamp'),
   ('FANTASY', 'PLACE', 'L5', 'Tunnel of lost memories and echoes'),
   ('FANTASY', 'PLACE', 'L5', 'Turf-lined shelter for armored chargers'),
   ('FANTASY', 'PLACE', 'L5', 'Twilight-fortress amid snow-capped peaks'),
   ('FANTASY', 'PLACE', 'L5', 'Twilight-lit crypt of eternal sleep'),
   ('FANTASY', 'PLACE', 'L5', 'Twilight-lit path of glory'),
   ('FANTASY', 'PLACE', 'L5', 'Twisted Miners’ Tunnel '),
   ('FANTASY', 'PLACE', 'L5', 'Twisted experiments of dark science'),
   ('FANTASY', 'PLACE', 'L5', 'Twisted tree hollow of foul magic'),
   ('FANTASY', 'PLACE', 'L5', 'Twisting corridors of labyrinthine magic'),
   ('FANTASY', 'PLACE', 'L5', 'Twisting labyrinth of doom'),
   ('FANTASY', 'PLACE', 'L5', 'Underground Escape Route '),
   ('FANTASY', 'PLACE', 'L5', 'Underworld gates of endless hunger'),
   ('FANTASY', 'PLACE', 'L5', 'Underworld maze filled with wraiths'),
   ('FANTASY', 'PLACE', 'L5', 'Undying whispers from ancient crypts'),
   ('FANTASY', 'PLACE', 'L5', 'Unholy monastery of hidden rites'),
   ('FANTASY', 'PLACE', 'L5', 'Unkempt stable of mutant creatures'),
   ('FANTASY', 'PLACE', 'L5', 'Valiant blades where thunder strikes'),
   ('FANTASY', 'PLACE', 'L5', 'Vast gateway leading to the unknown'),
   ('FANTASY', 'PLACE', 'L5', 'Vast tunnels beneath cursed lands'),
   ('FANTASY', 'PLACE', 'L5', 'Vault of celestial battle arms'),
   ('FANTASY', 'PLACE', 'L5', 'Vault of celestial knowledge'),
   ('FANTASY', 'PLACE', 'L5', 'Vault of forgotten deities'),
   ('FANTASY', 'PLACE', 'L5', 'Vault of the ancients’ last will'),
   ('FANTASY', 'PLACE', 'L5', 'Vault of the public trust'),
   ('FANTASY', 'PLACE', 'L5', 'Vault of thunderous warsteel'),
   ('FANTASY', 'PLACE', 'L5', 'Vaulted halls of celestial armaments'),
   ('FANTASY', 'PLACE', 'L5', 'Vaults guarded by forgotten creatures'),
   ('FANTASY', 'PLACE', 'L5', 'Vaults of arcane mysteries'),
   ('FANTASY', 'PLACE', 'L5', 'Veiled monastery of the lost'),
   ('FANTASY', 'PLACE', 'L5', 'Veiled pit of desolate fate'),
   ('FANTASY', 'PLACE', 'L5', 'Veins of corrupted magic in air'),
   ('FANTASY', 'PLACE', 'L5', 'Veins of night’s poison running deep'),
   ('FANTASY', 'PLACE', 'L5', 'Veins pulse along carved walls'),
   ('FANTASY', 'PLACE', 'L5', 'Verdant fields where wild steeds run'),
   ('FANTASY', 'PLACE', 'L5', 'Vials filled with essence of decay'),
   ('FANTASY', 'PLACE', 'L5', 'Vigil kept through storm and stars'),
   ('FANTASY', 'PLACE', 'L5', 'Vile tomes and skeletal hands'),
   ('FANTASY', 'PLACE', 'L5', 'Wailing spirits in shadowed corners'),
   ('FANTASY', 'PLACE', 'L5', 'Walls carved by moonlit hands'),
   ('FANTASY', 'PLACE', 'L5', 'Wandering merchant’s caravan encampment'),
   ('FANTASY', 'PLACE', 'L5', 'War-ready forge of electric fury'),
   ('FANTASY', 'PLACE', 'L5', 'Warpaint smeared on hanging skulls'),
   ('FANTASY', 'PLACE', 'L5', 'Warren of giant beasts and warhorses'),
   ('FANTASY', 'PLACE', 'L5', 'Watchtower made of broken wagons'),
   ('FANTASY', 'PLACE', 'L5', 'Water-filled sanctum of long-lost deities'),
   ('FANTASY', 'PLACE', 'L5', 'Waterlogged relics of a lost faith'),
   ('FANTASY', 'PLACE', 'L5', 'Waterside cottage nestled in dunes'),
   ('FANTASY', 'PLACE', 'L5', 'Water’s edge home with wind chimes'),
   ('FANTASY', 'PLACE', 'L5', 'Wave-touched haven for travelers'),
   ('FANTASY', 'PLACE', 'L5', 'Weapons wrought in storm’s cradle'),
   ('FANTASY', 'PLACE', 'L5', 'Weathered barn at the crossroads'),
   ('FANTASY', 'PLACE', 'L5', 'Weathered barn beneath the mountain'),
   ('FANTASY', 'PLACE', 'L5', 'Weathered halls built to last'),
   ('FANTASY', 'PLACE', 'L5', 'Weathered spires etched in stone'),
   ('FANTASY', 'PLACE', 'L5', 'Web of ancient traps and illusions'),
   ('FANTASY', 'PLACE', 'L5', 'Where commoners and nobles meet'),
   ('FANTASY', 'PLACE', 'L5', 'Whisper-hall where taxes are born'),
   ('FANTASY', 'PLACE', 'L5', 'Whispered prophecy in battle winds'),
   ('FANTASY', 'PLACE', 'L5', 'Whispered riddles in thick fog'),
   ('FANTASY', 'PLACE', 'L5', 'Whispered screams from broken vaults'),
   ('FANTASY', 'PLACE', 'L5', 'Whispering Guildhall '),
   ('FANTASY', 'PLACE', 'L5', 'Whispering halls of ancient lore'),
   ('FANTASY', 'PLACE', 'L5', 'Whispering ruins of the damned'),
   ('FANTASY', 'PLACE', 'L5', 'Wind moans through shattered beams'),
   ('FANTASY', 'PLACE', 'L5', 'Wind-carved gateway to the frozen wastes'),
   ('FANTASY', 'PLACE', 'L5', 'Wind-drenched guard post at the pass'),
   ('FANTASY', 'PLACE', 'L5', 'Wind-swept bastion of endless skies'),
   ('FANTASY', 'PLACE', 'L5', 'Wind-swept refuge for galloping creatures'),
   ('FANTASY', 'PLACE', 'L5', 'Winding passage through towering peaks'),
   ('FANTASY', 'PLACE', 'L5', 'Windswept cabin by the pier'),
   ('FANTASY', 'PLACE', 'L5', 'Windswept haven on storm-touched plains'),
   ('FANTASY', 'PLACE', 'L5', 'Windswept perch of eternal vigilance'),
   ('FANTASY', 'PLACE', 'L5', 'Windswept shack on the point'),
   ('FANTASY', 'PLACE', 'L5', 'Windswept tower by the shoreline'),
   ('FANTASY', 'PLACE', 'L5', 'Wings aloft on eastern wind'),
   ('FANTASY', 'PLACE', 'L5', 'Wise elder’s circle of voices'),
   ('FANTASY', 'PLACE', 'L5', 'Withered garden of bloodfruit'),
   ('FANTASY', 'PLACE', 'L5', 'Wooden effigy burned at center'),
   ('FANTASY', 'PLACE', 'L5', 'Wooden shelter for forest wolves'),
   ('FANTASY', 'PLACE', 'L5', 'Worn Mapmaker’s Office '),
   ('FANTASY', 'PLACE', 'L5', 'Worn Stone Alchemist’s Workshop '),
   ('FANTASY', 'PLACE', 'L5', 'Worn shack of eerie whispers'),
   ('FANTASY', 'PLACE', 'L5', 'Wretched cave of dark whispers'),
   ('FANTASY', 'PLACE', 'L5', 'Wretched hymns bind the marrow'),
   ('FANTASY', 'PLACE', 'L5', 'Wrought with the fury of lightning'),
   ('FANTASY', 'PLACE', 'L5', 'Happy fields where Alexandra´s flowers grow ');

commit;