use hierarchy_generator;

INSERT INTO `NameTitles` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('FANTASY', 'PLACE', 'L5', 'Aerial Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Aerial Nesting Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Aerie Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Aerie Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Aerie of the Winds'),
   ('FANTASY', 'PLACE', 'L5', 'Aeris Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Aetherblade Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Alchemist’s Laboratory'),
   ('FANTASY', 'PLACE', 'L5', 'Alchemist’s Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Alchemy Laboratory'),
   ('FANTASY', 'PLACE', 'L5', 'Ancestors Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Ancestral Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient Foundry'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient Oak Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient Tree Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Ancient Wyrm’s Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Ancients'),
   ('FANTASY', 'PLACE', 'L5', 'Anemone Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Animal Pen'),
   ('FANTASY', 'PLACE', 'L5', 'Anvil Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Apothecary’s Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Apothecary’s Store'),
   ('FANTASY', 'PLACE', 'L5', 'Aquatic Enclave'),
   ('FANTASY', 'PLACE', 'L5', 'Arcane Conservatory'),
   ('FANTASY', 'PLACE', 'L5', 'Arcane Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Arcane Laboratories'),
   ('FANTASY', 'PLACE', 'L5', 'Arcane Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Arcane Research Facility'),
   ('FANTASY', 'PLACE', 'L5', 'Arcane Sanctum'),
   ('FANTASY', 'PLACE', 'L5', 'Archery Range'),
   ('FANTASY', 'PLACE', 'L5', 'Arena'),
   ('FANTASY', 'PLACE', 'L5', 'Arena of Strength'),
   ('FANTASY', 'PLACE', 'L5', 'Ascendant Pinnacle'),
   ('FANTASY', 'PLACE', 'L5', 'Astral Conduit'),
   ('FANTASY', 'PLACE', 'L5', 'Astral Gatehouse'),
   ('FANTASY', 'PLACE', 'L5', 'Astral Observatory'),
   ('FANTASY', 'PLACE', 'L5', 'Astral Pathway'),
   ('FANTASY', 'PLACE', 'L5', 'Aurora Gate'),
   ('FANTASY', 'PLACE', 'L5', 'Baker’s Oven'),
   ('FANTASY', 'PLACE', 'L5', 'Banner of Dawn Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Bard’s Amphitheater'),
   ('FANTASY', 'PLACE', 'L5', 'Barnacle-Encrusted Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Bat-Flight Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Bathhouse'),
   ('FANTASY', 'PLACE', 'L5', 'Battered Jail'),
   ('FANTASY', 'PLACE', 'L5', 'Battle-Born Longhouse'),
   ('FANTASY', 'PLACE', 'L5', 'Battle-Hardened Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Battle-Horn Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Beast-Binder’s Pen'),
   ('FANTASY', 'PLACE', 'L5', 'Beggars’ Alley'),
   ('FANTASY', 'PLACE', 'L5', 'Berserker’s Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Bifrost Waystation'),
   ('FANTASY', 'PLACE', 'L5', 'Birdsong Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Bisonhide Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Black Throne Room'),
   ('FANTASY', 'PLACE', 'L5', 'Blackened Mausoleum'),
   ('FANTASY', 'PLACE', 'L5', 'Blacksmith Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Blacksmith’s Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Blighted Crypt'),
   ('FANTASY', 'PLACE', 'L5', 'Blood Altar'),
   ('FANTASY', 'PLACE', 'L5', 'Blood Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Blood Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Blood Fountain'),
   ('FANTASY', 'PLACE', 'L5', 'Blood Moon Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Blood Pit'),
   ('FANTASY', 'PLACE', 'L5', 'Blood Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-Bound Manor'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-Cursed Estate'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-Cursed Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-Feast Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-Red Manor'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-Soaked Crypt'),
   ('FANTASY', 'PLACE', 'L5', 'Blood-Stained Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Bloodhorn Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Bloodied Arena'),
   ('FANTASY', 'PLACE', 'L5', 'Bloodpit Arena'),
   ('FANTASY', 'PLACE', 'L5', 'Bloodstained Battlefield'),
   ('FANTASY', 'PLACE', 'L5', 'Bloodstone Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Bloomstone Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Blossomveil Shelter'),
   ('FANTASY', 'PLACE', 'L5', 'Boar-Hunter’s Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Bone Altar'),
   ('FANTASY', 'PLACE', 'L5', 'Bone Pile Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Bone Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Bone-Cursed Mausoleum'),
   ('FANTASY', 'PLACE', 'L5', 'Bone-Fortified Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Bone-Hoarding Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Bone-Marked Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Bone-Pile Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Bone-Piled Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Bone-Piled Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Bone-Shielded Barricade'),
   ('FANTASY', 'PLACE', 'L5', 'Bonework Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Bottled Chaos House'),
   ('FANTASY', 'PLACE', 'L5', 'Boulder-Piled Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Bowyer’s Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Bowyer’s Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Brewery'),
   ('FANTASY', 'PLACE', 'L5', 'Brewpub'),
   ('FANTASY', 'PLACE', 'L5', 'Brewstone Cellar'),
   ('FANTASY', 'PLACE', 'L5', 'Brimstone Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Bubble-Bloom Garden'),
   ('FANTASY', 'PLACE', 'L5', 'Bull’s Blood Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Bull’s Eye Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Burrowed Cavern'),
   ('FANTASY', 'PLACE', 'L5', 'Butterfly Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Candle Maker’s Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Candlemaker’s Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Cannibal’s Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Carpenter’s Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Castle Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Cathedral'),
   ('FANTASY', 'PLACE', 'L5', 'Cave Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Cavefront Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Cavern of Decay'),
   ('FANTASY', 'PLACE', 'L5', 'Cavernous Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Cavernous Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Celestial Altar'),
   ('FANTASY', 'PLACE', 'L5', 'Celestial Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Celestial Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Celestial Warhall'),
   ('FANTASY', 'PLACE', 'L5', 'Celestia’s Beacon'),
   ('FANTASY', 'PLACE', 'L5', 'Cemetery'),
   ('FANTASY', 'PLACE', 'L5', 'Chasm Dwelling'),
   ('FANTASY', 'PLACE', 'L5', 'Chieftain’s Tent'),
   ('FANTASY', 'PLACE', 'L5', 'Choir of Valor'),
   ('FANTASY', 'PLACE', 'L5', 'Chronomancer’s Observatory'),
   ('FANTASY', 'PLACE', 'L5', 'Clash-Haven'),
   ('FANTASY', 'PLACE', 'L5', 'Clawmarked Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Clay-Ridge Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Cliffside Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Cliffside Throne'),
   ('FANTASY', 'PLACE', 'L5', 'Clifftop Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Cloud Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Cloudreach Arsenal'),
   ('FANTASY', 'PLACE', 'L5', 'Cloudreach Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Cloudscorn Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Cloudstone Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Cloverhill Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Cluttered Bazaar'),
   ('FANTASY', 'PLACE', 'L5', 'Cobble Stone Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Cobblepath Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Coffin Chambers'),
   ('FANTASY', 'PLACE', 'L5', 'Collapsed Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Coral Palace'),
   ('FANTASY', 'PLACE', 'L5', 'Coral Reef Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Coral Reef Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Corpse-Laden Bunker'),
   ('FANTASY', 'PLACE', 'L5', 'Corruption Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Council Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Courthouse'),
   ('FANTASY', 'PLACE', 'L5', 'Courtroom'),
   ('FANTASY', 'PLACE', 'L5', 'Coven’s Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Cradle of the Leaves'),
   ('FANTASY', 'PLACE', 'L5', 'Crashing Wave Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Creaking Carriage House'),
   ('FANTASY', 'PLACE', 'L5', 'Crown of Winds'),
   ('FANTASY', 'PLACE', 'L5', 'Crumbling Bridge'),
   ('FANTASY', 'PLACE', 'L5', 'Crypt of the Forgotten'),
   ('FANTASY', 'PLACE', 'L5', 'Cryptkeeper’s Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal Cavern'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal Dewdrop Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal Grotto'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal Observatory'),
   ('FANTASY', 'PLACE', 'L5', 'Crystal Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Crystalbloom Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Cursed Burial Ground'),
   ('FANTASY', 'PLACE', 'L5', 'Cursed Castle'),
   ('FANTASY', 'PLACE', 'L5', 'Cursed Coffin Shelter'),
   ('FANTASY', 'PLACE', 'L5', 'Dandelion Enclave'),
   ('FANTASY', 'PLACE', 'L5', 'Dark Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Dark Crystal Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Dark Forest Watch'),
   ('FANTASY', 'PLACE', 'L5', 'Dark Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Dark Horn Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Darkened Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Darkstone Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Darkwing Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Dawn Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Deadroot House'),
   ('FANTASY', 'PLACE', 'L5', 'Deathshroud Tomb'),
   ('FANTASY', 'PLACE', 'L5', 'Deep Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Deep Mines'),
   ('FANTASY', 'PLACE', 'L5', 'Deepwater Alcove'),
   ('FANTASY', 'PLACE', 'L5', 'Desecrated Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Desolate Burial Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Dewdrop Fountain'),
   ('FANTASY', 'PLACE', 'L5', 'Dewdrop Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Dewlit Treehouse'),
   ('FANTASY', 'PLACE', 'L5', 'Dewveil Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Digging Pit Shelter'),
   ('FANTASY', 'PLACE', 'L5', 'Divination Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Divine Flight Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Dolphin Watch Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Doomed Tombstone Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Doomstone Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Draconic Sanctum'),
   ('FANTASY', 'PLACE', 'L5', 'Dragonflame Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Dragonflight Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Dragonflight Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Dragonshard Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Dragonstone Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Dragon’s Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Dragon’s Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Drakewatch Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Drake’s Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Dread Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Dreambloom Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Dreamweaver’s Cottage'),
   ('FANTASY', 'PLACE', 'L5', 'Driftwood Bridge'),
   ('FANTASY', 'PLACE', 'L5', 'Driftwood Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Druidic Mage Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Drum Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Dwarven Armory'),
   ('FANTASY', 'PLACE', 'L5', 'Dwarven Brewery'),
   ('FANTASY', 'PLACE', 'L5', 'Dwarven Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Dwarven Hold'),
   ('FANTASY', 'PLACE', 'L5', 'Dwarven Library'),
   ('FANTASY', 'PLACE', 'L5', 'Eaglecrest Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Eaglefeather Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Eagleflight Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Eaglewing Watch'),
   ('FANTASY', 'PLACE', 'L5', 'Ebbing Reef Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Echo of Shields'),
   ('FANTASY', 'PLACE', 'L5', 'Echoing Helm Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Elder Tree Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Elder´s Dragonhold'),
   ('FANTASY', 'PLACE', 'L5', 'Elderbark Hearth'),
   ('FANTASY', 'PLACE', 'L5', 'Elder’s Council Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Elder’s Longhouse'),
   ('FANTASY', 'PLACE', 'L5', 'Elder’s Moot'),
   ('FANTASY', 'PLACE', 'L5', 'Elder’s Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Eldritch Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Elemental Conflux'),
   ('FANTASY', 'PLACE', 'L5', 'Elemental Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Elven Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Elven Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Elven Monastery'),
   ('FANTASY', 'PLACE', 'L5', 'Elven Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Elven Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Ember Throne Room'),
   ('FANTASY', 'PLACE', 'L5', 'Ember Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Emeraldleaf Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanted Flowerbed'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanted Garden'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanted Grove'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanted Treehouse'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanted Vine Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanter’s Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Enchanter’s Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Essence Vial Room'),
   ('FANTASY', 'PLACE', 'L5', 'Eternal Crypt'),
   ('FANTASY', 'PLACE', 'L5', 'Eternal Flame Cave '),
   ('FANTASY', 'PLACE', 'L5', 'Eternal Hunger Den'),
   ('FANTASY', 'PLACE', 'L5', 'Eternal Night Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Evershade Council Ring'),
   ('FANTASY', 'PLACE', 'L5', 'Fae Blossom Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Faerie Ring'),
   ('FANTASY', 'PLACE', 'L5', 'Faerie Ring Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Fairy Queen’s Court'),
   ('FANTASY', 'PLACE', 'L5', 'Falcon’s Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Fallen Hero’s Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Familiar’s Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Fang-Drained Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Fanged Manor'),
   ('FANTASY', 'PLACE', 'L5', 'Fanglord’s Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Farming Barn'),
   ('FANTASY', 'PLACE', 'L5', 'Farming Homestead'),
   ('FANTASY', 'PLACE', 'L5', 'Farmstead'),
   ('FANTASY', 'PLACE', 'L5', 'Feasting Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Feathercrest Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Feathered Crag'),
   ('FANTASY', 'PLACE', 'L5', 'Feathered Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Feathered Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Feathered Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Featherlight Command Post'),
   ('FANTASY', 'PLACE', 'L5', 'Featherlore Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Feathersong Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Featherstone Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Featherstone Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Featherwhisper Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Feral Den'),
   ('FANTASY', 'PLACE', 'L5', 'Feral Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Fernshade Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Fey Court Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Feyleaf Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Feywild Alcove'),
   ('FANTASY', 'PLACE', 'L5', 'Feywild Gardens'),
   ('FANTASY', 'PLACE', 'L5', 'Fighting Pits'),
   ('FANTASY', 'PLACE', 'L5', 'Filthy Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Firefly Lantern Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Firelance Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Firelord’s Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Firestone Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Flame-Spire Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Flameheart Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Flesh-Crushing Pit'),
   ('FANTASY', 'PLACE', 'L5', 'Flesh-Eaters’ Den'),
   ('FANTASY', 'PLACE', 'L5', 'Flesh-Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Flesh-Heap Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Flesh-Made Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Flesh-Ridden Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Fleshbound Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Fletcher’s Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Fletcher’s Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Flightbound Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Flintstone Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Flower Petal Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Forest Pathway'),
   ('FANTASY', 'PLACE', 'L5', 'Forest Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Forge of the Minotaur'),
   ('FANTASY', 'PLACE', 'L5', 'Fortress Gatehouse'),
   ('FANTASY', 'PLACE', 'L5', 'Frostbinder’s Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Frostblossom Conservatory'),
   ('FANTASY', 'PLACE', 'L5', 'Frostfire Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Frosthammer Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Frostleaf Grotto'),
   ('FANTASY', 'PLACE', 'L5', 'Fungi-Filled Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Fungus Cavern'),
   ('FANTASY', 'PLACE', 'L5', 'Furrier’s Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Galloping Arena'),
   ('FANTASY', 'PLACE', 'L5', 'Gemcutter’s Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Gemstone Observatory'),
   ('FANTASY', 'PLACE', 'L5', 'Ghastly Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Ghoul’s Feeding Ground'),
   ('FANTASY', 'PLACE', 'L5', 'Ghoul’s Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Giant Graveyard'),
   ('FANTASY', 'PLACE', 'L5', 'Gilded Valor Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Glade of Gentle Branches'),
   ('FANTASY', 'PLACE', 'L5', 'Glimmerbrook Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Glimmering Blossom Cottage'),
   ('FANTASY', 'PLACE', 'L5', 'Glimmering Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Glimmering Pool'),
   ('FANTASY', 'PLACE', 'L5', 'Glimmering Root Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Glimmering Tide Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Glittering Fae Court'),
   ('FANTASY', 'PLACE', 'L5', 'Glittering Halls'),
   ('FANTASY', 'PLACE', 'L5', 'Gloomspire'),
   ('FANTASY', 'PLACE', 'L5', 'Gloomstone Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Glory’s Summit'),
   ('FANTASY', 'PLACE', 'L5', 'Glowing Clamshell Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Gnarled Hovel'),
   ('FANTASY', 'PLACE', 'L5', 'Goblin Wreckyard'),
   ('FANTASY', 'PLACE', 'L5', 'Goblin-Made Mill'),
   ('FANTASY', 'PLACE', 'L5', 'Goblin-Touched Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Goblins’ Grotto'),
   ('FANTASY', 'PLACE', 'L5', 'Goblin’s Grotto'),
   ('FANTASY', 'PLACE', 'L5', 'Golden Hoard Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Golden Ivy Grove'),
   ('FANTASY', 'PLACE', 'L5', 'Golden Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Golden Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Goldenwing Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Gossamer Throne Room'),
   ('FANTASY', 'PLACE', 'L5', 'Grand Plaza'),
   ('FANTASY', 'PLACE', 'L5', 'Granite Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Granite Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Grave Mound'),
   ('FANTASY', 'PLACE', 'L5', 'Grave-Pit Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Gravel Pit Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Graveyard'),
   ('FANTASY', 'PLACE', 'L5', 'Graveyard Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Graveyard Mausoleum'),
   ('FANTASY', 'PLACE', 'L5', 'Graveyard Outpost'),
   ('FANTASY', 'PLACE', 'L5', 'Great Mining Complex'),
   ('FANTASY', 'PLACE', 'L5', 'Great Smithy'),
   ('FANTASY', 'PLACE', 'L5', 'Great Wyrm Cavern '),
   ('FANTASY', 'PLACE', 'L5', 'Griffinwing Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Griffin’s Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Griffin’s Wing Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Griffon Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Griffon’s Eye Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Grim-Halls Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Grimey Hideout'),
   ('FANTASY', 'PLACE', 'L5', 'Grimrock Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Guard Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Guildhall'),
   ('FANTASY', 'PLACE', 'L5', 'Gunkhole Cavern'),
   ('FANTASY', 'PLACE', 'L5', 'Hall '),
   ('FANTASY', 'PLACE', 'L5', 'Hall of the Chosen'),
   ('FANTASY', 'PLACE', 'L5', 'Hallowed Glade'),
   ('FANTASY', 'PLACE', 'L5', 'Halls of Sacred Battle'),
   ('FANTASY', 'PLACE', 'L5', 'Hammerfall Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Hammerstone Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Harpysong Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Haunting Obelisk'),
   ('FANTASY', 'PLACE', 'L5', 'Hazelbough Den'),
   ('FANTASY', 'PLACE', 'L5', 'Heartgrove Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Heavenpiercer Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Herb Shack'),
   ('FANTASY', 'PLACE', 'L5', 'Herbalist’s Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Herbalist’s Tent'),
   ('FANTASY', 'PLACE', 'L5', 'Herding Barn'),
   ('FANTASY', 'PLACE', 'L5', 'Herdmaster’s Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Hidden Mine Shelter'),
   ('FANTASY', 'PLACE', 'L5', 'Highbranch Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Highcliff Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Highflying Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Hightalon Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Highwind Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Hoard Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Hollow Tree Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Hollowed Flesh Pit'),
   ('FANTASY', 'PLACE', 'L5', 'Hollowed Out Burrow'),
   ('FANTASY', 'PLACE', 'L5', 'Hollowed Skull Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Hoofbeat Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Hoofprint Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Hoofstone Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Horned Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Horned Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Horned Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Horned Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Horns of War'),
   ('FANTASY', 'PLACE', 'L5', 'Horse Breeder’s Stables'),
   ('FANTASY', 'PLACE', 'L5', 'Howling Crypt'),
   ('FANTASY', 'PLACE', 'L5', 'Hunter’s Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Hunter’s Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Hunter’s Stash'),
   ('FANTASY', 'PLACE', 'L5', 'Hunting Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Huntmaster’s Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Illusionist’s Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Infernal Throne'),
   ('FANTASY', 'PLACE', 'L5', 'Inferno Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Inn'),
   ('FANTASY', 'PLACE', 'L5', 'Iron Horn Gate'),
   ('FANTASY', 'PLACE', 'L5', 'Ironclad Arena'),
   ('FANTASY', 'PLACE', 'L5', 'Ironclad Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Ironclad Stronghold'),
   ('FANTASY', 'PLACE', 'L5', 'Ironclaw Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Ironhoof Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Ironshard Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Ironwing Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Ironwood Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Jadepetal Gathering Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Jeweler’s Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Junkpile Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Junkyard Palace'),
   ('FANTASY', 'PLACE', 'L5', 'Knowledge Fountain'),
   ('FANTASY', 'PLACE', 'L5', 'Labyrinthine Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Lanceguard Watchpost'),
   ('FANTASY', 'PLACE', 'L5', 'Lava Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Leafwoven Cottage'),
   ('FANTASY', 'PLACE', 'L5', 'Library'),
   ('FANTASY', 'PLACE', 'L5', 'Lily Petal Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Lilyshade Dome'),
   ('FANTASY', 'PLACE', 'L5', 'Longstride Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Lore Library'),
   ('FANTASY', 'PLACE', 'L5', 'Luminous Lagoon Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Lunar Moss Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Lunar Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Lurking Tomb'),
   ('FANTASY', 'PLACE', 'L5', 'Mages’ Guild'),
   ('FANTASY', 'PLACE', 'L5', 'Mages’ Guildhall'),
   ('FANTASY', 'PLACE', 'L5', 'Mage’s Guildhall'),
   ('FANTASY', 'PLACE', 'L5', 'Maggot-Crafted Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Magic Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Magic Item Emporium'),
   ('FANTASY', 'PLACE', 'L5', 'Magical Fountain'),
   ('FANTASY', 'PLACE', 'L5', 'Magical Wing Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Mane Gathering Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Market Square'),
   ('FANTASY', 'PLACE', 'L5', 'Mausoleum of the Damned'),
   ('FANTASY', 'PLACE', 'L5', 'Maze Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Maze Prison'),
   ('FANTASY', 'PLACE', 'L5', 'Maze of the Minotaur'),
   ('FANTASY', 'PLACE', 'L5', 'Medicine Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Merchant’s Stall'),
   ('FANTASY', 'PLACE', 'L5', 'Merman’s Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Midnight Courtyard'),
   ('FANTASY', 'PLACE', 'L5', 'Miller’s Windmill'),
   ('FANTASY', 'PLACE', 'L5', 'Minotaur Pit'),
   ('FANTASY', 'PLACE', 'L5', 'Minotaur Tomb'),
   ('FANTASY', 'PLACE', 'L5', 'Minotaur’s Throne Room'),
   ('FANTASY', 'PLACE', 'L5', 'Mischief Den'),
   ('FANTASY', 'PLACE', 'L5', 'Mithril Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Mithril Works'),
   ('FANTASY', 'PLACE', 'L5', 'Mole-Hole Hideaway'),
   ('FANTASY', 'PLACE', 'L5', 'Monastery'),
   ('FANTASY', 'PLACE', 'L5', 'Moonbeam Conservatory'),
   ('FANTASY', 'PLACE', 'L5', 'Moonbeam Palace'),
   ('FANTASY', 'PLACE', 'L5', 'Moonfern Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Moonflower Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Arbor'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Cove'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Grazing Grounds'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Lagoon'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Mausoleum'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Necropolis'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Moonlit Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Moonstone Altar'),
   ('FANTASY', 'PLACE', 'L5', 'Moonstone Palace'),
   ('FANTASY', 'PLACE', 'L5', 'Moonvine Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Moonwell'),
   ('FANTASY', 'PLACE', 'L5', 'Moss-Cloaked Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Moss-Covered Crypt'),
   ('FANTASY', 'PLACE', 'L5', 'Moss-Crusted Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Mossbound Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Mosswoven Den'),
   ('FANTASY', 'PLACE', 'L5', 'Mossy Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Mountain Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Mountain Pass Gate'),
   ('FANTASY', 'PLACE', 'L5', 'Mountaincrest Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Mountainpeak Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Mud-Bound Shack'),
   ('FANTASY', 'PLACE', 'L5', 'Mud-Dug Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Mud-Dwelling'),
   ('FANTASY', 'PLACE', 'L5', 'Mudslide Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Mudslide Outpost'),
   ('FANTASY', 'PLACE', 'L5', 'Mudstone Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Mushroom Grove'),
   ('FANTASY', 'PLACE', 'L5', 'Mystic Dragon Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Mystic Fire Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Mystic Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Mystic Glade'),
   ('FANTASY', 'PLACE', 'L5', 'Mystic Scriptorium'),
   ('FANTASY', 'PLACE', 'L5', 'Naiad’s Well'),
   ('FANTASY', 'PLACE', 'L5', 'Nature’s Embrace Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Nautical Altar'),
   ('FANTASY', 'PLACE', 'L5', 'Necromancer’s Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Necrotic Lab'),
   ('FANTASY', 'PLACE', 'L5', 'Nest of the Gale'),
   ('FANTASY', 'PLACE', 'L5', 'Nest of the Storm'),
   ('FANTASY', 'PLACE', 'L5', 'Night Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Nightmare Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Nightwatch Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Night’s Embrace Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Nocturnal Mansion'),
   ('FANTASY', 'PLACE', 'L5', 'Nocturnal Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Nomad’s Camp'),
   ('FANTASY', 'PLACE', 'L5', 'Oakmother’s Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Oathfire Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Obsidian Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Obsidian Quarry'),
   ('FANTASY', 'PLACE', 'L5', 'Oceanic Chateau'),
   ('FANTASY', 'PLACE', 'L5', 'Oceanic Court'),
   ('FANTASY', 'PLACE', 'L5', 'Palace'),
   ('FANTASY', 'PLACE', 'L5', 'Patchwork Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Pearl Enclave'),
   ('FANTASY', 'PLACE', 'L5', 'Pearl Harbor'),
   ('FANTASY', 'PLACE', 'L5', 'Pearl Shell Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Perch of the Highwinds'),
   ('FANTASY', 'PLACE', 'L5', 'Petal-Draped Canopy'),
   ('FANTASY', 'PLACE', 'L5', 'Philosopher’s Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Pinnacle Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Pit of Honor'),
   ('FANTASY', 'PLACE', 'L5', 'Pixie Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Poisoned Pit Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Potion Brewing Lab'),
   ('FANTASY', 'PLACE', 'L5', 'Potion Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Potion Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Prison'),
   ('FANTASY', 'PLACE', 'L5', 'Putrescent Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Putrid Shop'),
   ('FANTASY', 'PLACE', 'L5', 'Putrid Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Quarry'),
   ('FANTASY', 'PLACE', 'L5', 'Ragged Den'),
   ('FANTASY', 'PLACE', 'L5', 'Raiders’ Den'),
   ('FANTASY', 'PLACE', 'L5', 'Raiders’ Fort'),
   ('FANTASY', 'PLACE', 'L5', 'Rainbow Meadow Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Rat-Run Tunnel'),
   ('FANTASY', 'PLACE', 'L5', 'Rat’s Nest Tavern'),
   ('FANTASY', 'PLACE', 'L5', 'Rat’s Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Ravager’s Tent'),
   ('FANTASY', 'PLACE', 'L5', 'Raven-Keeper’s Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Ravencrest Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Ravenwing Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Riders’ Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Rider’s Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Rider’s Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Riding Stables'),
   ('FANTASY', 'PLACE', 'L5', 'Ritual Cave'),
   ('FANTASY', 'PLACE', 'L5', 'Ritual Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Ritual Ground'),
   ('FANTASY', 'PLACE', 'L5', 'Roaring Heights Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Rockhide Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Rootspire Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Rot-Filled House'),
   ('FANTASY', 'PLACE', 'L5', 'Rotten Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Rotting Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Rotting Tomb'),
   ('FANTASY', 'PLACE', 'L5', 'Rubble Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Rune Carving Studio'),
   ('FANTASY', 'PLACE', 'L5', 'Rune-Bound Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Rune-Crafting Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Runehammer Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Runestone Altar'),
   ('FANTASY', 'PLACE', 'L5', 'Runic Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Rusty Cage Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Rusty Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred Fire Pit'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred Grove'),
   ('FANTASY', 'PLACE', 'L5', 'Sacred Grove Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Sacrificial Altar'),
   ('FANTASY', 'PLACE', 'L5', 'Sage’s Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Saltwater Reef House'),
   ('FANTASY', 'PLACE', 'L5', 'Sanctum of the Worthy'),
   ('FANTASY', 'PLACE', 'L5', 'Sandcastle Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Sanguine Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Sapstone Garden Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Savagery Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Scalebound Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Scavenger’s Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Scavenger’s Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Schoolhouse'),
   ('FANTASY', 'PLACE', 'L5', 'Scorched Hearth'),
   ('FANTASY', 'PLACE', 'L5', 'Scorched Ritual Ground'),
   ('FANTASY', 'PLACE', 'L5', 'Scorched Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Scrapheap Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Scrapstone Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Scrapwood Cabin'),
   ('FANTASY', 'PLACE', 'L5', 'Scribe’s Office'),
   ('FANTASY', 'PLACE', 'L5', 'Sea Breeze House'),
   ('FANTASY', 'PLACE', 'L5', 'Seafloor Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Seafoam Haven'),
   ('FANTASY', 'PLACE', 'L5', 'Searing Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Searing Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Seashell Cottage'),
   ('FANTASY', 'PLACE', 'L5', 'Seashell Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Seaweed Grove'),
   ('FANTASY', 'PLACE', 'L5', 'Secret Door Tavern'),
   ('FANTASY', 'PLACE', 'L5', 'Secret Passage Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Seer’s Dome'),
   ('FANTASY', 'PLACE', 'L5', 'Seer’s Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Seraphic Gatehouse'),
   ('FANTASY', 'PLACE', 'L5', 'Sewer Maze Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Sewer-Lair Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Shade-Ridden Estate'),
   ('FANTASY', 'PLACE', 'L5', 'Shadow Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Shadowed Courtyard'),
   ('FANTASY', 'PLACE', 'L5', 'Shadows Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Shaky Shack'),
   ('FANTASY', 'PLACE', 'L5', 'Shaman’s Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Shaman’s Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Sharkfin Observatory'),
   ('FANTASY', 'PLACE', 'L5', 'Shattered Clifftop'),
   ('FANTASY', 'PLACE', 'L5', 'Shattered Coffin Room'),
   ('FANTASY', 'PLACE', 'L5', 'Shattered Stone Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Shield-Crafted Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Shieldmaiden’s Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Shimmering Sea Garden'),
   ('FANTASY', 'PLACE', 'L5', 'Shoddy Warehouse'),
   ('FANTASY', 'PLACE', 'L5', 'Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Shrouded Tomb'),
   ('FANTASY', 'PLACE', 'L5', 'Silver Current Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Silverbark Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Silverfeather Watch'),
   ('FANTASY', 'PLACE', 'L5', 'Silverleaf Library'),
   ('FANTASY', 'PLACE', 'L5', 'Silvermist Cove'),
   ('FANTASY', 'PLACE', 'L5', 'Silvermist Garden'),
   ('FANTASY', 'PLACE', 'L5', 'Silverstone Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Silverwing Den'),
   ('FANTASY', 'PLACE', 'L5', 'Silverwood Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Singing Branch Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Siren’s Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Skeletal Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Skeletal Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Skittering Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Skull-Crowned Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Skull-Splintered Gatehouse'),
   ('FANTASY', 'PLACE', 'L5', 'Skullgate Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Sky-Palace of the Winds'),
   ('FANTASY', 'PLACE', 'L5', 'Skyborne Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Skyclaw Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Skyforge Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Skyfury Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Skyhunter Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Skyshard Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Skyward Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Skyward Observatory'),
   ('FANTASY', 'PLACE', 'L5', 'Skyward Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Skywarden’s Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Skywatch Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Skywatch Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Skyweaver Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Slime-Ridden Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Smelting Furnace Den'),
   ('FANTASY', 'PLACE', 'L5', 'Smithy'),
   ('FANTASY', 'PLACE', 'L5', 'Smoldering Fire Pit'),
   ('FANTASY', 'PLACE', 'L5', 'Soaring Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Soaring Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Softbark Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Songbird Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Songbird Sanctum'),
   ('FANTASY', 'PLACE', 'L5', 'Sorcerer’s Library'),
   ('FANTASY', 'PLACE', 'L5', 'Sorcery Academy'),
   ('FANTASY', 'PLACE', 'L5', 'Soulstone Altar'),
   ('FANTASY', 'PLACE', 'L5', 'Spearpeak Monastery'),
   ('FANTASY', 'PLACE', 'L5', 'Spearsworn Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Spearwind Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Spell Library'),
   ('FANTASY', 'PLACE', 'L5', 'Spellcasting Arena'),
   ('FANTASY', 'PLACE', 'L5', 'Spellcasting Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Spiked Cage'),
   ('FANTASY', 'PLACE', 'L5', 'Spiked Pit Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Spirit Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Spirit Totem Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Spirit-Touched Tent'),
   ('FANTASY', 'PLACE', 'L5', 'Spriggan’s Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Stable'),
   ('FANTASY', 'PLACE', 'L5', 'Stables'),
   ('FANTASY', 'PLACE', 'L5', 'Starfall Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Starfish Grove'),
   ('FANTASY', 'PLACE', 'L5', 'Starflower Archway'),
   ('FANTASY', 'PLACE', 'L5', 'Starleaf Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Starlight Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Starlight Enclave'),
   ('FANTASY', 'PLACE', 'L5', 'Starlight Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Starshine Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Stinkpit Dungeon'),
   ('FANTASY', 'PLACE', 'L5', 'Stone Bridge'),
   ('FANTASY', 'PLACE', 'L5', 'Stone Horn Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Stone Pillar Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-Hearted Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Stone-Tunnel Den'),
   ('FANTASY', 'PLACE', 'L5', 'Stonecrag Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Stonecutters Guild'),
   ('FANTASY', 'PLACE', 'L5', 'Stonefoot Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Stoneforge Guild'),
   ('FANTASY', 'PLACE', 'L5', 'Stonehearth Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Stonehelm Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Stonemason’s Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Stoneshield Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Storm-Cauldron Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Stormcall Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Stormcaller’s Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Stormcrest Palace'),
   ('FANTASY', 'PLACE', 'L5', 'Stormfeather Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Stormfeather Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Stormfury Aerie'),
   ('FANTASY', 'PLACE', 'L5', 'Stormrider’s Hold'),
   ('FANTASY', 'PLACE', 'L5', 'Stormrider’s Lookout'),
   ('FANTASY', 'PLACE', 'L5', 'Stormspire Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Stormwind Alcove'),
   ('FANTASY', 'PLACE', 'L5', 'Stormwing Hold'),
   ('FANTASY', 'PLACE', 'L5', 'Summoning Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Sunbeam Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Sunburst Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Suncatcher Aerie'),
   ('FANTASY', 'PLACE', 'L5', 'Sunfire Watch'),
   ('FANTASY', 'PLACE', 'L5', 'Sunken Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Sunlit Encampment'),
   ('FANTASY', 'PLACE', 'L5', 'Sunlit Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Sunlit Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Sunpetal Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Sunset Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Sunshine Grove'),
   ('FANTASY', 'PLACE', 'L5', 'Sunspire Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Sunwoven Dome'),
   ('FANTASY', 'PLACE', 'L5', 'Swamp Hovel'),
   ('FANTASY', 'PLACE', 'L5', 'Swamp Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Swanwing Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Sylvan Archway'),
   ('FANTASY', 'PLACE', 'L5', 'Sylvan Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Tailor’s House'),
   ('FANTASY', 'PLACE', 'L5', 'Talonstone Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Talons’ Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Tangleleaf Watch'),
   ('FANTASY', 'PLACE', 'L5', 'Tattered Tent'),
   ('FANTASY', 'PLACE', 'L5', 'Tavern'),
   ('FANTASY', 'PLACE', 'L5', 'Teleportation Nexus'),
   ('FANTASY', 'PLACE', 'L5', 'Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Tethered Stall'),
   ('FANTASY', 'PLACE', 'L5', 'The Blooming Archway'),
   ('FANTASY', 'PLACE', 'L5', 'The Bull’s Roar'),
   ('FANTASY', 'PLACE', 'L5', 'The Celestial Armory'),
   ('FANTASY', 'PLACE', 'L5', 'The Deepforge'),
   ('FANTASY', 'PLACE', 'L5', 'The Eclipsed Spire'),
   ('FANTASY', 'PLACE', 'L5', 'The Enleafed Spire'),
   ('FANTASY', 'PLACE', 'L5', 'The Eternal Roost'),
   ('FANTASY', 'PLACE', 'L5', 'The Great Labyrinth'),
   ('FANTASY', 'PLACE', 'L5', 'The Greenheart Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'The Griffin’s Talon'),
   ('FANTASY', 'PLACE', 'L5', 'The Ironroot Hall'),
   ('FANTASY', 'PLACE', 'L5', 'The Lichen Niche'),
   ('FANTASY', 'PLACE', 'L5', 'The Living Arch'),
   ('FANTASY', 'PLACE', 'L5', 'The Minotaur’s Den'),
   ('FANTASY', 'PLACE', 'L5', 'The Roosting Perch'),
   ('FANTASY', 'PLACE', 'L5', 'The Silver Roost'),
   ('FANTASY', 'PLACE', 'L5', 'The Stoneroom'),
   ('FANTASY', 'PLACE', 'L5', 'The Sylvan Hearth'),
   ('FANTASY', 'PLACE', 'L5', 'The Valkyrie Circle'),
   ('FANTASY', 'PLACE', 'L5', 'The Valkyrie’s Flame'),
   ('FANTASY', 'PLACE', 'L5', 'The Verdant Spiral'),
   ('FANTASY', 'PLACE', 'L5', 'The Wildroot Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'The Winged Crown'),
   ('FANTASY', 'PLACE', 'L5', 'The Wingguard Lodge'),
   ('FANTASY', 'PLACE', 'L5', 'Thistlebloom Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Thistlewood Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Thorn-Kissed Arbor'),
   ('FANTASY', 'PLACE', 'L5', 'Thorn-Snare Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Thunderclaw Observatory'),
   ('FANTASY', 'PLACE', 'L5', 'Thunderhoof Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Thunderpeak Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Thunderpeak Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Thunderwing Armory'),
   ('FANTASY', 'PLACE', 'L5', 'Tidal Archway'),
   ('FANTASY', 'PLACE', 'L5', 'Tidal Cavern Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Tidal Pool Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Tidecaller’s Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Time Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Tinker’s Workshop'),
   ('FANTASY', 'PLACE', 'L5', 'Torn Canvas Shelter'),
   ('FANTASY', 'PLACE', 'L5', 'Town Gatehouse'),
   ('FANTASY', 'PLACE', 'L5', 'Town Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Town Watchhouse'),
   ('FANTASY', 'PLACE', 'L5', 'Tracker’s Campfire'),
   ('FANTASY', 'PLACE', 'L5', 'Tracker’s Hideout'),
   ('FANTASY', 'PLACE', 'L5', 'Trading Post'),
   ('FANTASY', 'PLACE', 'L5', 'Tranquility Gardens'),
   ('FANTASY', 'PLACE', 'L5', 'Trap-Filled Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Trapdoor House'),
   ('FANTASY', 'PLACE', 'L5', 'Travelers´ Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Treasure Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Tree'),
   ('FANTASY', 'PLACE', 'L5', 'Treehouse Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Tribal Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Tribal Gathering Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Tribe Elder’s Tent'),
   ('FANTASY', 'PLACE', 'L5', 'Tribe’s Hearth'),
   ('FANTASY', 'PLACE', 'L5', 'Trickster’s Tunnel'),
   ('FANTASY', 'PLACE', 'L5', 'Troll Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Troll Forge'),
   ('FANTASY', 'PLACE', 'L5', 'Troll Market'),
   ('FANTASY', 'PLACE', 'L5', 'Troll Pit'),
   ('FANTASY', 'PLACE', 'L5', 'Troll-Bone Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Troll-Horn Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Troll-Keeper’s Outpost'),
   ('FANTASY', 'PLACE', 'L5', 'Trollbone Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Trollhold'),
   ('FANTASY', 'PLACE', 'L5', 'Trollwatch'),
   ('FANTASY', 'PLACE', 'L5', 'Troll’s Bridge'),
   ('FANTASY', 'PLACE', 'L5', 'Troll’s Den'),
   ('FANTASY', 'PLACE', 'L5', 'Troll’s Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Trophy Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Trophy Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Tumbleweed Outpost'),
   ('FANTASY', 'PLACE', 'L5', 'Tunnels'),
   ('FANTASY', 'PLACE', 'L5', 'Tunnels of the Buried King'),
   ('FANTASY', 'PLACE', 'L5', 'Tunnels of the Lost'),
   ('FANTASY', 'PLACE', 'L5', 'Turtleback Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Twilight Blossom Glade'),
   ('FANTASY', 'PLACE', 'L5', 'Twilight Lance Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Twilight Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Twitching Tunnel Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Twixtwind Garden'),
   ('FANTASY', 'PLACE', 'L5', 'Undead Alcove'),
   ('FANTASY', 'PLACE', 'L5', 'Undead Hall of Flesh'),
   ('FANTASY', 'PLACE', 'L5', 'Underdweller´s Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Cunning Underground Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Underground Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Undying Crypt'),
   ('FANTASY', 'PLACE', 'L5', 'Valiance Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Valkyrie’s Vigil'),
   ('FANTASY', 'PLACE', 'L5', 'Vampire Throne Room'),
   ('FANTASY', 'PLACE', 'L5', 'Vampire’s Castle'),
   ('FANTASY', 'PLACE', 'L5', 'Vampire’s Garden'),
   ('FANTASY', 'PLACE', 'L5', 'Vampire’s Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Vampire’s Lair'),
   ('FANTASY', 'PLACE', 'L5', 'Vampire’s Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Vampiric Estate'),
   ('FANTASY', 'PLACE', 'L5', 'Vampiric Parlor'),
   ('FANTASY', 'PLACE', 'L5', 'Vanguard Outpost'),
   ('FANTASY', 'PLACE', 'L5', 'Veilflower Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Veilroot Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Veilwood Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Vengeful Vault'),
   ('FANTASY', 'PLACE', 'L5', 'Vermin’s Burrow'),
   ('FANTASY', 'PLACE', 'L5', 'Victory Pole'),
   ('FANTASY', 'PLACE', 'L5', 'Vile Hatchery'),
   ('FANTASY', 'PLACE', 'L5', 'Vineyard'),
   ('FANTASY', 'PLACE', 'L5', 'Volcanic Chamber'),
   ('FANTASY', 'PLACE', 'L5', 'Volcanic Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Wandering Glade'),
   ('FANTASY', 'PLACE', 'L5', 'Wanderwood Dwelling'),
   ('FANTASY', 'PLACE', 'L5', 'War Banner Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'War Chief’s Hall'),
   ('FANTASY', 'PLACE', 'L5', 'War Steed Stables'),
   ('FANTASY', 'PLACE', 'L5', 'War Tent'),
   ('FANTASY', 'PLACE', 'L5', 'Warband’s Camp'),
   ('FANTASY', 'PLACE', 'L5', 'Warband’s Enclave'),
   ('FANTASY', 'PLACE', 'L5', 'Warchief’s Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Warchief’s Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Warding Circle'),
   ('FANTASY', 'PLACE', 'L5', 'Warg-Rider’s Outpost'),
   ('FANTASY', 'PLACE', 'L5', 'Warhorn Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Warlock’s Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Warlord’s Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Warlord’s Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Warlord’s Throne'),
   ('FANTASY', 'PLACE', 'L5', 'Warpath Shrine'),
   ('FANTASY', 'PLACE', 'L5', 'Warren Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Warren of Secrets'),
   ('FANTASY', 'PLACE', 'L5', 'Warrior’s Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Warrior’s Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Warrior’s Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Warrior’s Longhouse'),
   ('FANTASY', 'PLACE', 'L5', 'Warrior’s Mead Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Warrior’s Rest'),
   ('FANTASY', 'PLACE', 'L5', 'Warrior’s Stables'),
   ('FANTASY', 'PLACE', 'L5', 'Warrior’s Training Grounds'),
   ('FANTASY', 'PLACE', 'L5', 'Wartorn Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Wartusk’s Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Water-Whisperer’s Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Watermill'),
   ('FANTASY', 'PLACE', 'L5', 'Wave-Crested Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Whale-Bone Longhouse'),
   ('FANTASY', 'PLACE', 'L5', 'Whimsy Nook'),
   ('FANTASY', 'PLACE', 'L5', 'Whirlpool Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Whirlwind Shelter'),
   ('FANTASY', 'PLACE', 'L5', 'Whisperbreeze Alcove'),
   ('FANTASY', 'PLACE', 'L5', 'Whispering Crypts'),
   ('FANTASY', 'PLACE', 'L5', 'Whispering Glade'),
   ('FANTASY', 'PLACE', 'L5', 'Whispering Grove'),
   ('FANTASY', 'PLACE', 'L5', 'Whispering Grove Pavilion'),
   ('FANTASY', 'PLACE', 'L5', 'Whisperwillow Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Whisperwind Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Wicked Chapel'),
   ('FANTASY', 'PLACE', 'L5', 'Wilder’s Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Wildstalker’s Watchtower'),
   ('FANTASY', 'PLACE', 'L5', 'Willowroot Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Willowwood Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Wind-Eagle’s Nest'),
   ('FANTASY', 'PLACE', 'L5', 'Wind-Swept Perch'),
   ('FANTASY', 'PLACE', 'L5', 'Wind-Touched Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Windborne Sanctum'),
   ('FANTASY', 'PLACE', 'L5', 'Windcallers’ Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Windcallers’ Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Windcutter’s Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Windmill'),
   ('FANTASY', 'PLACE', 'L5', 'Windrider Keep'),
   ('FANTASY', 'PLACE', 'L5', 'Windrider’s Observatory'),
   ('FANTASY', 'PLACE', 'L5', 'Windrunner’s Tent'),
   ('FANTASY', 'PLACE', 'L5', 'Windshard Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Windsong Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Windsong Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Windstorm Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Windward Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Wingcliff Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Winged Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Winged Haven'),
   ('FANTASY', 'PLACE', 'L5', 'Winged Hollow'),
   ('FANTASY', 'PLACE', 'L5', 'Winged Sanctuary'),
   ('FANTASY', 'PLACE', 'L5', 'Wingshadow Spire'),
   ('FANTASY', 'PLACE', 'L5', 'Wingshield Citadel'),
   ('FANTASY', 'PLACE', 'L5', 'Wingspan Barracks'),
   ('FANTASY', 'PLACE', 'L5', 'Wispwood Refuge'),
   ('FANTASY', 'PLACE', 'L5', 'Witch’s Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Wizard’s Retreat'),
   ('FANTASY', 'PLACE', 'L5', 'Wizard’s Sanctum'),
   ('FANTASY', 'PLACE', 'L5', 'Wizard’s Tower'),
   ('FANTASY', 'PLACE', 'L5', 'Wobbling Wharf'),
   ('FANTASY', 'PLACE', 'L5', 'Worm-Eaten Bastion'),
   ('FANTASY', 'PLACE', 'L5', 'Wormhole Fortress'),
   ('FANTASY', 'PLACE', 'L5', 'Wormwood Hut'),
   ('FANTASY', 'PLACE', 'L5', 'Woven Vineshelter'),
   ('FANTASY', 'PLACE', 'L5', 'Wraith-Filled Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Wreckage Hall'),
   ('FANTASY', 'PLACE', 'L5', 'Wyrmstone Temple'),
   ('FANTASY', 'PLACE', 'L5', 'Wyrm’s Roost'),
   ('FANTASY', 'PLACE', 'L5', 'Zigzagged Pit');

commit;