use hierarchy_generator;

INSERT INTO `NameAdjectives` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('FANTASY', 'PLACE', 'L3', 'Ancient Oracle’s'),
   ('FANTASY', 'PLACE', 'L3', 'Ancient Singer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Anvilborn'),
   ('FANTASY', 'PLACE', 'L3', 'Arcane Owl'),
   ('FANTASY', 'PLACE', 'L3', 'Arcane Spiral'),
   ('FANTASY', 'PLACE', 'L3', 'Arcanist’s Wake'),
   ('FANTASY', 'PLACE', 'L3', 'Ash-Born'),
   ('FANTASY', 'PLACE', 'L3', 'Ash-Crowned'),
   ('FANTASY', 'PLACE', 'L3', 'Ash-Stained'),
   ('FANTASY', 'PLACE', 'L3', 'Ash-Tongued'),
   ('FANTASY', 'PLACE', 'L3', 'Ashen Vow'),
   ('FANTASY', 'PLACE', 'L3', 'Astral-Crowned'),
   ('FANTASY', 'PLACE', 'L3', 'Axebitten'),
   ('FANTASY', 'PLACE', 'L3', 'Barreldelver’s'),
   ('FANTASY', 'PLACE', 'L3', 'Battle-Cursed'),
   ('FANTASY', 'PLACE', 'L3', 'Blackblood'),
   ('FANTASY', 'PLACE', 'L3', 'Blackstone'),
   ('FANTASY', 'PLACE', 'L3', 'Blacktongue'),
   ('FANTASY', 'PLACE', 'L3', 'Blacktooth'),
   ('FANTASY', 'PLACE', 'L3', 'Bladeshorn'),
   ('FANTASY', 'PLACE', 'L3', 'Blight-Touched'),
   ('FANTASY', 'PLACE', 'L3', 'Blightborn'),
   ('FANTASY', 'PLACE', 'L3', 'Blistered Iron'),
   ('FANTASY', 'PLACE', 'L3', 'Blood-Eyed'),
   ('FANTASY', 'PLACE', 'L3', 'Blood-Touched'),
   ('FANTASY', 'PLACE', 'L3', 'Bloodbraid'),
   ('FANTASY', 'PLACE', 'L3', 'Blooddrinker’s'),
   ('FANTASY', 'PLACE', 'L3', 'Bloodmarked Warrior'),
   ('FANTASY', 'PLACE', 'L3', 'Blooming Thistle'),
   ('FANTASY', 'PLACE', 'L3', 'Bone-Cracked'),
   ('FANTASY', 'PLACE', 'L3', 'Bone-Torched'),
   ('FANTASY', 'PLACE', 'L3', 'Bonefire’s'),
   ('FANTASY', 'PLACE', 'L3', 'Bonehowler’s'),
   ('FANTASY', 'PLACE', 'L3', 'Brimstone-Crowned'),
   ('FANTASY', 'PLACE', 'L3', 'Broken Fang'),
   ('FANTASY', 'PLACE', 'L3', 'Broken Sword'),
   ('FANTASY', 'PLACE', 'L3', 'Bronzebeard’s'),
   ('FANTASY', 'PLACE', 'L3', 'Brute-Wrought'),
   ('FANTASY', 'PLACE', 'L3', 'Burning Covenant'),
   ('FANTASY', 'PLACE', 'L3', 'Burnt-Earth'),
   ('FANTASY', 'PLACE', 'L3', 'Celestial Seal'),
   ('FANTASY', 'PLACE', 'L3', 'Chainbound'),
   ('FANTASY', 'PLACE', 'L3', 'Chainbound Flame'),
   ('FANTASY', 'PLACE', 'L3', 'Charnel Warden’s'),
   ('FANTASY', 'PLACE', 'L3', 'Chieftain’s Wrath'),
   ('FANTASY', 'PLACE', 'L3', 'Chronoglyph'),
   ('FANTASY', 'PLACE', 'L3', 'Chronomancer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Cinder-Eyed'),
   ('FANTASY', 'PLACE', 'L3', 'Cloaked Star'),
   ('FANTASY', 'PLACE', 'L3', 'Coalhearted'),
   ('FANTASY', 'PLACE', 'L3', 'Copper-Browed'),
   ('FANTASY', 'PLACE', 'L3', 'Corpse-Splitter’s'),
   ('FANTASY', 'PLACE', 'L3', 'Cracked Helm'),
   ('FANTASY', 'PLACE', 'L3', 'Cragborn'),
   ('FANTASY', 'PLACE', 'L3', 'Crimson Grave'),
   ('FANTASY', 'PLACE', 'L3', 'Crimson Pact'),
   ('FANTASY', 'PLACE', 'L3', 'Crown of Thorns'),
   ('FANTASY', 'PLACE', 'L3', 'Crowned Anvil'),
   ('FANTASY', 'PLACE', 'L3', 'Crystal Veil'),
   ('FANTASY', 'PLACE', 'L3', 'Crystal-Spined'),
   ('FANTASY', 'PLACE', 'L3', 'Curse-Marked'),
   ('FANTASY', 'PLACE', 'L3', 'Daggermaw'),
   ('FANTASY', 'PLACE', 'L3', 'Dark Promise'),
   ('FANTASY', 'PLACE', 'L3', 'Death-Tide'),
   ('FANTASY', 'PLACE', 'L3', 'Deathchant'),
   ('FANTASY', 'PLACE', 'L3', 'Deep-Hammered'),
   ('FANTASY', 'PLACE', 'L3', 'Deep-Warded'),
   ('FANTASY', 'PLACE', 'L3', 'Deepdelver’s'),
   ('FANTASY', 'PLACE', 'L3', 'Demon’s Grin'),
   ('FANTASY', 'PLACE', 'L3', 'Desecrator’s Mark'),
   ('FANTASY', 'PLACE', 'L3', 'Doomchant'),
   ('FANTASY', 'PLACE', 'L3', 'Dread Sorcerer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Dread-Eyed'),
   ('FANTASY', 'PLACE', 'L3', 'Dream-Linked'),
   ('FANTASY', 'PLACE', 'L3', 'Dreaming Star'),
   ('FANTASY', 'PLACE', 'L3', 'Dreamthorn'),
   ('FANTASY', 'PLACE', 'L3', 'Duskborn'),
   ('FANTASY', 'PLACE', 'L3', 'Dust-Warded'),
   ('FANTASY', 'PLACE', 'L3', 'Earthblooded'),
   ('FANTASY', 'PLACE', 'L3', 'Elderscribed'),
   ('FANTASY', 'PLACE', 'L3', 'Ember-Crowned'),
   ('FANTASY', 'PLACE', 'L3', 'Ember-Eyed'),
   ('FANTASY', 'PLACE', 'L3', 'Ember-Wreathed'),
   ('FANTASY', 'PLACE', 'L3', 'Emberglyph'),
   ('FANTASY', 'PLACE', 'L3', 'Enchanted Lantern'),
   ('FANTASY', 'PLACE', 'L3', 'Ether-Sung'),
   ('FANTASY', 'PLACE', 'L3', 'Ethereal Bloom'),
   ('FANTASY', 'PLACE', 'L3', 'Featherquill’s'),
   ('FANTASY', 'PLACE', 'L3', 'Fey-Whisper'),
   ('FANTASY', 'PLACE', 'L3', 'Fire-Anointed'),
   ('FANTASY', 'PLACE', 'L3', 'Fire-Braided'),
   ('FANTASY', 'PLACE', 'L3', 'Fire-Eyed Giant'),
   ('FANTASY', 'PLACE', 'L3', 'Fire-Lashed'),
   ('FANTASY', 'PLACE', 'L3', 'Flamebrand'),
   ('FANTASY', 'PLACE', 'L3', 'Flaybrand'),
   ('FANTASY', 'PLACE', 'L3', 'Forge-Kissed'),
   ('FANTASY', 'PLACE', 'L3', 'Forgefather’s'),
   ('FANTASY', 'PLACE', 'L3', 'Forgotten Wraith'),
   ('FANTASY', 'PLACE', 'L3', 'Frostjaw'),
   ('FANTASY', 'PLACE', 'L3', 'Gemcarver’s'),
   ('FANTASY', 'PLACE', 'L3', 'Gentle Deer'),
   ('FANTASY', 'PLACE', 'L3', 'Gilded Antler'),
   ('FANTASY', 'PLACE', 'L3', 'Gilded Page'),
   ('FANTASY', 'PLACE', 'L3', 'Glimmering Spirit'),
   ('FANTASY', 'PLACE', 'L3', 'Goldbound'),
   ('FANTASY', 'PLACE', 'L3', 'Golden Sunbeam'),
   ('FANTASY', 'PLACE', 'L3', 'Goldvein'),
   ('FANTASY', 'PLACE', 'L3', 'Gravetusk'),
   ('FANTASY', 'PLACE', 'L3', 'Greathammer'),
   ('FANTASY', 'PLACE', 'L3', 'Grim Raven'),
   ('FANTASY', 'PLACE', 'L3', 'Grime-Clad'),
   ('FANTASY', 'PLACE', 'L3', 'Grimoire-Keeper’s'),
   ('FANTASY', 'PLACE', 'L3', 'Grudgebearer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Hammerdeep'),
   ('FANTASY', 'PLACE', 'L3', 'Hammerthane'),
   ('FANTASY', 'PLACE', 'L3', 'Hate-Wrought'),
   ('FANTASY', 'PLACE', 'L3', 'Haunted Widow’s'),
   ('FANTASY', 'PLACE', 'L3', 'Hearth-Hollowed'),
   ('FANTASY', 'PLACE', 'L3', 'Hellborne'),
   ('FANTASY', 'PLACE', 'L3', 'Hellfire’s Whisper'),
   ('FANTASY', 'PLACE', 'L3', 'Helmcarver’s'),
   ('FANTASY', 'PLACE', 'L3', 'Hexcarved'),
   ('FANTASY', 'PLACE', 'L3', 'Hollow-Eyed'),
   ('FANTASY', 'PLACE', 'L3', 'Horn-Crowned'),
   ('FANTASY', 'PLACE', 'L3', 'Howling Fang'),
   ('FANTASY', 'PLACE', 'L3', 'Illusion-Braided'),
   ('FANTASY', 'PLACE', 'L3', 'Infernal Eye'),
   ('FANTASY', 'PLACE', 'L3', 'Ink-Stained'),
   ('FANTASY', 'PLACE', 'L3', 'Iron Wolf'),
   ('FANTASY', 'PLACE', 'L3', 'Iron-Burnt'),
   ('FANTASY', 'PLACE', 'L3', 'Ironflame'),
   ('FANTASY', 'PLACE', 'L3', 'Ironforged'),
   ('FANTASY', 'PLACE', 'L3', 'Ironjaw'),
   ('FANTASY', 'PLACE', 'L3', 'Lava-Bathed'),
   ('FANTASY', 'PLACE', 'L3', 'Leaf-Kissed'),
   ('FANTASY', 'PLACE', 'L3', 'Lore-Bound'),
   ('FANTASY', 'PLACE', 'L3', 'Loreforged'),
   ('FANTASY', 'PLACE', 'L3', 'Magma-Blooded'),
   ('FANTASY', 'PLACE', 'L3', 'Malice-Forged'),
   ('FANTASY', 'PLACE', 'L3', 'Mawscarred'),
   ('FANTASY', 'PLACE', 'L3', 'Mindpiercer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Mirror-Wrought'),
   ('FANTASY', 'PLACE', 'L3', 'Misty Hill'),
   ('FANTASY', 'PLACE', 'L3', 'Mithril-Clad'),
   ('FANTASY', 'PLACE', 'L3', 'Moon-Hallowed'),
   ('FANTASY', 'PLACE', 'L3', 'Moon-Scribed'),
   ('FANTASY', 'PLACE', 'L3', 'Moon-Warped'),
   ('FANTASY', 'PLACE', 'L3', 'Moonlit Sage'),
   ('FANTASY', 'PLACE', 'L3', 'Mossy Elm'),
   ('FANTASY', 'PLACE', 'L3', 'Nightwhispered'),
   ('FANTASY', 'PLACE', 'L3', 'Oath-Shattered'),
   ('FANTASY', 'PLACE', 'L3', 'Oathbound'),
   ('FANTASY', 'PLACE', 'L3', 'Oathbreaker’s'),
   ('FANTASY', 'PLACE', 'L3', 'Oracle’s Ash'),
   ('FANTASY', 'PLACE', 'L3', 'Ore-Drinker’s'),
   ('FANTASY', 'PLACE', 'L3', 'Oreheart’s'),
   ('FANTASY', 'PLACE', 'L3', 'Pale Moon'),
   ('FANTASY', 'PLACE', 'L3', 'Pickhand’s'),
   ('FANTASY', 'PLACE', 'L3', 'Quiet Shepherd’s'),
   ('FANTASY', 'PLACE', 'L3', 'Quill-Bent'),
   ('FANTASY', 'PLACE', 'L3', 'Rageforged'),
   ('FANTASY', 'PLACE', 'L3', 'Ravager’s Grin'),
   ('FANTASY', 'PLACE', 'L3', 'Razorbound'),
   ('FANTASY', 'PLACE', 'L3', 'Red-Eyed'),
   ('FANTASY', 'PLACE', 'L3', 'Red-Eyed Horns'),
   ('FANTASY', 'PLACE', 'L3', 'Red-Fanged'),
   ('FANTASY', 'PLACE', 'L3', 'Red-Vein'),
   ('FANTASY', 'PLACE', 'L3', 'Riftborn'),
   ('FANTASY', 'PLACE', 'L3', 'Rockrooted'),
   ('FANTASY', 'PLACE', 'L3', 'Rotfang'),
   ('FANTASY', 'PLACE', 'L3', 'Rune-Sealed'),
   ('FANTASY', 'PLACE', 'L3', 'Rune-etched'),
   ('FANTASY', 'PLACE', 'L3', 'Runemarked'),
   ('FANTASY', 'PLACE', 'L3', 'Rustfang'),
   ('FANTASY', 'PLACE', 'L3', 'Rustling Willow'),
   ('FANTASY', 'PLACE', 'L3', 'Sapphire Archer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Scarhound’s'),
   ('FANTASY', 'PLACE', 'L3', 'Scarred Tusker’s'),
   ('FANTASY', 'PLACE', 'L3', 'Scary Vampire'),
   ('FANTASY', 'PLACE', 'L3', 'Scorch-Cursed'),
   ('FANTASY', 'PLACE', 'L3', 'Screaming Flame'),
   ('FANTASY', 'PLACE', 'L3', 'Scroll-Kissed'),
   ('FANTASY', 'PLACE', 'L3', 'Shadow-Cloaked'),
   ('FANTASY', 'PLACE', 'L3', 'Shieldwright’s'),
   ('FANTASY', 'PLACE', 'L3', 'Shrieking Maw'),
   ('FANTASY', 'PLACE', 'L3', 'Sigil-Spun'),
   ('FANTASY', 'PLACE', 'L3', 'Silver Flame'),
   ('FANTASY', 'PLACE', 'L3', 'Silverveined'),
   ('FANTASY', 'PLACE', 'L3', 'Sin-Eater’s'),
   ('FANTASY', 'PLACE', 'L3', 'Singing River'),
   ('FANTASY', 'PLACE', 'L3', 'Sinshackled'),
   ('FANTASY', 'PLACE', 'L3', 'Skarr-Blessed'),
   ('FANTASY', 'PLACE', 'L3', 'Skullhammer'),
   ('FANTASY', 'PLACE', 'L3', 'Slaughtermark'),
   ('FANTASY', 'PLACE', 'L3', 'Soft Wind'),
   ('FANTASY', 'PLACE', 'L3', 'Soulflayer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Spellbound Wind'),
   ('FANTASY', 'PLACE', 'L3', 'Spellburned'),
   ('FANTASY', 'PLACE', 'L3', 'Spellmarked'),
   ('FANTASY', 'PLACE', 'L3', 'Spiral-Eyed'),
   ('FANTASY', 'PLACE', 'L3', 'Splitbone'),
   ('FANTASY', 'PLACE', 'L3', 'Staff-Bearer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Starcaller’s Echo'),
   ('FANTASY', 'PLACE', 'L3', 'Starlight Wanderer’s'),
   ('FANTASY', 'PLACE', 'L3', 'Starlit Arcanum'),
   ('FANTASY', 'PLACE', 'L3', 'Starroot'),
   ('FANTASY', 'PLACE', 'L3', 'Starwoven'),
   ('FANTASY', 'PLACE', 'L3', 'Steel-Sung'),
   ('FANTASY', 'PLACE', 'L3', 'Stonefather’s'),
   ('FANTASY', 'PLACE', 'L3', 'Stonethrone’s'),
   ('FANTASY', 'PLACE', 'L3', 'Storm-Hammered'),
   ('FANTASY', 'PLACE', 'L3', 'Stoutshield'),
   ('FANTASY', 'PLACE', 'L3', 'Sweet Clover'),
   ('FANTASY', 'PLACE', 'L3', 'The Broken Sigil'),
   ('FANTASY', 'PLACE', 'L3', 'The Fallen Seal'),
   ('FANTASY', 'PLACE', 'L3', 'Thirsting Flame'),
   ('FANTASY', 'PLACE', 'L3', 'Thorn-Crowned'),
   ('FANTASY', 'PLACE', 'L3', 'Thunderhide'),
   ('FANTASY', 'PLACE', 'L3', 'Thundersteel'),
   ('FANTASY', 'PLACE', 'L3', 'Time-Bound'),
   ('FANTASY', 'PLACE', 'L3', 'Timelost'),
   ('FANTASY', 'PLACE', 'L3', 'Tome-Cracked'),
   ('FANTASY', 'PLACE', 'L3', 'Tuskbound'),
   ('FANTASY', 'PLACE', 'L3', 'Twilight Glyph'),
   ('FANTASY', 'PLACE', 'L3', 'Vault of Thought'),
   ('FANTASY', 'PLACE', 'L3', 'Vault-Keeper’s'),
   ('FANTASY', 'PLACE', 'L3', 'Vilebrand'),
   ('FANTASY', 'PLACE', 'L3', 'Void-Inked'),
   ('FANTASY', 'PLACE', 'L3', 'Voidbound'),
   ('FANTASY', 'PLACE', 'L3', 'Wand-Touched'),
   ('FANTASY', 'PLACE', 'L3', 'Wandering Candle'),
   ('FANTASY', 'PLACE', 'L3', 'Wandering Fey'),
   ('FANTASY', 'PLACE', 'L3', 'Wandering Sigil'),
   ('FANTASY', 'PLACE', 'L3', 'Wandlight'),
   ('FANTASY', 'PLACE', 'L3', 'War-Cursed'),
   ('FANTASY', 'PLACE', 'L3', 'Warborn Forger'),
   ('FANTASY', 'PLACE', 'L3', 'Warhowler’s'),
   ('FANTASY', 'PLACE', 'L3', 'Warmaw'),
   ('FANTASY', 'PLACE', 'L3', 'Warp-Fanged'),
   ('FANTASY', 'PLACE', 'L3', 'Warpainted'),
   ('FANTASY', 'PLACE', 'L3', 'Warpfire’s'),
   ('FANTASY', 'PLACE', 'L3', 'Whispering Ember'),
   ('FANTASY', 'PLACE', 'L3', 'Whispering Ghoul'),
   ('FANTASY', 'PLACE', 'L3', 'Whispering Tome'),
   ('FANTASY', 'PLACE', 'L3', 'Wither-Soaked'),
   ('FANTASY', 'PLACE', 'L3', 'Woe-Wrapped'),
   ('FANTASY', 'PLACE', 'L3', 'Woundtaker'),
   ('FANTASY', 'PLACE', 'L3', 'Wrathcloaked');
   
commit;