use hierarchy_generator;

INSERT INTO `NameAdjectives` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('FANTASY', 'PLACE', 'L4', 'Amber-Moonlit Dreaming-Leaf Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Amber-Touched Moonlit Sylvan'),
   ('FANTASY', 'PLACE', 'L4', 'Arcane-Fern Crystal-Bloomed'),
   ('FANTASY', 'PLACE', 'L4', 'Ash-Scarred Flesh-Worn Necropolis'),
   ('FANTASY', 'PLACE', 'L4', 'Ashen Wolfclaw Moonrise'),
   ('FANTASY', 'PLACE', 'L4', 'Ashen-Clawed Thunder-Bound Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Blackened-Hoofed Skull-Touched'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Eaten Ruin-Marked Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Forged Iron-Horned Battle'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Frosted Soul-Devoured Undying'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Howled Lunar Claw'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Laced Steel-Backed Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Marked Steel-Fanged Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Mist Skull-Ravaged Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Roared Grass-Stride Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Roared Iron-Tusked Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Scented Lupine Howl'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Scented War-Scarred Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Soaked Lupine Night-Bound'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Spattered Iron-Fanged War'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Stained Skull-Touched Battle'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Tainted Bone-Crawled Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Blood-Torn Savage-Fanged War'),
   ('FANTASY', 'PLACE', 'L4', 'Bloodied-Claw Iron-Fanged Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Bloodlust Nightfang Moonlit'),
   ('FANTASY', 'PLACE', 'L4', 'Bloodmoon Lupine-Frosted Dark'),
   ('FANTASY', 'PLACE', 'L4', 'Bone-Crafted Thunder-Skinned War'),
   ('FANTASY', 'PLACE', 'L4', 'Bone-Crowned Shadow-Whispered Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Bone-Crushed Steel-Blooded Beast'),
   ('FANTASY', 'PLACE', 'L4', 'Bone-Cursed Flame-Born Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Bone-Horned Thunder-Roared Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Bone-Misted Veil-Cursed Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Bone-Ravaged Thunder-Clawed Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Bone-Touched Fire-Bound Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Celestial Crystal-Sheened Unicorn'),
   ('FANTASY', 'PLACE', 'L4', 'Celestial Glimmering Unicorn-Crowned'),
   ('FANTASY', 'PLACE', 'L4', 'Celestial Horn-Touched Enchanted'),
   ('FANTASY', 'PLACE', 'L4', 'Celestial Unicorn-Woven Moonlit'),
   ('FANTASY', 'PLACE', 'L4', 'Celestial-Aurora Leaf-Marked Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Celestial-Moon-Glazed Sylvan Grove'),
   ('FANTASY', 'PLACE', 'L4', 'Coral-Misted Siren’s Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Coral-Scented Seafoam Haven'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Bloomed Sylvan-Harmony Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Bound Ocean’s Whisper'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Crested Siren Song'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Horned Leaf-Bound Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Horned Starlight Faewood'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Laden Abyssal Tide'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Mane Twilight-Radiant'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Moonlit Sylvan-Bloom'),
   ('FANTASY', 'PLACE', 'L4', 'Crystal-Moonlit Sylvan-Touched'),
   ('FANTASY', 'PLACE', 'L4', 'Dark-Borne Death-Spire Shadow'),
   ('FANTASY', 'PLACE', 'L4', 'Dark-Cloaked Bone-Shrieking Undying'),
   ('FANTASY', 'PLACE', 'L4', 'Dark-Soaked Flesh-Bound Grave'),
   ('FANTASY', 'PLACE', 'L4', 'Dark-Soul Blood-Drained Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Dawn-Blessed Hoof-Roared'),
   ('FANTASY', 'PLACE', 'L4', 'Dawn-Soaked Grass-Hoofed Wanderer'),
   ('FANTASY', 'PLACE', 'L4', 'Death-Bloomed Forgotten-Rune Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Death-Scented Hollow-Breath Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Death-Soaked Cursed-Torn Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Death-Torn Grave-Howled Necropolis'),
   ('FANTASY', 'PLACE', 'L4', 'Death-Touched Ashen-Breath Wraith'),
   ('FANTASY', 'PLACE', 'L4', 'Deep-Crested Tranquil Wave'),
   ('FANTASY', 'PLACE', 'L4', 'Deep-Sung Saltwater'),
   ('FANTASY', 'PLACE', 'L4', 'Deepwater Serenade Pearl-Bound'),
   ('FANTASY', 'PLACE', 'L4', 'Dew-Crowned Sunlight-Elven Grove'),
   ('FANTASY', 'PLACE', 'L4', 'Dream-Crafted Unicorn’s Light'),
   ('FANTASY', 'PLACE', 'L4', 'Dream-Echoed Crystal-Hoofed'),
   ('FANTASY', 'PLACE', 'L4', 'Dreamstone Moon-Touched Silver'),
   ('FANTASY', 'PLACE', 'L4', 'Dreamwhisper Horned Crystal-Bloom'),
   ('FANTASY', 'PLACE', 'L4', 'Dust-Born Flame-Whispered Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Dust-Torn Wind-Roamed Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Earth-Marked Hoof-Touched Wild'),
   ('FANTASY', 'PLACE', 'L4', 'Earth-Shaped Horn-Raised Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Earthbound Thunder-Mane Herd'),
   ('FANTASY', 'PLACE', 'L4', 'Ember-Hearted Hoof-Touched Nomad'),
   ('FANTASY', 'PLACE', 'L4', 'Eternal-Bone Plague-Soaked Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Eternal-Cursed Wraith-Bound Death'),
   ('FANTASY', 'PLACE', 'L4', 'Ethereal Silverlight Horn-Crested'),
   ('FANTASY', 'PLACE', 'L4', 'Ethereal-Crafted Sunlit Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Ever-Flowing Crystal-Lined Moon'),
   ('FANTASY', 'PLACE', 'L4', 'Evergreen Moon-Crafted Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Fae-Bloomed Dew-Drenched Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Faeblossom Horned Dream-Dusted'),
   ('FANTASY', 'PLACE', 'L4', 'Faewood Horned Glimmering Unicorn'),
   ('FANTASY', 'PLACE', 'L4', 'Faewood-Blessed Goldenleaf Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Faewood-Embrace Wind-Dusted Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Faewood-Washed Moonlit Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Faewood-Whispered Radiant-Moon'),
   ('FANTASY', 'PLACE', 'L4', 'Fangclaw Night-Shattered Moon'),
   ('FANTASY', 'PLACE', 'L4', 'Feral-Crowned Iron-Blooded Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Fire-Cracked Bone-Roared Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Fire-Hearted Thunder-Roamed Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Fire-Raged Skull-Fisted War'),
   ('FANTASY', 'PLACE', 'L4', 'Fire-Scorched Bone-Cracked War'),
   ('FANTASY', 'PLACE', 'L4', 'Fire-Wrought Skull-Blooded War'),
   ('FANTASY', 'PLACE', 'L4', 'Flame-Bound Skull-Splintered Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Flame-Scarred Ravage-Blooded Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Flame-Touched Earth-Sworn Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Flame-Woven Grass-Roamed Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Flesh-Bound Moon-Cursed Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Flesh-Hungering Dark-Blooded Undying'),
   ('FANTASY', 'PLACE', 'L4', 'Flesh-Shriek Rot-Silenced Necropolis'),
   ('FANTASY', 'PLACE', 'L4', 'Forest-Hushed Fire-Hearted Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Forgotten-Whispered Rot-Soaked Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Frost-Horned Savage Fang'),
   ('FANTASY', 'PLACE', 'L4', 'Frost-Marked Shifting Wolf'),
   ('FANTASY', 'PLACE', 'L4', 'Fullmoon Howl-Born Shadowfang'),
   ('FANTASY', 'PLACE', 'L4', 'Fullmoon Warden-Guarded Wild'),
   ('FANTASY', 'PLACE', 'L4', 'Fullmoon Wulfkin Shroud'),
   ('FANTASY', 'PLACE', 'L4', 'Gale-Blessed Fire-Crafted Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Gale-Touched Hoofed-Wild Running'),
   ('FANTASY', 'PLACE', 'L4', 'Galloping-Hoof Moonlit Thunder-'),
   ('FANTASY', 'PLACE', 'L4', 'Glimmering Faewood Crystal-Crowned'),
   ('FANTASY', 'PLACE', 'L4', 'Glimmering Faewood Horned'),
   ('FANTASY', 'PLACE', 'L4', 'Glimmering Hoof-Touched Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Glimmering Moon-Pool Silverleaf'),
   ('FANTASY', 'PLACE', 'L4', 'Glimmering Seafoam Dream-Laced'),
   ('FANTASY', 'PLACE', 'L4', 'Glittering Abyss-Touched Siren'),
   ('FANTASY', 'PLACE', 'L4', 'Glittering Guarded Reef'),
   ('FANTASY', 'PLACE', 'L4', 'Glowing Crystal-Pure Unicorn'),
   ('FANTASY', 'PLACE', 'L4', 'Gore-Blooded Stone-Hewn Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Grass-Blessed Hoof-Crafted Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Grass-Echoed Thunder-Marked Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Grass-Marked Galloping-Mane Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Grave-Drenched Moonlit-Silence Undying'),
   ('FANTASY', 'PLACE', 'L4', 'Grave-Hollowed Veil-Worn Undying'),
   ('FANTASY', 'PLACE', 'L4', 'Hoof-Bound Spirit-Roamed Herd'),
   ('FANTASY', 'PLACE', 'L4', 'Hoof-Dusted Clan-Held Wild'),
   ('FANTASY', 'PLACE', 'L4', 'Hoof-Risen Wild-Marked Herd'),
   ('FANTASY', 'PLACE', 'L4', 'Hoof-Roamed Star-Marked Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Hoof-Stormed Wild-Hearted Nomad'),
   ('FANTASY', 'PLACE', 'L4', 'Horn-Raised Galloping-Sun Herd'),
   ('FANTASY', 'PLACE', 'L4', 'Horn-Roared Storm-Soaked Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Horned Celestial Dream-Sung'),
   ('FANTASY', 'PLACE', 'L4', 'Horned-Bound Earth-Touched Galloping'),
   ('FANTASY', 'PLACE', 'L4', 'Howl-Frosted Silverclaw Wolf'),
   ('FANTASY', 'PLACE', 'L4', 'Howl-Touched Savage Lupine'),
   ('FANTASY', 'PLACE', 'L4', 'Howling Beast-Soul Bloodmoon'),
   ('FANTASY', 'PLACE', 'L4', 'Howling Hunter´s Bloodstorm'),
   ('FANTASY', 'PLACE', 'L4', 'Howling Wolf-Born Moonstone'),
   ('FANTASY', 'PLACE', 'L4', 'Howling Wolf-Touched Bloodmoon'),
   ('FANTASY', 'PLACE', 'L4', 'Iridescent Shell-Tide Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Backed Blood-Crushed Battle'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Backed Savage-Horned Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Blooded Warlord-Guarded'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Clad Beast-Born Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Cleaved Bone-Worn Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Fisted Bone-Torn Battle'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Footed Herd-Touched Wild'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Hearted Skull-Touched Battle'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Roared Beast-Blooded Forge'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Spiked Bone-Horned War'),
   ('FANTASY', 'PLACE', 'L4', 'Iron-Wrought Bone-Marked Warlord'),
   ('FANTASY', 'PLACE', 'L4', 'Leaf-Touched Silver-Streaked Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Luminous Faewood Moonbeam'),
   ('FANTASY', 'PLACE', 'L4', 'Luminous Moon-Horned Starflare'),
   ('FANTASY', 'PLACE', 'L4', 'Luminous Wind-Blessed Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Lunar-Wolf Fang-Storm'),
   ('FANTASY', 'PLACE', 'L4', 'Lupine Fangshadow Frostbite'),
   ('FANTASY', 'PLACE', 'L4', 'Lupine Hunter´s Wolfhowl'),
   ('FANTASY', 'PLACE', 'L4', 'Lush-Grove Moon-Touched Radiance'),
   ('FANTASY', 'PLACE', 'L4', 'Lush-Rose Sylvan-Dream Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Midnight Howled Fang-Torn'),
   ('FANTASY', 'PLACE', 'L4', 'Midnight Moonshadow Lupine'),
   ('FANTASY', 'PLACE', 'L4', 'Midnight Wolf-Hunted Savage'),
   ('FANTASY', 'PLACE', 'L4', 'Mist-Kissed Starweave Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Crested Sea-Glimmering'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Frosted Night-Wolf Howl'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Frosted Sylvan-Woven'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Hallowed Howling Beast'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Kissed Hoof-Wrought Herd'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Kissed Stardust-Glowing'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Shadowed Howl-Bound Claw'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Touched Arcane-Woven Sylvan'),
   ('FANTASY', 'PLACE', 'L4', 'Moon-Touched Celestial Hoof'),
   ('FANTASY', 'PLACE', 'L4', 'Moonblessed Faewood Crystal-Crowned'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlight-Horned Luminous Twilight'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Coral-Hearted Pearl'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Crystal-Hoofed Starlight'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Crystal-Horned Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Fang-Walkers Bloodmoon'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Hoof-Bound Warrior’s'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Horn-Woven Faewood'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Nightwolf Blood-Howl'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Ocean-Touched Reef'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Savage Pack'),
   ('FANTASY', 'PLACE', 'L4', 'Moonlit Silverwood-Echoed Star'),
   ('FANTASY', 'PLACE', 'L4', 'Moonshard Ocean-Crowned Coral'),
   ('FANTASY', 'PLACE', 'L4', 'Moonstone-Glowed Silverleaf-Walked'),
   ('FANTASY', 'PLACE', 'L4', 'Necrotic-Hollow Plague-Born Grave'),
   ('FANTASY', 'PLACE', 'L4', 'Night-Blood Moon-Fanged Wolf'),
   ('FANTASY', 'PLACE', 'L4', 'Night-Bound Fang-Howled Lupine'),
   ('FANTASY', 'PLACE', 'L4', 'Night-Frosted Wolf-Torn Fullmoon'),
   ('FANTASY', 'PLACE', 'L4', 'Night-Hunted Crimson Fang'),
   ('FANTASY', 'PLACE', 'L4', 'Night-Risen Rot-Skulled Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Night-Shrouded Wolfmoon Dawn'),
   ('FANTASY', 'PLACE', 'L4', 'Night-Touched Bone-Eater Undying'),
   ('FANTASY', 'PLACE', 'L4', 'Night-Walked Grave-Eater Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Ocean-Blessed Sunken Reef'),
   ('FANTASY', 'PLACE', 'L4', 'Ocean-Bound Coral-Breathing'),
   ('FANTASY', 'PLACE', 'L4', 'Ocean-Echoed Crystal-Winged'),
   ('FANTASY', 'PLACE', 'L4', 'Ocean-Frosted Dream-Bound'),
   ('FANTASY', 'PLACE', 'L4', 'Ocean-Kissed Moonstone Reef'),
   ('FANTASY', 'PLACE', 'L4', 'Pearl-Crowned Moonlit Wave'),
   ('FANTASY', 'PLACE', 'L4', 'Pearl-Touched Ocean-Hearted'),
   ('FANTASY', 'PLACE', 'L4', 'Pearl-Touched Ocean-Winged'),
   ('FANTASY', 'PLACE', 'L4', 'Pearl-Touched Whispering Wave'),
   ('FANTASY', 'PLACE', 'L4', 'Plague-Touched Bone-Crushed Shadow'),
   ('FANTASY', 'PLACE', 'L4', 'Pure Horned Star-Touched'),
   ('FANTASY', 'PLACE', 'L4', 'Purelight Horn-Crafted Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Puremoon Crystal-Horned'),
   ('FANTASY', 'PLACE', 'L4', 'Radiant Dream-Echoed Horn'),
   ('FANTASY', 'PLACE', 'L4', 'Radiant Horn-Touched Silverbeam'),
   ('FANTASY', 'PLACE', 'L4', 'Radiant Horn-Whispered Moonbeam'),
   ('FANTASY', 'PLACE', 'L4', 'Radiant Horned Stardust-Sheen'),
   ('FANTASY', 'PLACE', 'L4', 'Radiant Moon-Touched Starfall'),
   ('FANTASY', 'PLACE', 'L4', 'Radiant-Glade Wind-Washed'),
   ('FANTASY', 'PLACE', 'L4', 'Radiant-Horned Golden-Touched Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Radiant-Whispered Silver-Grove'),
   ('FANTASY', 'PLACE', 'L4', 'Roaring-Hoofed Dawn-Rising Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Rot-Ravaged Shade-Drained'),
   ('FANTASY', 'PLACE', 'L4', 'Rot-Ravaged Wraith-Bound Shadow'),
   ('FANTASY', 'PLACE', 'L4', 'Rotting-Soul Cursed-Screams Necropolis'),
   ('FANTASY', 'PLACE', 'L4', 'Salt-Blessed Shimmering Pearl'),
   ('FANTASY', 'PLACE', 'L4', 'Salt-Soaked Tranquil Abyss'),
   ('FANTASY', 'PLACE', 'L4', 'Sapphire-Hued Mermaid’s Whisper'),
   ('FANTASY', 'PLACE', 'L4', 'Savage Moon-Wolf Shard'),
   ('FANTASY', 'PLACE', 'L4', 'Savage-Born Bone-Cracked War'),
   ('FANTASY', 'PLACE', 'L4', 'Savage-Hearted Iron-Bound War'),
   ('FANTASY', 'PLACE', 'L4', 'Savage-Raised Bone-Skinned Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Sea-Born Crystal-Tide'),
   ('FANTASY', 'PLACE', 'L4', 'Sea-Born Iridescent Shell'),
   ('FANTASY', 'PLACE', 'L4', 'Sea-Kissed Crystal-Bound Moon'),
   ('FANTASY', 'PLACE', 'L4', 'Seabreeze-Scented Moon-Kissed'),
   ('FANTASY', 'PLACE', 'L4', 'Seawind-Whispered Luminous Pearl'),
   ('FANTASY', 'PLACE', 'L4', 'Shadow-Bound Fang-Scarred Wolf'),
   ('FANTASY', 'PLACE', 'L4', 'Shadow-Haunted Grave-Stained Wraith'),
   ('FANTASY', 'PLACE', 'L4', 'Shadow-Howled Wolfpack Night'),
   ('FANTASY', 'PLACE', 'L4', 'Shadow-Mist Bone-Eaten Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Shadow-Wrapped Spirit-Drained Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Shattered-Flesh Night-Touched Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Shattered-Soul Grave-Swallowed Night'),
   ('FANTASY', 'PLACE', 'L4', 'Shattered-Soul Silent-Hunger Undead'),
   ('FANTASY', 'PLACE', 'L4', 'Shattered-Whispered Grave-Torn Undying'),
   ('FANTASY', 'PLACE', 'L4', 'Shell-Bound Ocean-Kissed Pearl'),
   ('FANTASY', 'PLACE', 'L4', 'Shimmering Crystal-Glowed Unicorn'),
   ('FANTASY', 'PLACE', 'L4', 'Shimmering Horned Moonstone'),
   ('FANTASY', 'PLACE', 'L4', 'Shimmering Tide-Mist Coral'),
   ('FANTASY', 'PLACE', 'L4', 'Shimmering Wave-Touched Crystal'),
   ('FANTASY', 'PLACE', 'L4', 'Shining Crystal-Glazed Unicorn-Crowned'),
   ('FANTASY', 'PLACE', 'L4', 'Shining Hoofed Crystal-Bound'),
   ('FANTASY', 'PLACE', 'L4', 'Silent-Bane Ashen-Roamed Dead'),
   ('FANTASY', 'PLACE', 'L4', 'Silent-Hunger Flesh-Cursed Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Silent-Mist Broken-Soul Necropolis'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Bloomed Dew-Scented Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Bloomed Glade-Woven Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Clawed Midnight Howl'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Finned Moonlit Tide'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Hoofed Moonlit Whispering'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Horned Star-Glowed Unicorn'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Horned Twilight-Bloomed Unicorn'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Leafed Fae-Touched Grove'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Mane Moonlit Dreamstone'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Moonlit Dream-Echoed'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Scented Darkfang Howl'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Touched Blood-Torn Wolf'),
   ('FANTASY', 'PLACE', 'L4', 'Silver-Touched Dreamstone Unicorn'),
   ('FANTASY', 'PLACE', 'L4', 'Silverfang Nightclaw Blood'),
   ('FANTASY', 'PLACE', 'L4', 'Silverfang Shadow-Bound Moon'),
   ('FANTASY', 'PLACE', 'L4', 'Silverleaf-Walked Starlight-Dream Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Siren-Sung Tidal Moon'),
   ('FANTASY', 'PLACE', 'L4', 'Skull-Blooded Iron-Wrought War'),
   ('FANTASY', 'PLACE', 'L4', 'Skull-Bound Iron-Cracked Battle'),
   ('FANTASY', 'PLACE', 'L4', 'Skull-Crushed Blood-Roared Beast'),
   ('FANTASY', 'PLACE', 'L4', 'Skull-Frosted Blood-Chilled Specter'),
   ('FANTASY', 'PLACE', 'L4', 'Sky-High Herd-Marked Thunder'),
   ('FANTASY', 'PLACE', 'L4', 'Soul-Bound Corpse-Screamed Nightfall'),
   ('FANTASY', 'PLACE', 'L4', 'Soul-Drenched Phantom-Bound Death'),
   ('FANTASY', 'PLACE', 'L4', 'Soul-Eater Silent-Cloaked Necrotic'),
   ('FANTASY', 'PLACE', 'L4', 'Soul-Scorned Flesh-Torn Wraith'),
   ('FANTASY', 'PLACE', 'L4', 'Spirit-Horned Storm-Roamed Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Star-Flecked Sapphire Deep'),
   ('FANTASY', 'PLACE', 'L4', 'Star-Kissed Crystal-Hoofed'),
   ('FANTASY', 'PLACE', 'L4', 'Star-Kissed Grass-Horned Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Star-Lit Shimmering Ocean'),
   ('FANTASY', 'PLACE', 'L4', 'Star-Sprinkled Ancient-Oak Whispering'),
   ('FANTASY', 'PLACE', 'L4', 'Stardust-Touched Silver Hoof'),
   ('FANTASY', 'PLACE', 'L4', 'Starlight-Pure Unicorn-Blessed'),
   ('FANTASY', 'PLACE', 'L4', 'Starlight-Touched Faewood Radiance'),
   ('FANTASY', 'PLACE', 'L4', 'Starlight-Washed Crystal-Leaf Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Starlit Horned Faewood Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Starlit-Mystic Silver-Drenched'),
   ('FANTASY', 'PLACE', 'L4', 'Starry-Touched Silver-Leaf Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Steel-Clad Thunder-Fanged War'),
   ('FANTASY', 'PLACE', 'L4', 'Stone-Fist Blood-Torn Beast'),
   ('FANTASY', 'PLACE', 'L4', 'Stone-Fisted Blood-Horned Battle'),
   ('FANTASY', 'PLACE', 'L4', 'Stone-Raised Blood-Bound Warchief'),
   ('FANTASY', 'PLACE', 'L4', 'Stone-Torn Blood-Wrought Beast'),
   ('FANTASY', 'PLACE', 'L4', 'Stone-Wild Thunder-Bound Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Stone-Wrought Horn-Roared Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Storm-Chased Swift-Hoofed Nomad'),
   ('FANTASY', 'PLACE', 'L4', 'Storm-Shadowed Earthbound Herd-Mane'),
   ('FANTASY', 'PLACE', 'L4', 'Storm-Touched Hoof-Sworn Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Storm-Whipped Horned-Warrior Herd'),
   ('FANTASY', 'PLACE', 'L4', 'Sun-Drenched Hoof-Bound Plains'),
   ('FANTASY', 'PLACE', 'L4', 'Sun-Horned Galloping-Earth Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Sun-Kissed Arcane-Leaf Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Sun-Kissed Meadow-Bound Galloping'),
   ('FANTASY', 'PLACE', 'L4', 'Sun-Kissed Verdant-Grove Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Sunken Coral-Sheened Wave'),
   ('FANTASY', 'PLACE', 'L4', 'Sunken Shell-Whispered Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Sylvan-Sung Silver-Pool'),
   ('FANTASY', 'PLACE', 'L4', 'Thunder-Blooded Flame-Forged War'),
   ('FANTASY', 'PLACE', 'L4', 'Thunder-Bound Bone-Ravaged Orc'),
   ('FANTASY', 'PLACE', 'L4', 'Thunder-Fist Iron-Torn War'),
   ('FANTASY', 'PLACE', 'L4', 'Thunder-Lashed Herd-Bound Galloping'),
   ('FANTASY', 'PLACE', 'L4', 'Thunder-Roamed Earth-Blessed Galloping'),
   ('FANTASY', 'PLACE', 'L4', 'Tidal-Whispered Deepwater Pearl'),
   ('FANTASY', 'PLACE', 'L4', 'Tide-Bound Serpent-Song'),
   ('FANTASY', 'PLACE', 'L4', 'Tranquil Deepwater Dream-Wave'),
   ('FANTASY', 'PLACE', 'L4', 'Tranquil Star-Sheened Coral'),
   ('FANTASY', 'PLACE', 'L4', 'Twilight Glimmering Horned Stardust'),
   ('FANTASY', 'PLACE', 'L4', 'Twilight Moonbeam Unicorn’s Grace'),
   ('FANTASY', 'PLACE', 'L4', 'Twilight-Glimmering Star-Leaf Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Twilight-Glowing Emerald-Woven Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Twilight-Misted Star-Horned Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Undying-Bone Soul-Weeping Shadow'),
   ('FANTASY', 'PLACE', 'L4', 'Veil-Torn Bone-Crafted Undying'),
   ('FANTASY', 'PLACE', 'L4', 'Wave-Touched Ocean-Crowned Dream'),
   ('FANTASY', 'PLACE', 'L4', 'Whispering Grove-Hearted Silvermoon'),
   ('FANTASY', 'PLACE', 'L4', 'Whispering Ocean-Tide Star'),
   ('FANTASY', 'PLACE', 'L4', 'Whispering Tide-Crystal Coral'),
   ('FANTASY', 'PLACE', 'L4', 'Whispering-Moon Crystal-Crafted Elven'),
   ('FANTASY', 'PLACE', 'L4', 'Whispering-Wind Grave-Touched Specter'),
   ('FANTASY', 'PLACE', 'L4', 'Wildflower-Blanketed Starbound Grove'),
   ('FANTASY', 'PLACE', 'L4', 'Wind-Crafted Stone-Roamed Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Wind-Forged Galloping-Mane Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Wind-Horned Herd-Crafted Centaur'),
   ('FANTASY', 'PLACE', 'L4', 'Wind-Roared Blood-Rustled Warrior'),
   ('FANTASY', 'PLACE', 'L4', 'Wind-Swept Plains-Rider Clan'),
   ('FANTASY', 'PLACE', 'L4', 'Wolf-Bound Dark-Sky Fullmoon'),
   ('FANTASY', 'PLACE', 'L4', 'Wolf-Bound Silent Nightfall'),
   ('FANTASY', 'PLACE', 'L4', 'Wolf-Crowned Shadow-Hunters Fullmoon'),
   ('FANTASY', 'PLACE', 'L4', 'Wolf-Kissed Silverstorm Fullmoon'),
   ('FANTASY', 'PLACE', 'L4', 'Wolf-Marked Shadow-Wolf Night'),
   ('FANTASY', 'PLACE', 'L4', 'Wolf-Touched Darkfang Moon'),
   ('FANTASY', 'PLACE', 'L4', 'Wolf-Touched Twilight Shadow'),
   ('FANTASY', 'PLACE', 'L4', 'Wraith-Touched Moon-Swallowed Necropolis');

commit;