use hierarchy_generator;

INSERT INTO `NameTitles` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('VIKING', 'PLACE', 'L4', 'Chieftain of'),
   ('VIKING', 'PLACE', 'L4', 'Jarl of'),
   ('VIKING', 'PLACE', 'L4', 'Thane of'),
   ('VIKING', 'PLACE', 'L4', 'Overlord of'),
   ('VIKING', 'PLACE', 'L4', 'Hersir of'),
   ('VIKING', 'PLACE', 'L4', 'Steward of'),
   ('VIKING', 'PLACE', 'L4', 'Skald of'),
   ('VIKING', 'PLACE', 'L4', 'Warden of'),
   ('VIKING', 'PLACE', 'L4', 'Varangian of'),
   ('VIKING', 'PLACE', 'L4', 'Earl of'),
   ('VIKING', 'PLACE', 'L4', 'Captain of'),
   ('VIKING', 'PLACE', 'L4', 'Ruler of'),
   ('VIKING', 'PLACE', 'L4', 'Protector of'),
   ('VIKING', 'PLACE', 'L4', 'Guardian of'),
   ('VIKING', 'PLACE', 'L4', 'Chamberlain of'),
   ('VIKING', 'PLACE', 'L4', 'Lord of'),
   ('VIKING', 'PLACE', 'L4', 'High Chief of'),
   ('VIKING', 'PLACE', 'L4', 'Bailiff of'),
   ('VIKING', 'PLACE', 'L4', 'Overseer of'),
   ('VIKING', 'PLACE', 'L4', 'Master of'),
   ('VIKING', 'PLACE', 'L4', 'Ranger of'),
   ('VIKING', 'PLACE', 'L4', 'Harbinger of'),
   ('VIKING', 'PLACE', 'L4', 'Viggo of'),
   ('VIKING', 'PLACE', 'L4', 'Hirdman of'),
   ('VIKING', 'PLACE', 'L4', 'Shield-bearer of'),
   ('VIKING', 'PLACE', 'L4', 'Watcher of'),
   ('VIKING', 'PLACE', 'L4', 'Vikinglord of'),
   ('VIKING', 'PLACE', 'L4', 'Vanguard of'),
   ('VIKING', 'PLACE', 'L4', 'Hearthwarden of'),
   ('VIKING', 'PLACE', 'L4', 'Skjaldmær of'),
   ('VIKING', 'PLACE', 'L4', 'Captain of the Watch'),
   ('VIKING', 'PLACE', 'L4', 'Tactical Commander of'),
   ('VIKING', 'PLACE', 'L4', 'Shield Captain of'),
   ('VIKING', 'PLACE', 'L4', 'Berserker Chief of'),
   ('VIKING', 'PLACE', 'L4', 'Thane of the Shield'),
   ('VIKING', 'PLACE', 'L4', 'Loyal Companion of'),
   ('VIKING', 'PLACE', 'L4', 'Jarl’s Hand of'),
   ('VIKING', 'PLACE', 'L4', 'Landsman of');

commit;