use hierarchy_generator;

INSERT INTO `NameAdjectives` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('VIKING', 'PLACE', 'L1', 'Ancient'),
   ('VIKING', 'PLACE', 'L1', 'Nordic'),
   ('VIKING', 'PLACE', 'L1', 'Ironclad'),
   ('VIKING', 'PLACE', 'L1', 'Frostbound'),
   ('VIKING', 'PLACE', 'L1', 'Bloodied'),
   ('VIKING', 'PLACE', 'L1', 'Stormborn'),
   ('VIKING', 'PLACE', 'L1', 'Wolf-fanged'),
   ('VIKING', 'PLACE', 'L1', 'Thunderstrike'),
   ('VIKING', 'PLACE', 'L1', 'Valiant'),
   ('VIKING', 'PLACE', 'L1', 'Runic'),
   ('VIKING', 'PLACE', 'L1', 'Iron-hearted'),
   ('VIKING', 'PLACE', 'L1', 'Blood-soaked'),
   ('VIKING', 'PLACE', 'L1', 'Frozen'),
   ('VIKING', 'PLACE', 'L1', 'Berserk'),
   ('VIKING', 'PLACE', 'L1', 'Warborn'),
   ('VIKING', 'PLACE', 'L1', 'Raven-clad'),
   ('VIKING', 'PLACE', 'L1', 'Valkyrie-guided'),
   ('VIKING', 'PLACE', 'L1', 'Shielded'),
   ('VIKING', 'PLACE', 'L1', 'Hearthbound'),
   ('VIKING', 'PLACE', 'L1', 'Storm-ravaged'),
   ('VIKING', 'PLACE', 'L1', 'Fire-forged'),
   ('VIKING', 'PLACE', 'L1', 'Glacial'),
   ('VIKING', 'PLACE', 'L1', 'Thunderclash'),
   ('VIKING', 'PLACE', 'L1', 'Axe-wielding'),
   ('VIKING', 'PLACE', 'L1', 'Wolf-hearted'),
   ('VIKING', 'PLACE', 'L1', 'Frost-covered'),
   ('VIKING', 'PLACE', 'L1', 'Iron-forged'),
   ('VIKING', 'PLACE', 'L1', 'Battle-hardened'),
   ('VIKING', 'PLACE', 'L1', 'Drakkar-sailed'),
   ('VIKING', 'PLACE', 'L1', 'Blizzard-born'),
   ('VIKING', 'PLACE', 'L1', 'Viking-clad'),
   ('VIKING', 'PLACE', 'L1', 'Seafaring'),
   ('VIKING', 'PLACE', 'L1', 'Shield-brother'),
   ('VIKING', 'PLACE', 'L1', 'Raven-winged'),
   ('VIKING', 'PLACE', 'L1', 'Wolf-king'),
   ('VIKING', 'PLACE', 'L1', 'Baldur-blessed'),
   ('VIKING', 'PLACE', 'L1', 'Oath-bound'),
   ('VIKING', 'PLACE', 'L1', 'Valkyrie-chosen'),
   ('VIKING', 'PLACE', 'L1', 'Asgardian'),
   ('VIKING', 'PLACE', 'L1', 'Blood-bonded'),
   ('VIKING', 'PLACE', 'L1', 'Stone-hearted'),
   ('VIKING', 'PLACE', 'L1', 'Thor´s Wrath'),
   ('VIKING', 'PLACE', 'L1', 'Valkyrie-blessed'),
   ('VIKING', 'PLACE', 'L1', 'Elder-favored'),
   ('VIKING', 'PLACE', 'L1', 'Wyrm-slayer');


commit;