use hierarchy_generator;

INSERT INTO `NameAdjectives` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('VIKING', 'PLACE', 'L3', 'Aesir-protected'),
   ('VIKING', 'PLACE', 'L3', 'Arctic-bound'),
   ('VIKING', 'PLACE', 'L3', 'Asgard-bound'),
   ('VIKING', 'PLACE', 'L3', 'Asgardian'),
   ('VIKING', 'PLACE', 'L3', 'Ash-ridden'),
   ('VIKING', 'PLACE', 'L3', 'Ashen'),
   ('VIKING', 'PLACE', 'L3', 'Baldur’s light'),
   ('VIKING', 'PLACE', 'L3', 'Baldur’s'),
   ('VIKING', 'PLACE', 'L3', 'Bay-bound'),
   ('VIKING', 'PLACE', 'L3', 'Bitter-cold'),
   ('VIKING', 'PLACE', 'L3', 'Blackened'),
   ('VIKING', 'PLACE', 'L3', 'Blizzard-ravaged'),
   ('VIKING', 'PLACE', 'L3', 'Blood-soaked'),
   ('VIKING', 'PLACE', 'L3', 'Blood-tinged'),
   ('VIKING', 'PLACE', 'L3', 'Blood-touched'),
   ('VIKING', 'PLACE', 'L3', 'Bluff-hung'),
   ('VIKING', 'PLACE', 'L3', 'Boreal'),
   ('VIKING', 'PLACE', 'L3', 'Cavernous'),
   ('VIKING', 'PLACE', 'L3', 'Cliff-side'),
   ('VIKING', 'PLACE', 'L3', 'Coastal'),
   ('VIKING', 'PLACE', 'L3', 'Cold-hammered'),
   ('VIKING', 'PLACE', 'L3', 'Cursed'),
   ('VIKING', 'PLACE', 'L3', 'Darkened'),
   ('VIKING', 'PLACE', 'L3', 'Deep-woods'),
   ('VIKING', 'PLACE', 'L3', 'Desolate'),
   ('VIKING', 'PLACE', 'L3', 'Distant'),
   ('VIKING', 'PLACE', 'L3', 'Fenrir’s'),
   ('VIKING', 'PLACE', 'L3', 'Fire-forged'),
   ('VIKING', 'PLACE', 'L3', 'Fire-kissed'),
   ('VIKING', 'PLACE', 'L3', 'Forest-surrounded'),
   ('VIKING', 'PLACE', 'L3', 'Forge-blessed'),
   ('VIKING', 'PLACE', 'L3', 'Freya’s'),
   ('VIKING', 'PLACE', 'L3', 'Freyja’s blessing'),
   ('VIKING', 'PLACE', 'L3', 'Freyja’s charm'),
   ('VIKING', 'PLACE', 'L3', 'Frost-broken'),
   ('VIKING', 'PLACE', 'L3', 'Frost-covered'),
   ('VIKING', 'PLACE', 'L3', 'Frostbitten'),
   ('VIKING', 'PLACE', 'L3', 'Frozen'),
   ('VIKING', 'PLACE', 'L3', 'Glacier-cradled'),
   ('VIKING', 'PLACE', 'L3', 'Glen-sheltered'),
   ('VIKING', 'PLACE', 'L3', 'Gravel-risen'),
   ('VIKING', 'PLACE', 'L3', 'Hallowed'),
   ('VIKING', 'PLACE', 'L3', 'Hearth-bound'),
   ('VIKING', 'PLACE', 'L3', 'Hearth-hewn'),
   ('VIKING', 'PLACE', 'L3', 'Hearthstone'),
   ('VIKING', 'PLACE', 'L3', 'Heimdallr’s watch'),
   ('VIKING', 'PLACE', 'L3', 'Hel-blighted'),
   ('VIKING', 'PLACE', 'L3', 'Hel’s'),
   ('VIKING', 'PLACE', 'L3', 'Highland'),
   ('VIKING', 'PLACE', 'L3', 'Hugin’s'),
   ('VIKING', 'PLACE', 'L3', 'Ice-bound'),
   ('VIKING', 'PLACE', 'L3', 'Ice-frozen'),
   ('VIKING', 'PLACE', 'L3', 'Ice-locked'),
   ('VIKING', 'PLACE', 'L3', 'Icy'),
   ('VIKING', 'PLACE', 'L3', 'Iron-clad'),
   ('VIKING', 'PLACE', 'L3', 'Jörmungandr-wrapped'),
   ('VIKING', 'PLACE', 'L3', 'Jörmungandr’s'),
   ('VIKING', 'PLACE', 'L3', 'Jötunheimr-stormed'),
   ('VIKING', 'PLACE', 'L3', 'Lake-shored'),
   ('VIKING', 'PLACE', 'L3', 'Loki’s tricks'),
   ('VIKING', 'PLACE', 'L3', 'Loki’s'),
   ('VIKING', 'PLACE', 'L3', 'Longship-guarded'),
   ('VIKING', 'PLACE', 'L3', 'Marsh-wreathed'),
   ('VIKING', 'PLACE', 'L3', 'Midgardian'),
   ('VIKING', 'PLACE', 'L3', 'Mimir’s wisdom'),
   ('VIKING', 'PLACE', 'L3', 'Mjölnir-forged'),
   ('VIKING', 'PLACE', 'L3', 'Moons-guarded'),
   ('VIKING', 'PLACE', 'L3', 'Mountain-bound'),
   ('VIKING', 'PLACE', 'L3', 'Munin’s'),
   ('VIKING', 'PLACE', 'L3', 'Niflheimr-chilled'),
   ('VIKING', 'PLACE', 'L3', 'Night-drenched'),
   ('VIKING', 'PLACE', 'L3', 'Night-fallen'),
   ('VIKING', 'PLACE', 'L3', 'Nordic'),
   ('VIKING', 'PLACE', 'L3', 'Norn-bound'),
   ('VIKING', 'PLACE', 'L3', 'Northern'),
   ('VIKING', 'PLACE', 'L3', 'Ocean-locked'),
   ('VIKING', 'PLACE', 'L3', 'Odin-blessed'),
   ('VIKING', 'PLACE', 'L3', 'Odin’s eye'),
   ('VIKING', 'PLACE', 'L3', 'Odin’s hall'),
   ('VIKING', 'PLACE', 'L3', 'Odin’s'),
   ('VIKING', 'PLACE', 'L3', 'Ragnarök-marked'),
   ('VIKING', 'PLACE', 'L3', 'Raven-marked'),
   ('VIKING', 'PLACE', 'L3', 'Raven-watched'),
   ('VIKING', 'PLACE', 'L3', 'Remote'),
   ('VIKING', 'PLACE', 'L3', 'River-fed'),
   ('VIKING', 'PLACE', 'L3', 'Rune-marked'),
   ('VIKING', 'PLACE', 'L3', 'Runestone-etched'),
   ('VIKING', 'PLACE', 'L3', 'Sea-battered'),
   ('VIKING', 'PLACE', 'L3', 'Secluded'),
   ('VIKING', 'PLACE', 'L3', 'Shadow-clad'),
   ('VIKING', 'PLACE', 'L3', 'Shafted'),
   ('VIKING', 'PLACE', 'L3', 'Shield-maiden’s'),
   ('VIKING', 'PLACE', 'L3', 'Shielded'),
   ('VIKING', 'PLACE', 'L3', 'Shoreswept'),
   ('VIKING', 'PLACE', 'L3', 'Skadi’s'),
   ('VIKING', 'PLACE', 'L3', 'Skald’s song'),
   ('VIKING', 'PLACE', 'L3', 'Skald’s'),
   ('VIKING', 'PLACE', 'L3', 'Sleipnir’s path'),
   ('VIKING', 'PLACE', 'L3', 'Snow-clad'),
   ('VIKING', 'PLACE', 'L3', 'Star-washed'),
   ('VIKING', 'PLACE', 'L3', 'Stone-bound'),
   ('VIKING', 'PLACE', 'L3', 'Storm-battered'),
   ('VIKING', 'PLACE', 'L3', 'Storm-lashed'),
   ('VIKING', 'PLACE', 'L3', 'Storm-swept'),
   ('VIKING', 'PLACE', 'L3', 'Storm-washed'),
   ('VIKING', 'PLACE', 'L3', 'Swamp-shadowed'),
   ('VIKING', 'PLACE', 'L3', 'Thorn-bound'),
   ('VIKING', 'PLACE', 'L3', 'Thor’s hammered'),
   ('VIKING', 'PLACE', 'L3', 'Thor’s'),
   ('VIKING', 'PLACE', 'L3', 'Thunder-struck'),
   ('VIKING', 'PLACE', 'L3', 'Thundering'),
   ('VIKING', 'PLACE', 'L3', 'Tidal'),
   ('VIKING', 'PLACE', 'L3', 'Tundra-bound'),
   ('VIKING', 'PLACE', 'L3', 'Tundra-branded'),
   ('VIKING', 'PLACE', 'L3', 'Tyr’s justice'),
   ('VIKING', 'PLACE', 'L3', 'Tyr’s strength'),
   ('VIKING', 'PLACE', 'L3', 'Valhalla-bound'),
   ('VIKING', 'PLACE', 'L3', 'Valkyrie-blessed'),
   ('VIKING', 'PLACE', 'L3', 'Valkyrie-guarded'),
   ('VIKING', 'PLACE', 'L3', 'Valkyrie’s wings'),
   ('VIKING', 'PLACE', 'L3', 'Valley-dwelling'),
   ('VIKING', 'PLACE', 'L3', 'Vanaheimr-blessed'),
   ('VIKING', 'PLACE', 'L3', 'Wild'),
   ('VIKING', 'PLACE', 'L3', 'Wind-whipped'),
   ('VIKING', 'PLACE', 'L3', 'Windswept'),
   ('VIKING', 'PLACE', 'L3', 'Wolf-haunted'),
   ('VIKING', 'PLACE', 'L3', 'Wolf-marked'),
   ('VIKING', 'PLACE', 'L3', 'Wolfsbane-filled'),
   ('VIKING', 'PLACE', 'L3', 'Yggdrasil-rooted'),
   ('VIKING', 'PLACE', 'L3', 'Ymir’s blood');


commit;