use hierarchy_generator;

INSERT INTO `NameTitles` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('VIKING', 'PLACE', 'L5', 'Aegir’s Fisher'),
   ('VIKING', 'PLACE', 'L5', 'Aegir’s Wavecaller'),
   ('VIKING', 'PLACE', 'L5', 'Ambush Specialist'),
   ('VIKING', 'PLACE', 'L5', 'Ambusher'),
   ('VIKING', 'PLACE', 'L5', 'Anchor Maker'),
   ('VIKING', 'PLACE', 'L5', 'Angrboða’s Hunt'),
   ('VIKING', 'PLACE', 'L5', 'Baldur’s Seeker'),
   ('VIKING', 'PLACE', 'L5', 'Baldur’s Soulkeeper'),
   ('VIKING', 'PLACE', 'L5', 'Beast Slayer'),
   ('VIKING', 'PLACE', 'L5', 'Berserker'),
   ('VIKING', 'PLACE', 'L5', 'Berserker’s Fury'),
   ('VIKING', 'PLACE', 'L5', 'Boat Builder'),
   ('VIKING', 'PLACE', 'L5', 'Boat Joiner'),
   ('VIKING', 'PLACE', 'L5', 'Booty Hunter'),
   ('VIKING', 'PLACE', 'L5', 'Boreas’s Predator'),
   ('VIKING', 'PLACE', 'L5', 'Bragi’s Bard'),
   ('VIKING', 'PLACE', 'L5', 'Bragi’s Rhapsodist'),
   ('VIKING', 'PLACE', 'L5', 'Brawler'),
   ('VIKING', 'PLACE', 'L5', 'Carpenter'),
   ('VIKING', 'PLACE', 'L5', 'Chisel Carver'),
   ('VIKING', 'PLACE', 'L5', 'Chisel Crafter'),
   ('VIKING', 'PLACE', 'L5', 'Coastal Raider'),
   ('VIKING', 'PLACE', 'L5', 'Coastal Scout'),
   ('VIKING', 'PLACE', 'L5', 'Deck Placer'),
   ('VIKING', 'PLACE', 'L5', 'Despoiler'),
   ('VIKING', 'PLACE', 'L5', 'Door Carver'),
   ('VIKING', 'PLACE', 'L5', 'Draugr Hunter'),
   ('VIKING', 'PLACE', 'L5', 'Draugr’s Last Breath'),
   ('VIKING', 'PLACE', 'L5', 'Fafnir’s Vanquisher'),
   ('VIKING', 'PLACE', 'L5', 'Fenrir’s Bane'),
   ('VIKING', 'PLACE', 'L5', 'Fenrir’s Last Stand'),
   ('VIKING', 'PLACE', 'L5', 'Fighter'),
   ('VIKING', 'PLACE', 'L5', 'Forager'),
   ('VIKING', 'PLACE', 'L5', 'Foray Leader'),
   ('VIKING', 'PLACE', 'L5', 'Forest Troll Hunter'),
   ('VIKING', 'PLACE', 'L5', 'Fornjot’s Wrath'),
   ('VIKING', 'PLACE', 'L5', 'Forseti’s Judge'),
   ('VIKING', 'PLACE', 'L5', 'Fort Wall Builder'),
   ('VIKING', 'PLACE', 'L5', 'Fortress Constructor'),
   ('VIKING', 'PLACE', 'L5', 'Freyja’s Huntress'),
   ('VIKING', 'PLACE', 'L5', 'Freyja’s Priestess'),
   ('VIKING', 'PLACE', 'L5', 'Freyja’s Seer'),
   ('VIKING', 'PLACE', 'L5', 'Freyja’s Valkyrie'),
   ('VIKING', 'PLACE', 'L5', 'Freyr’s Gardener'),
   ('VIKING', 'PLACE', 'L5', 'Freyr’s Priest'),
   ('VIKING', 'PLACE', 'L5', 'Frigg’s Matron'),
   ('VIKING', 'PLACE', 'L5', 'Frigg’s Oracle'),
   ('VIKING', 'PLACE', 'L5', 'Garmr’s Conqueror'),
   ('VIKING', 'PLACE', 'L5', 'Giant Slayer'),
   ('VIKING', 'PLACE', 'L5', 'Grave Ransacker'),
   ('VIKING', 'PLACE', 'L5', 'Hati’s Hunt'),
   ('VIKING', 'PLACE', 'L5', 'Hati’s Hunter'),
   ('VIKING', 'PLACE', 'L5', 'Hati’s Pursuer'),
   ('VIKING', 'PLACE', 'L5', 'Hearth Maker'),
   ('VIKING', 'PLACE', 'L5', 'Heimdall’s Watcher'),
   ('VIKING', 'PLACE', 'L5', 'Helblindi’s Cursed'),
   ('VIKING', 'PLACE', 'L5', 'Helblindi’s Shadow'),
   ('VIKING', 'PLACE', 'L5', 'Hel’s Enforcer'),
   ('VIKING', 'PLACE', 'L5', 'Hel’s Warden'),
   ('VIKING', 'PLACE', 'L5', 'Hengikjoll Tracker'),
   ('VIKING', 'PLACE', 'L5', 'Huldufólk Seeker'),
   ('VIKING', 'PLACE', 'L5', 'Hull Builder'),
   ('VIKING', 'PLACE', 'L5', 'Höðr’s Silent'),
   ('VIKING', 'PLACE', 'L5', 'Idunn’s Keeper'),
   ('VIKING', 'PLACE', 'L5', 'Iron Smith'),
   ('VIKING', 'PLACE', 'L5', 'Ironworker'),
   ('VIKING', 'PLACE', 'L5', 'Jotun Riddler'),
   ('VIKING', 'PLACE', 'L5', 'Jotun’s Bane'),
   ('VIKING', 'PLACE', 'L5', 'Jörmungandr’s Killer'),
   ('VIKING', 'PLACE', 'L5', 'Jörmungandr’s Prey'),
   ('VIKING', 'PLACE', 'L5', 'Jörmungandr’s Ruler'),
   ('VIKING', 'PLACE', 'L5', 'Jörmungandr’s Serpent'),
   ('VIKING', 'PLACE', 'L5', 'Keel Setter'),
   ('VIKING', 'PLACE', 'L5', 'Kraken Foe'),
   ('VIKING', 'PLACE', 'L5', 'Lindworm’s Pursuer'),
   ('VIKING', 'PLACE', 'L5', 'Loki’s Cunning'),
   ('VIKING', 'PLACE', 'L5', 'Loki’s Harbinger'),
   ('VIKING', 'PLACE', 'L5', 'Loki’s Trickster'),
   ('VIKING', 'PLACE', 'L5', 'Longboat Crewman'),
   ('VIKING', 'PLACE', 'L5', 'Longboat Oarsman'),
   ('VIKING', 'PLACE', 'L5', 'Longhouse Builder'),
   ('VIKING', 'PLACE', 'L5', 'Loot Collector'),
   ('VIKING', 'PLACE', 'L5', 'Loot Master'),
   ('VIKING', 'PLACE', 'L5', 'Looting Captain'),
   ('VIKING', 'PLACE', 'L5', 'Marauder'),
   ('VIKING', 'PLACE', 'L5', 'Marauder’s Bane'),
   ('VIKING', 'PLACE', 'L5', 'Mast Binder'),
   ('VIKING', 'PLACE', 'L5', 'Mast Builder'),
   ('VIKING', 'PLACE', 'L5', 'Mimir’s Riddlekeeper'),
   ('VIKING', 'PLACE', 'L5', 'Mimir’s Scholar'),
   ('VIKING', 'PLACE', 'L5', 'Mokkurkalfi’s Vanquisher'),
   ('VIKING', 'PLACE', 'L5', 'Mountain Troll Fighter'),
   ('VIKING', 'PLACE', 'L5', 'Njord’s Sailor'),
   ('VIKING', 'PLACE', 'L5', 'Nokken Slayer'),
   ('VIKING', 'PLACE', 'L5', 'Níðhöggr’s Stalker'),
   ('VIKING', 'PLACE', 'L5', 'Odin’s Allfather'),
   ('VIKING', 'PLACE', 'L5', 'Odin’s Chosen'),
   ('VIKING', 'PLACE', 'L5', 'Pillager'),
   ('VIKING', 'PLACE', 'L5', 'Pillaging Strategist'),
   ('VIKING', 'PLACE', 'L5', 'Pillar Setter'),
   ('VIKING', 'PLACE', 'L5', 'Plank Joiner'),
   ('VIKING', 'PLACE', 'L5', 'Plank Layer'),
   ('VIKING', 'PLACE', 'L5', 'Plunder Leader'),
   ('VIKING', 'PLACE', 'L5', 'Plunderer Leader'),
   ('VIKING', 'PLACE', 'L5', 'Plunderer'),
   ('VIKING', 'PLACE', 'L5', 'Rafter Maker'),
   ('VIKING', 'PLACE', 'L5', 'Raid Leader'),
   ('VIKING', 'PLACE', 'L5', 'Raider'),
   ('VIKING', 'PLACE', 'L5', 'Raiding Commander'),
   ('VIKING', 'PLACE', 'L5', 'Raiding Scout'),
   ('VIKING', 'PLACE', 'L5', 'Ransacker'),
   ('VIKING', 'PLACE', 'L5', 'Ran’s Seeker'),
   ('VIKING', 'PLACE', 'L5', 'Ratatoskr’s Pursuer'),
   ('VIKING', 'PLACE', 'L5', 'Ravager'),
   ('VIKING', 'PLACE', 'L5', 'Roof Beamer'),
   ('VIKING', 'PLACE', 'L5', 'Roof Thatcher'),
   ('VIKING', 'PLACE', 'L5', 'Rope Weaver'),
   ('VIKING', 'PLACE', 'L5', 'Sacker'),
   ('VIKING', 'PLACE', 'L5', 'Sailmaker'),
   ('VIKING', 'PLACE', 'L5', 'Sailor'),
   ('VIKING', 'PLACE', 'L5', 'Scout'),
   ('VIKING', 'PLACE', 'L5', 'Seafarer'),
   ('VIKING', 'PLACE', 'L5', 'Shield Bearer'),
   ('VIKING', 'PLACE', 'L5', 'Shield Carver'),
   ('VIKING', 'PLACE', 'L5', 'Shield Maker'),
   ('VIKING', 'PLACE', 'L5', 'Shield Wall Leader'),
   ('VIKING', 'PLACE', 'L5', 'Ship Captain'),
   ('VIKING', 'PLACE', 'L5', 'Ship Carver'),
   ('VIKING', 'PLACE', 'L5', 'Ship Chaser'),
   ('VIKING', 'PLACE', 'L5', 'Ship Designer'),
   ('VIKING', 'PLACE', 'L5', 'Ship Finisher'),
   ('VIKING', 'PLACE', 'L5', 'Shipwright (Raids)'),
   ('VIKING', 'PLACE', 'L5', 'Shipwright'),
   ('VIKING', 'PLACE', 'L5', 'Sif’s Protectress'),
   ('VIKING', 'PLACE', 'L5', 'Sif’s Weaver'),
   ('VIKING', 'PLACE', 'L5', 'Skadi’s Tracker'),
   ('VIKING', 'PLACE', 'L5', 'Skogsrå Tracker'),
   ('VIKING', 'PLACE', 'L5', 'Skoll’s Chaser'),
   ('VIKING', 'PLACE', 'L5', 'Sköll’s Stalker'),
   ('VIKING', 'PLACE', 'L5', 'Sleipnir’s Rider'),
   ('VIKING', 'PLACE', 'L5', 'Stealthy Raider'),
   ('VIKING', 'PLACE', 'L5', 'Stone Mason'),
   ('VIKING', 'PLACE', 'L5', 'Stone Troll Vanquisher'),
   ('VIKING', 'PLACE', 'L5', 'Stonemason'),
   ('VIKING', 'PLACE', 'L5', 'Strategist'),
   ('VIKING', 'PLACE', 'L5', 'Surprise Attacker'),
   ('VIKING', 'PLACE', 'L5', 'Surtur’s Vengeful'),
   ('VIKING', 'PLACE', 'L5', 'Svartálfar Hunter'),
   ('VIKING', 'PLACE', 'L5', 'Svartálfar Tracker'),
   ('VIKING', 'PLACE', 'L5', 'Tannery Worker'),
   ('VIKING', 'PLACE', 'L5', 'Thor’s Hammerbearer'),
   ('VIKING', 'PLACE', 'L5', 'Thor’s Hammerer'),
   ('VIKING', 'PLACE', 'L5', 'Thor’s Thunderer'),
   ('VIKING', 'PLACE', 'L5', 'Timber Cutter'),
   ('VIKING', 'PLACE', 'L5', 'Troll Ambusher'),
   ('VIKING', 'PLACE', 'L5', 'Troll Baiter'),
   ('VIKING', 'PLACE', 'L5', 'Troll Bane'),
   ('VIKING', 'PLACE', 'L5', 'Troll Bastard'),
   ('VIKING', 'PLACE', 'L5', 'Troll Battle Warden'),
   ('VIKING', 'PLACE', 'L5', 'Troll Beast Slayer'),
   ('VIKING', 'PLACE', 'L5', 'Troll Beastmaster'),
   ('VIKING', 'PLACE', 'L5', 'Troll Breaker'),
   ('VIKING', 'PLACE', 'L5', 'Troll Cleaver'),
   ('VIKING', 'PLACE', 'L5', 'Troll Defeater'),
   ('VIKING', 'PLACE', 'L5', 'Troll Destroyer'),
   ('VIKING', 'PLACE', 'L5', 'Troll Dismemberer'),
   ('VIKING', 'PLACE', 'L5', 'Troll Eliminator'),
   ('VIKING', 'PLACE', 'L5', 'Troll Executioner'),
   ('VIKING', 'PLACE', 'L5', 'Troll Expert'),
   ('VIKING', 'PLACE', 'L5', 'Troll Fang Collector'),
   ('VIKING', 'PLACE', 'L5', 'Troll Hunter Captain'),
   ('VIKING', 'PLACE', 'L5', 'Troll Hunter Leader'),
   ('VIKING', 'PLACE', 'L5', 'Troll Hunter Scout'),
   ('VIKING', 'PLACE', 'L5', 'Troll Hunter'),
   ('VIKING', 'PLACE', 'L5', 'Troll Kill Squad Leader'),
   ('VIKING', 'PLACE', 'L5', 'Troll Massacre Specialist'),
   ('VIKING', 'PLACE', 'L5', 'Troll Mounter'),
   ('VIKING', 'PLACE', 'L5', 'Troll Pursuer'),
   ('VIKING', 'PLACE', 'L5', 'Troll Scout'),
   ('VIKING', 'PLACE', 'L5', 'Troll Skewerer'),
   ('VIKING', 'PLACE', 'L5', 'Troll Skinner'),
   ('VIKING', 'PLACE', 'L5', 'Troll Slayer Captain'),
   ('VIKING', 'PLACE', 'L5', 'Troll Slayer'),
   ('VIKING', 'PLACE', 'L5', 'Troll Smasher'),
   ('VIKING', 'PLACE', 'L5', 'Troll Snare Expert'),
   ('VIKING', 'PLACE', 'L5', 'Troll Snatcher'),
   ('VIKING', 'PLACE', 'L5', 'Troll Specialist'),
   ('VIKING', 'PLACE', 'L5', 'Troll Stabber Captain'),
   ('VIKING', 'PLACE', 'L5', 'Troll Stabber'),
   ('VIKING', 'PLACE', 'L5', 'Troll Stalker'),
   ('VIKING', 'PLACE', 'L5', 'Troll Tamer'),
   ('VIKING', 'PLACE', 'L5', 'Troll Tracker Captain'),
   ('VIKING', 'PLACE', 'L5', 'Troll Tracker Expert'),
   ('VIKING', 'PLACE', 'L5', 'Troll Tracker'),
   ('VIKING', 'PLACE', 'L5', 'Troll Trapper'),
   ('VIKING', 'PLACE', 'L5', 'Troll Warden'),
   ('VIKING', 'PLACE', 'L5', 'Trollhunter'),
   ('VIKING', 'PLACE', 'L5', 'Trollskogen Stalker'),
   ('VIKING', 'PLACE', 'L5', 'Tyr’s Avenger'),
   ('VIKING', 'PLACE', 'L5', 'Tyr’s Defender'),
   ('VIKING', 'PLACE', 'L5', 'Ulfhednar Hunter'),
   ('VIKING', 'PLACE', 'L5', 'Valkyrie’s Champion'),
   ('VIKING', 'PLACE', 'L5', 'Valkyrie’s Shadow'),
   ('VIKING', 'PLACE', 'L5', 'Valkyrie’s Stalker'),
   ('VIKING', 'PLACE', 'L5', 'Vampyr Slayer'),
   ('VIKING', 'PLACE', 'L5', 'Vidar’s Avenger'),
   ('VIKING', 'PLACE', 'L5', 'Viking Invader'),
   ('VIKING', 'PLACE', 'L5', 'Viking Raider'),
   ('VIKING', 'PLACE', 'L5', 'Viking Ship Blacksmith'),
   ('VIKING', 'PLACE', 'L5', 'Viking Thief'),
   ('VIKING', 'PLACE', 'L5', 'Víðarr’s Tracker'),
   ('VIKING', 'PLACE', 'L5', 'Víðarr’s Vengeance'),
   ('VIKING', 'PLACE', 'L5', 'Vörgr’s Conqueror'),
   ('VIKING', 'PLACE', 'L5', 'Wagon Maker'),
   ('VIKING', 'PLACE', 'L5', 'Warg’s Bane'),
   ('VIKING', 'PLACE', 'L5', 'Warrior Raider'),
   ('VIKING', 'PLACE', 'L5', 'Wind Sailer'),
   ('VIKING', 'PLACE', 'L5', 'Wolftracker'),
   ('VIKING', 'PLACE', 'L5', 'Woodcarver'),
   ('VIKING', 'PLACE', 'L5', 'Woodworker'),
   ('VIKING', 'PLACE', 'L5', 'Ymir’s Slayer'),
   ('VIKING', 'PLACE', 'L5', 'ale-hauler'),
   ('VIKING', 'PLACE', 'L5', 'ale-keeper'),
   ('VIKING', 'PLACE', 'L5', 'arrow-maker'),
   ('VIKING', 'PLACE', 'L5', 'ash-collector'),
   ('VIKING', 'PLACE', 'L5', 'ash-hauler'),
   ('VIKING', 'PLACE', 'L5', 'axe-bearer'),
   ('VIKING', 'PLACE', 'L5', 'axe-grinder'),
   ('VIKING', 'PLACE', 'L5', 'axe-hurler'),
   ('VIKING', 'PLACE', 'L5', 'bale-hauler'),
   ('VIKING', 'PLACE', 'L5', 'barley-harvester'),
   ('VIKING', 'PLACE', 'L5', 'barn-cleaner'),
   ('VIKING', 'PLACE', 'L5', 'barrel-filler'),
   ('VIKING', 'PLACE', 'L5', 'battle-banner holder'),
   ('VIKING', 'PLACE', 'L5', 'bean-planter'),
   ('VIKING', 'PLACE', 'L5', 'beast-watcher'),
   ('VIKING', 'PLACE', 'L5', 'berry-forager'),
   ('VIKING', 'PLACE', 'L5', 'blade-dancer'),
   ('VIKING', 'PLACE', 'L5', 'blade-engraver'),
   ('VIKING', 'PLACE', 'L5', 'blade-hewer'),
   ('VIKING', 'PLACE', 'L5', 'blade-oiler'),
   ('VIKING', 'PLACE', 'L5', 'blade-runner'),
   ('VIKING', 'PLACE', 'L5', 'blade-smith'),
   ('VIKING', 'PLACE', 'L5', 'boar-roaster'),
   ('VIKING', 'PLACE', 'L5', 'boar-skinner'),
   ('VIKING', 'PLACE', 'L5', 'boatwright'),
   ('VIKING', 'PLACE', 'L5', 'bone-picker'),
   ('VIKING', 'PLACE', 'L5', 'bowmaker'),
   ('VIKING', 'PLACE', 'L5', 'bowstring-puller'),
   ('VIKING', 'PLACE', 'L5', 'bread-baker'),
   ('VIKING', 'PLACE', 'L5', 'brewer'),
   ('VIKING', 'PLACE', 'L5', 'buckler-lifter'),
   ('VIKING', 'PLACE', 'L5', 'butter-churner'),
   ('VIKING', 'PLACE', 'L5', 'carver'),
   ('VIKING', 'PLACE', 'L5', 'chain-mail repairer'),
   ('VIKING', 'PLACE', 'L5', 'cheese-rind scraper'),
   ('VIKING', 'PLACE', 'L5', 'cheese-turner'),
   ('VIKING', 'PLACE', 'L5', 'coal-burner'),
   ('VIKING', 'PLACE', 'L5', 'coal-digger'),
   ('VIKING', 'PLACE', 'L5', 'combat-drummer'),
   ('VIKING', 'PLACE', 'L5', 'combat-tester'),
   ('VIKING', 'PLACE', 'L5', 'cook'),
   ('VIKING', 'PLACE', 'L5', 'crossbow cranker'),
   ('VIKING', 'PLACE', 'L5', 'dagger-dancer'),
   ('VIKING', 'PLACE', 'L5', 'duel-spotter'),
   ('VIKING', 'PLACE', 'L5', 'eel-catcher'),
   ('VIKING', 'PLACE', 'L5', 'egg-gatherer'),
   ('VIKING', 'PLACE', 'L5', 'ember-tender'),
   ('VIKING', 'PLACE', 'L5', 'field hand'),
   ('VIKING', 'PLACE', 'L5', 'field-tiler'),
   ('VIKING', 'PLACE', 'L5', 'firewood-splitter'),
   ('VIKING', 'PLACE', 'L5', 'fish-smoker'),
   ('VIKING', 'PLACE', 'L5', 'fisher'),
   ('VIKING', 'PLACE', 'L5', 'flame-tosser'),
   ('VIKING', 'PLACE', 'L5', 'fur-brusher'),
   ('VIKING', 'PLACE', 'L5', 'game-dresser'),
   ('VIKING', 'PLACE', 'L5', 'goat-herder'),
   ('VIKING', 'PLACE', 'L5', 'goat-milker'),
   ('VIKING', 'PLACE', 'L5', 'grain-thresher'),
   ('VIKING', 'PLACE', 'L5', 'gravedigger'),
   ('VIKING', 'PLACE', 'L5', 'griddle-tender'),
   ('VIKING', 'PLACE', 'L5', 'grip-winder'),
   ('VIKING', 'PLACE', 'L5', 'gruel-cooker'),
   ('VIKING', 'PLACE', 'L5', 'haft-carver'),
   ('VIKING', 'PLACE', 'L5', 'halberd-hauler'),
   ('VIKING', 'PLACE', 'L5', 'harpooner'),
   ('VIKING', 'PLACE', 'L5', 'hay-baler'),
   ('VIKING', 'PLACE', 'L5', 'helm-polisher'),
   ('VIKING', 'PLACE', 'L5', 'herb-drier'),
   ('VIKING', 'PLACE', 'L5', 'herb-grinder'),
   ('VIKING', 'PLACE', 'L5', 'herd-watcher'),
   ('VIKING', 'PLACE', 'L5', 'herder'),
   ('VIKING', 'PLACE', 'L5', 'hide-cleaner'),
   ('VIKING', 'PLACE', 'L5', 'hilt-binder'),
   ('VIKING', 'PLACE', 'L5', 'honey-gatherer'),
   ('VIKING', 'PLACE', 'L5', 'hoof-caretaker'),
   ('VIKING', 'PLACE', 'L5', 'horn-carver'),
   ('VIKING', 'PLACE', 'L5', 'hunter'),
   ('VIKING', 'PLACE', 'L5', 'ice-hauler'),
   ('VIKING', 'PLACE', 'L5', 'ice-splitter'),
   ('VIKING', 'PLACE', 'L5', 'iron-hammerer'),
   ('VIKING', 'PLACE', 'L5', 'javelin-flinger'),
   ('VIKING', 'PLACE', 'L5', 'kettle-watcher'),
   ('VIKING', 'PLACE', 'L5', 'kindler'),
   ('VIKING', 'PLACE', 'L5', 'knife-thrower'),
   ('VIKING', 'PLACE', 'L5', 'lamb-roaster'),
   ('VIKING', 'PLACE', 'L5', 'leather-worker'),
   ('VIKING', 'PLACE', 'L5', 'log-hauler'),
   ('VIKING', 'PLACE', 'L5', 'lookout'),
   ('VIKING', 'PLACE', 'L5', 'mail-weaver'),
   ('VIKING', 'PLACE', 'L5', 'mead-brewer'),
   ('VIKING', 'PLACE', 'L5', 'mead-hall brawler'),
   ('VIKING', 'PLACE', 'L5', 'mead-runner'),
   ('VIKING', 'PLACE', 'L5', 'mead-sipper'),
   ('VIKING', 'PLACE', 'L5', 'meat-hanger'),
   ('VIKING', 'PLACE', 'L5', 'meat-salter'),
   ('VIKING', 'PLACE', 'L5', 'melee-trainer'),
   ('VIKING', 'PLACE', 'L5', 'milk-maiden'),
   ('VIKING', 'PLACE', 'L5', 'moss-scraper'),
   ('VIKING', 'PLACE', 'L5', 'mud-patcher'),
   ('VIKING', 'PLACE', 'L5', 'mushroom-finder'),
   ('VIKING', 'PLACE', 'L5', 'net-caster'),
   ('VIKING', 'PLACE', 'L5', 'net-mender'),
   ('VIKING', 'PLACE', 'L5', 'oat-planter'),
   ('VIKING', 'PLACE', 'L5', 'ore-hauler'),
   ('VIKING', 'PLACE', 'L5', 'oven-feeder'),
   ('VIKING', 'PLACE', 'L5', 'oven-keeper'),
   ('VIKING', 'PLACE', 'L5', 'pan-scraper'),
   ('VIKING', 'PLACE', 'L5', 'path-mender'),
   ('VIKING', 'PLACE', 'L5', 'peasant'),
   ('VIKING', 'PLACE', 'L5', 'pig-herder'),
   ('VIKING', 'PLACE', 'L5', 'pig-slopper'),
   ('VIKING', 'PLACE', 'L5', 'pottage-maker'),
   ('VIKING', 'PLACE', 'L5', 'quiver-bearer'),
   ('VIKING', 'PLACE', 'L5', 'raider'),
   ('VIKING', 'PLACE', 'L5', 'reed-gatherer'),
   ('VIKING', 'PLACE', 'L5', 'reed-weaver'),
   ('VIKING', 'PLACE', 'L5', 'root-forager'),
   ('VIKING', 'PLACE', 'L5', 'root-picker'),
   ('VIKING', 'PLACE', 'L5', 'rope-maker'),
   ('VIKING', 'PLACE', 'L5', 'saber-tester'),
   ('VIKING', 'PLACE', 'L5', 'sailor'),
   ('VIKING', 'PLACE', 'L5', 'salt-curer'),
   ('VIKING', 'PLACE', 'L5', 'salt-panner'),
   ('VIKING', 'PLACE', 'L5', 'scout'),
   ('VIKING', 'PLACE', 'L5', 'scrimshander'),
   ('VIKING', 'PLACE', 'L5', 'seed-keeper'),
   ('VIKING', 'PLACE', 'L5', 'shepherd'),
   ('VIKING', 'PLACE', 'L5', 'shield-breaker'),
   ('VIKING', 'PLACE', 'L5', 'shield-maiden'),
   ('VIKING', 'PLACE', 'L5', 'shield-painter'),
   ('VIKING', 'PLACE', 'L5', 'shield-splitter'),
   ('VIKING', 'PLACE', 'L5', 'skald'),
   ('VIKING', 'PLACE', 'L5', 'skillet-turner'),
   ('VIKING', 'PLACE', 'L5', 'skirmish-scout'),
   ('VIKING', 'PLACE', 'L5', 'sling-stone hurler'),
   ('VIKING', 'PLACE', 'L5', 'sling-wielder'),
   ('VIKING', 'PLACE', 'L5', 'smith'),
   ('VIKING', 'PLACE', 'L5', 'smokehouse-tender'),
   ('VIKING', 'PLACE', 'L5', 'snow-packer'),
   ('VIKING', 'PLACE', 'L5', 'snow-runner'),
   ('VIKING', 'PLACE', 'L5', 'snow-shoveler'),
   ('VIKING', 'PLACE', 'L5', 'soup-sipper'),
   ('VIKING', 'PLACE', 'L5', 'spear-caster'),
   ('VIKING', 'PLACE', 'L5', 'spear-polisher'),
   ('VIKING', 'PLACE', 'L5', 'spear-setter'),
   ('VIKING', 'PLACE', 'L5', 'spear-thrower'),
   ('VIKING', 'PLACE', 'L5', 'stew-brewer'),
   ('VIKING', 'PLACE', 'L5', 'stew-sampler'),
   ('VIKING', 'PLACE', 'L5', 'stock-pot stirrer'),
   ('VIKING', 'PLACE', 'L5', 'stone-cutter'),
   ('VIKING', 'PLACE', 'L5', 'storm-watcher'),
   ('VIKING', 'PLACE', 'L5', 'sword-sharpener'),
   ('VIKING', 'PLACE', 'L5', 'sword-wielder'),
   ('VIKING', 'PLACE', 'L5', 'tanner'),
   ('VIKING', 'PLACE', 'L5', 'thatcher'),
   ('VIKING', 'PLACE', 'L5', 'thrall'),
   ('VIKING', 'PLACE', 'L5', 'torch-bearer'),
   ('VIKING', 'PLACE', 'L5', 'track-layer'),
   ('VIKING', 'PLACE', 'L5', 'trader'),
   ('VIKING', 'PLACE', 'L5', 'training-dummy maker'),
   ('VIKING', 'PLACE', 'L5', 'trap-setter'),
   ('VIKING', 'PLACE', 'L5', 'turnip-grower'),
   ('VIKING', 'PLACE', 'L5', 'vinegar-bottler'),
   ('VIKING', 'PLACE', 'L5', 'war-club maker'),
   ('VIKING', 'PLACE', 'L5', 'war-horn blower'),
   ('VIKING', 'PLACE', 'L5', 'war-pick bearer'),
   ('VIKING', 'PLACE', 'L5', 'water-fetcher'),
   ('VIKING', 'PLACE', 'L5', 'weaver'),
   ('VIKING', 'PLACE', 'L5', 'wheat-binder'),
   ('VIKING', 'PLACE', 'L5', 'wood-fired baker'),
   ('VIKING', 'PLACE', 'L5', 'woodcutter');

commit;