use hierarchy_generator;

INSERT INTO `NameAdjectives` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('SPACE', 'PLACE', 'L4', '42-Encoded'),
   ('SPACE', 'PLACE', 'L4', 'Acid-Blooded'),
   ('SPACE', 'PLACE', 'L4', 'Aiur-Fallen'),
   ('SPACE', 'PLACE', 'L4', 'Alpha Quadrant'),
   ('SPACE', 'PLACE', 'L4', 'Ancient'),
   ('SPACE', 'PLACE', 'L4', 'Andorian'),
   ('SPACE', 'PLACE', 'L4', 'Artificial'),
   ('SPACE', 'PLACE', 'L4', 'Asteroid-Linked'),
   ('SPACE', 'PLACE', 'L4', 'Babel-Fished'),
   ('SPACE', 'PLACE', 'L4', 'Bacta-Filled'),
   ('SPACE', 'PLACE', 'L4', 'Bajoran'),
   ('SPACE', 'PLACE', 'L4', 'Battlecruiser-Patrolled'),
   ('SPACE', 'PLACE', 'L4', 'Beskar-Strong'),
   ('SPACE', 'PLACE', 'L4', 'Binary-Star'),
   ('SPACE', 'PLACE', 'L4', 'Bio-Generated'),
   ('SPACE', 'PLACE', 'L4', 'Bioengineered'),
   ('SPACE', 'PLACE', 'L4', 'Blaster-scorched'),
   ('SPACE', 'PLACE', 'L4', 'Borg'),
   ('SPACE', 'PLACE', 'L4', 'Bureaucratically Dense'),
   ('SPACE', 'PLACE', 'L4', 'Cardassian'),
   ('SPACE', 'PLACE', 'L4', 'Celestial'),
   ('SPACE', 'PLACE', 'L4', 'Chitinous'),
   ('SPACE', 'PLACE', 'L4', 'Chrono-Aligned'),
   ('SPACE', 'PLACE', 'L4', 'Chrono-Enhanced'),
   ('SPACE', 'PLACE', 'L4', 'Chronologically Tangled'),
   ('SPACE', 'PLACE', 'L4', 'Clone-Held'),
   ('SPACE', 'PLACE', 'L4', 'Collective'),
   ('SPACE', 'PLACE', 'L4', 'Coruscanti'),
   ('SPACE', 'PLACE', 'L4', 'Cosmic'),
   ('SPACE', 'PLACE', 'L4', 'Cryo-sleep'),
   ('SPACE', 'PLACE', 'L4', 'Cryo-tech'),
   ('SPACE', 'PLACE', 'L4', 'Cybernetic'),
   ('SPACE', 'PLACE', 'L4', 'Dark Planetary'),
   ('SPACE', 'PLACE', 'L4', 'Dark Side'),
   ('SPACE', 'PLACE', 'L4', 'Dark Templar-Haunted'),
   ('SPACE', 'PLACE', 'L4', 'Delta Quadrant'),
   ('SPACE', 'PLACE', 'L4', 'Depressingly Sentient'),
   ('SPACE', 'PLACE', 'L4', 'Dominion'),
   ('SPACE', 'PLACE', 'L4', 'Dominion-Controlled'),
   ('SPACE', 'PLACE', 'L4', 'Driftcore'),
   ('SPACE', 'PLACE', 'L4', 'Droid-Made'),
   ('SPACE', 'PLACE', 'L4', 'Dustborn'),
   ('SPACE', 'PLACE', 'L4', 'Echo-linked'),
   ('SPACE', 'PLACE', 'L4', 'Enterprise-Class'),
   ('SPACE', 'PLACE', 'L4', 'Existentially Compromised'),
   ('SPACE', 'PLACE', 'L4', 'Exoskeletal'),
   ('SPACE', 'PLACE', 'L4', 'Expeditionary'),
   ('SPACE', 'PLACE', 'L4', 'Federation'),
   ('SPACE', 'PLACE', 'L4', 'Ferengi'),
   ('SPACE', 'PLACE', 'L4', 'Fleet-Crushed'),
   ('SPACE', 'PLACE', 'L4', 'Fluffy Yet Dangerous'),
   ('SPACE', 'PLACE', 'L4', 'Force-touched'),
   ('SPACE', 'PLACE', 'L4', 'Fordian'),
   ('SPACE', 'PLACE', 'L4', 'Frozen Belt'),
   ('SPACE', 'PLACE', 'L4', 'Galactic'),
   ('SPACE', 'PLACE', 'L4', 'Galvanic'),
   ('SPACE', 'PLACE', 'L4', 'Gamma'),
   ('SPACE', 'PLACE', 'L4', 'Genesis'),
   ('SPACE', 'PLACE', 'L4', 'Geo-Solar'),
   ('SPACE', 'PLACE', 'L4', 'Ghost-Operated'),
   ('SPACE', 'PLACE', 'L4', 'Gravitic'),
   ('SPACE', 'PLACE', 'L4', 'Hive-Bred'),
   ('SPACE', 'PLACE', 'L4', 'Hiveborn'),
   ('SPACE', 'PLACE', 'L4', 'Holographic'),
   ('SPACE', 'PLACE', 'L4', 'Hunter-Caste'),
   ('SPACE', 'PLACE', 'L4', 'Hutt-Controlled'),
   ('SPACE', 'PLACE', 'L4', 'Hybridic'),
   ('SPACE', 'PLACE', 'L4', 'Hyperintelligent'),
   ('SPACE', 'PLACE', 'L4', 'Imperial'),
   ('SPACE', 'PLACE', 'L4', 'Infestation-Zone'),
   ('SPACE', 'PLACE', 'L4', 'Infested'),
   ('SPACE', 'PLACE', 'L4', 'Infinite-Improbable'),
   ('SPACE', 'PLACE', 'L4', 'Infrared'),
   ('SPACE', 'PLACE', 'L4', 'Ionized'),
   ('SPACE', 'PLACE', 'L4', 'Isolated'),
   ('SPACE', 'PLACE', 'L4', 'Kerrigan-Forsaken'),
   ('SPACE', 'PLACE', 'L4', 'Kessel-Bound'),
   ('SPACE', 'PLACE', 'L4', 'Klingon'),
   ('SPACE', 'PLACE', 'L4', 'Koprulu-Sector'),
   ('SPACE', 'PLACE', 'L4', 'Light Side'),
   ('SPACE', 'PLACE', 'L4', 'Lunar'),
   ('SPACE', 'PLACE', 'L4', 'Mandalorian'),
   ('SPACE', 'PLACE', 'L4', 'Marvin-Built'),
   ('SPACE', 'PLACE', 'L4', 'Mirrorverse'),
   ('SPACE', 'PLACE', 'L4', 'Mostly Harmless'),
   ('SPACE', 'PLACE', 'L4', 'Nebula-Hidden'),
   ('SPACE', 'PLACE', 'L4', 'Nebular'),
   ('SPACE', 'PLACE', 'L4', 'Neutral Zone'),
   ('SPACE', 'PLACE', 'L4', 'Orbital-Damaged'),
   ('SPACE', 'PLACE', 'L4', 'Outer Rim'),
   ('SPACE', 'PLACE', 'L4', 'Overmind-Scarred'),
   ('SPACE', 'PLACE', 'L4', 'Pan-Galactic'),
   ('SPACE', 'PLACE', 'L4', 'Photon'),
   ('SPACE', 'PLACE', 'L4', 'Planet-Slayed'),
   ('SPACE', 'PLACE', 'L4', 'Plasma-wreathed'),
   ('SPACE', 'PLACE', 'L4', 'Pointless'),
   ('SPACE', 'PLACE', 'L4', 'Polarity-Shielded'),
   ('SPACE', 'PLACE', 'L4', 'Predator-Blooded'),
   ('SPACE', 'PLACE', 'L4', 'Predatorial'),
   ('SPACE', 'PLACE', 'L4', 'Prime Directive'),
   ('SPACE', 'PLACE', 'L4', 'Primitive'),
   ('SPACE', 'PLACE', 'L4', 'Probability-Twisted'),
   ('SPACE', 'PLACE', 'L4', 'Protoss-Guarded'),
   ('SPACE', 'PLACE', 'L4', 'Psi-Stormed'),
   ('SPACE', 'PLACE', 'L4', 'Psionically Charged'),
   ('SPACE', 'PLACE', 'L4', 'Pulse-Linked'),
   ('SPACE', 'PLACE', 'L4', 'Pulse-Ravaged'),
   ('SPACE', 'PLACE', 'L4', 'Quantum Slipstream'),
   ('SPACE', 'PLACE', 'L4', 'Quantum'),
   ('SPACE', 'PLACE', 'L4', 'Raynor-Loyal'),
   ('SPACE', 'PLACE', 'L4', 'Rebel'),
   ('SPACE', 'PLACE', 'L4', 'Red Alert'),
   ('SPACE', 'PLACE', 'L4', 'Rift-Born'),
   ('SPACE', 'PLACE', 'L4', 'Romulan'),
   ('SPACE', 'PLACE', 'L4', 'Section 31'),
   ('SPACE', 'PLACE', 'L4', 'Senatorial'),
   ('SPACE', 'PLACE', 'L4', 'Siege-Born'),
   ('SPACE', 'PLACE', 'L4', 'Sithborne'),
   ('SPACE', 'PLACE', 'L4', 'Skullmarked'),
   ('SPACE', 'PLACE', 'L4', 'Solar'),
   ('SPACE', 'PLACE', 'L4', 'Starfleet'),
   ('SPACE', 'PLACE', 'L4', 'Stealth-Hardened'),
   ('SPACE', 'PLACE', 'L4', 'Stellar'),
   ('SPACE', 'PLACE', 'L4', 'Sub-Etha Connected'),
   ('SPACE', 'PLACE', 'L4', 'Subspace'),
   ('SPACE', 'PLACE', 'L4', 'Substellar'),
   ('SPACE', 'PLACE', 'L4', 'Swarm-Touched'),
   ('SPACE', 'PLACE', 'L4', 'Synth'),
   ('SPACE', 'PLACE', 'L4', 'Synthetic'),
   ('SPACE', 'PLACE', 'L4', 'Tachyonic'),
   ('SPACE', 'PLACE', 'L4', 'Tatooinian'),
   ('SPACE', 'PLACE', 'L4', 'Tea-Deprived'),
   ('SPACE', 'PLACE', 'L4', 'Temporal'),
   ('SPACE', 'PLACE', 'L4', 'Terraforming'),
   ('SPACE', 'PLACE', 'L4', 'Terran-Fortified'),
   ('SPACE', 'PLACE', 'L4', 'Titan-class'),
   ('SPACE', 'PLACE', 'L4', 'Towel-Friendly'),
   ('SPACE', 'PLACE', 'L4', 'Transwarp'),
   ('SPACE', 'PLACE', 'L4', 'Trekian'),
   ('SPACE', 'PLACE', 'L4', 'Trill'),
   ('SPACE', 'PLACE', 'L4', 'Trillian-Touched'),
   ('SPACE', 'PLACE', 'L4', 'Trophy-Rich'),
   ('SPACE', 'PLACE', 'L4', 'Trophyless'),
   ('SPACE', 'PLACE', 'L4', 'Tunneler'),
   ('SPACE', 'PLACE', 'L4', 'Uncharted'),
   ('SPACE', 'PLACE', 'L4', 'Uncolonized'),
   ('SPACE', 'PLACE', 'L4', 'Unreasonably Large'),
   ('SPACE', 'PLACE', 'L4', 'Vogon-Occupied'),
   ('SPACE', 'PLACE', 'L4', 'Void-Ruptured'),
   ('SPACE', 'PLACE', 'L4', 'Void-Sealed'),
   ('SPACE', 'PLACE', 'L4', 'Voidborne'),
   ('SPACE', 'PLACE', 'L4', 'Vulcan'),
   ('SPACE', 'PLACE', 'L4', 'Warp-Fused'),
   ('SPACE', 'PLACE', 'L4', 'Warp-Gated'),
   ('SPACE', 'PLACE', 'L4', 'Warp-enabled'),
   ('SPACE', 'PLACE', 'L4', 'Weyland-Yutani'),
   ('SPACE', 'PLACE', 'L4', 'Wookiee-Carved'),
   ('SPACE', 'PLACE', 'L4', 'Xel`Naga-Touched'),
   ('SPACE', 'PLACE', 'L4', 'Xenomorphic'),
   ('SPACE', 'PLACE', 'L4', 'Yautja'),
   ('SPACE', 'PLACE', 'L4', 'Zaphodian'),
   ('SPACE', 'PLACE', 'L4', 'Zerg-Infested'),
   ('SPACE', 'PLACE', 'L4', 'Facehugger-Spawned');

commit;