use hierarchy_generator;

INSERT INTO `NameAdjectives` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('SPACE', 'PLACE', 'L1', 'Ancient'),
   ('SPACE', 'PLACE', 'L1', 'Futuristic'),
   ('SPACE', 'PLACE', 'L1', 'Celestial'),
   ('SPACE', 'PLACE', 'L1', 'Stellar'),
   ('SPACE', 'PLACE', 'L1', 'Galactic'),
   ('SPACE', 'PLACE', 'L1', 'Interstellar'),
   ('SPACE', 'PLACE', 'L1', 'Quantum'),
   ('SPACE', 'PLACE', 'L1', 'Nebular'),
   ('SPACE', 'PLACE', 'L1', 'Cosmic'),
   ('SPACE', 'PLACE', 'L1', 'Void'),
   ('SPACE', 'PLACE', 'L1', 'Ethereal'),
   ('SPACE', 'PLACE', 'L1', 'Transcendent'),
   ('SPACE', 'PLACE', 'L1', 'Techno'),
   ('SPACE', 'PLACE', 'L1', 'Starborn'),
   ('SPACE', 'PLACE', 'L1', 'Imperial'),
   ('SPACE', 'PLACE', 'L1', 'Sovereign'),
   ('SPACE', 'PLACE', 'L1', 'Dreadnought'),
   ('SPACE', 'PLACE', 'L1', 'Infinite'),
   ('SPACE', 'PLACE', 'L1', 'Hypernova'),
   ('SPACE', 'PLACE', 'L1', 'Extragalactic'),
   ('SPACE', 'PLACE', 'L1', 'Vast'),
   ('SPACE', 'PLACE', 'L1', 'Luminous'),
   ('SPACE', 'PLACE', 'L1', 'Alpha'),
   ('SPACE', 'PLACE', 'L1', 'Chrono'),
   ('SPACE', 'PLACE', 'L1', 'Omega'),
   ('SPACE', 'PLACE', 'L1', 'Nebulon'),
   ('SPACE', 'PLACE', 'L1', 'Astral'),
   ('SPACE', 'PLACE', 'L1', 'Chronos'),
   ('SPACE', 'PLACE', 'L1', 'Titanic'),
   ('SPACE', 'PLACE', 'L1', 'Intergalactic'),
   ('SPACE', 'PLACE', 'L1', 'Spectral'),
   ('SPACE', 'PLACE', 'L1', 'Infinite'),
   ('SPACE', 'PLACE', 'L1', 'Astronomical'),
   ('SPACE', 'PLACE', 'L1', 'Starlight'),
   ('SPACE', 'PLACE', 'L1', 'Eclipse'),
   ('SPACE', 'PLACE', 'L1', 'Supreme'),
   ('SPACE', 'PLACE', 'L1', 'Nova'),
   ('SPACE', 'PLACE', 'L1', 'Quantum'),
   ('SPACE', 'PLACE', 'L1', 'Ascendant'),
   ('SPACE', 'PLACE', 'L1', 'Distant'),
   ('SPACE', 'PLACE', 'L1', 'Boundless'),
   ('SPACE', 'PLACE', 'L1', 'Nebula'),
   ('SPACE', 'PLACE', 'L1', 'Eclipse'),
   ('SPACE', 'PLACE', 'L1', 'Starborn'),
   ('SPACE', 'PLACE', 'L1', 'Exponential');


commit;