use hierarchy_generator;

INSERT INTO `NameAdjectives` (`Theme`, `Category`, `NodeLevel`, `Value`) VALUES 
   ('SPACE', 'PLACE', 'L2', 'Abandoned'),
   ('SPACE', 'PLACE', 'L2', 'Ancient'),
   ('SPACE', 'PLACE', 'L2', 'Astartes-held'),
   ('SPACE', 'PLACE', 'L2', 'Blackened'),
   ('SPACE', 'PLACE', 'L2', 'Blighted'),
   ('SPACE', 'PLACE', 'L2', 'Blood-soaked'),
   ('SPACE', 'PLACE', 'L2', 'Boundless'),
   ('SPACE', 'PLACE', 'L2', 'Burning'),
   ('SPACE', 'PLACE', 'L2', 'Celestial'),
   ('SPACE', 'PLACE', 'L2', 'Chaotic'),
   ('SPACE', 'PLACE', 'L2', 'Corrupted'),
   ('SPACE', 'PLACE', 'L2', 'Crimson'),
   ('SPACE', 'PLACE', 'L2', 'Crimson-plagued'),
   ('SPACE', 'PLACE', 'L2', 'Dark Imperium'),
   ('SPACE', 'PLACE', 'L2', 'Dark'),
   ('SPACE', 'PLACE', 'L2', 'Deathworld'),
   ('SPACE', 'PLACE', 'L2', 'Doomed'),
   ('SPACE', 'PLACE', 'L2', 'Endless'),
   ('SPACE', 'PLACE', 'L2', 'Epic'),
   ('SPACE', 'PLACE', 'L2', 'Eternal'),
   ('SPACE', 'PLACE', 'L2', 'Exiled'),
   ('SPACE', 'PLACE', 'L2', 'Fading'),
   ('SPACE', 'PLACE', 'L2', 'Forbidden'),
   ('SPACE', 'PLACE', 'L2', 'Forged'),
   ('SPACE', 'PLACE', 'L2', 'Forsaken'),
   ('SPACE', 'PLACE', 'L2', 'Fragmented'),
   ('SPACE', 'PLACE', 'L2', 'Frozen'),
   ('SPACE', 'PLACE', 'L2', 'Galactic'),
   ('SPACE', 'PLACE', 'L2', 'Glorious'),
   ('SPACE', 'PLACE', 'L2', 'Glowing'),
   ('SPACE', 'PLACE', 'L2', 'God-forsaken'),
   ('SPACE', 'PLACE', 'L2', 'Hellish'),
   ('SPACE', 'PLACE', 'L2', 'Heretic'),
   ('SPACE', 'PLACE', 'L2', 'Hidden'),
   ('SPACE', 'PLACE', 'L2', 'Imperial'),
   ('SPACE', 'PLACE', 'L2', 'Lifeless'),
   ('SPACE', 'PLACE', 'L2', 'Lost'),
   ('SPACE', 'PLACE', 'L2', 'Luminous'),
   ('SPACE', 'PLACE', 'L2', 'Mysterious'),
   ('SPACE', 'PLACE', 'L2', 'Nebular'),
   ('SPACE', 'PLACE', 'L2', 'Oblivion-bound'),
   ('SPACE', 'PLACE', 'L2', 'Ominous'),
   ('SPACE', 'PLACE', 'L2', 'Radiant'),
   ('SPACE', 'PLACE', 'L2', 'Ruinous'),
   ('SPACE', 'PLACE', 'L2', 'Shattered'),
   ('SPACE', 'PLACE', 'L2', 'Shimmering'),
   ('SPACE', 'PLACE', 'L2', 'Stellar'),
   ('SPACE', 'PLACE', 'L2', 'Uncharted'),
   ('SPACE', 'PLACE', 'L2', 'Unknown'),
   ('SPACE', 'PLACE', 'L2', 'Unyielding'),
   ('SPACE', 'PLACE', 'L2', 'Vast'),
   ('SPACE', 'PLACE', 'L2', 'Vengeful'),
   ('SPACE', 'PLACE', 'L2', 'Void'),
   ('SPACE', 'PLACE', 'L2', 'War-hardened'),
   ('SPACE', 'PLACE', 'L2', 'War-torn'),
   ('SPACE', 'PLACE', 'L2', 'Warp-infested');

commit;